// remote/activity-view.js - GENERATED by test/_activity-bundle.mjs (B-874 v2.0.24). DO NOT EDIT.
// The phone's copy of lib/activity-view.js, wrapped unchanged.
// Edit lib/, then: node test/_activity-bundle.mjs --write
(function (root) {
const __m = {};
// ---- lib/activity-view.js ----
(function () {
"use strict";
// lib/activity-view.js - B-870 / B-874 (v2.0.24): what the shared top bar says.
//
// PURE and import-free (no chrome, no DOM): the laptop's top bar
// (lib/topbar.js) and the phone's (remote/topbar-view.js, through the
// generated remote/activity-view.js - test/_activity-bundle.mjs) run the SAME
// code over the SAME value, so the two can never word a job differently.
//
// Input = the `shopperActivity` value lib/activity.js writes (the phone gets
// the same shape as payload.activity):
//   { jobs: { [id]: { id, label, running, step, total, pct, text, startedAt, updatedAt } },
//     last: { id, label, ok, text, finishedAt, durationMs } | null }
// pct null = indeterminate (the bar rolls instead of filling).
//
// Output:
//   { mode: "idle"|"run", pct (0-100 int | null), label, text,
//     stepText ("step 3 of 7" | ""), stalledSec (0 unless 45+ s with no new step),
//     moreCount (other running jobs), lastLine ("Last full refresh 12:41 PM · done in 1m 52s" | "") }

const STALL_AFTER_MS = 45000;
const TZ = "America/Chicago";

function num(v) {
  const n = Number(v);
  return v === null || v === undefined || v === "" || !Number.isFinite(n) ? null : n;
}

/** "45s", "1m 05s", "1h 02m". */
function formatDuration(ms) {
  const n = num(ms);
  if (n === null || n < 0) return "";
  const s = Math.floor(n / 1000);
  if (s < 60) return `${s}s`;
  const m = Math.floor(s / 60);
  if (m < 60) return `${m}m ${String(s % 60).padStart(2, "0")}s`;
  return `${Math.floor(m / 60)}h ${String(m % 60).padStart(2, "0")}m`;
}

/** "12:41 PM" in Central time (Zach's clock). */
function formatClock(ms) {
  const n = num(ms);
  if (n === null) return "";
  try {
    return new Intl.DateTimeFormat("en-US", { timeZone: TZ, hour: "numeric", minute: "2-digit" }).format(new Date(n));
  } catch (e) {
    return "";
  }
}

function lower1(s) {
  return s ? s.charAt(0).toLowerCase() + s.slice(1) : s;
}

function lastLineOf(last) {
  if (!last || typeof last !== "object") return "";
  const label = String(last.label || "").trim();
  const at = formatClock(last.finishedAt);
  if (!label && !at) return "";
  const head = ("Last " + lower1(label || "job")).trim() + (at ? " " + at : "");
  const took = formatDuration(last.durationMs);
  if (last.ok === false) return head + (took ? ` · stopped after ${took}` : " · stopped");
  return head + (took ? ` · done in ${took}` : "");
}

function pctOf(job) {
  if (typeof job.pct === "number" && Number.isFinite(job.pct)) return Math.max(0, Math.min(100, Math.round(job.pct)));
  if (job.pct === undefined) {
    const step = num(job.step), total = num(job.total);
    if (step !== null && total !== null && total > 0) return Math.max(0, Math.min(100, Math.round((step / total) * 100)));
  }
  return null;
}

function activityDisplay(state, nowMs) {
  const now = num(nowMs) === null ? Date.now() : Number(nowMs);
  const st = state && typeof state === "object" ? state : {};
  const jobs = st.jobs && typeof st.jobs === "object" ? Object.values(st.jobs) : [];
  const running = jobs
    .filter((j) => j && typeof j === "object" && j.running)
    .sort((a, b) => (num(b.updatedAt) || num(b.startedAt) || 0) - (num(a.updatedAt) || num(a.startedAt) || 0));
  const lastLine = lastLineOf(st.last);
  if (!running.length) {
    return { mode: "idle", pct: null, label: "", text: "", stepText: "", stalledSec: 0, moreCount: 0, lastLine };
  }
  const job = running[0];
  const label = String(job.label || "Working").trim();
  const text = String(job.text || "").trim() || label;
  const step = num(job.step), total = num(job.total);
  const stepText = step !== null && total !== null && total > 0 ? `step ${step} of ${total}` : "";
  const seen = num(job.updatedAt) !== null ? num(job.updatedAt) : num(job.startedAt);
  const quiet = seen === null ? 0 : now - seen;
  const stalledSec = quiet >= STALL_AFTER_MS ? Math.floor(quiet / 1000) : 0;
  return { mode: "run", pct: pctOf(job), label, text, stepText, stalledSec, moreCount: running.length - 1, lastLine };
}

/** The one-line wording both bars print (so the phone and the laptop match). */
function activityLine(d) {
  if (!d || d.mode !== "run") return { head: "READY", rest: d && d.lastLine ? d.lastLine : "", warn: "" };
  const parts = [d.text];
  if (d.stepText) parts.push(d.stepText);
  if (d.moreCount > 0) parts.push(`+${d.moreCount} more running`);
  return {
    head: d.pct === null ? "WORKING" : `${d.pct}%`,
    rest: parts.join(" · "),
    warn: d.stalledSec ? `no new step for ${formatDuration(d.stalledSec * 1000)}` : "",
  };
}
__m["activity-view.js"] = { STALL_AFTER_MS, formatDuration, formatClock, activityDisplay, activityLine };
})();
root.ShopperActivityView = Object.freeze(Object.assign({}, ...Object.values(__m)));
})(typeof self !== "undefined" ? self : globalThis);
