// remote/belowmin-lib.js - GENERATED by test/_belowmin-bundle.mjs (B-741 v2.01, B-746 v2.0.2). DO NOT EDIT.
// The phone's copy of lib/sellersnap-price.js, lib/keepa-chart-svg.js, wrapped unchanged.
// Edit lib/, then: node test/_belowmin-bundle.mjs --write
(function (root) {
const __m = {};
// ---- lib/sellersnap-price.js ----
(function () {
"use strict";
// Shopper 2 (v2.01, B-741): profit at a price, the way Seller Snap works it
// out, and the price Shopper suggests when the Buy Box is under Zach's min.
// PURE - no chrome, no fetch, no I/O.
//
// Measured 2026-09-30 against Seller Snap's own numbers (scope doc
// claude/b741-bb-below-min-scope-2026-09-30.md section 3): B0C1HPL15D at its
// $16.37 min -> profit $0.51, margin 3.14% (Seller Snap 3.15%), ROI 5.74%
// (Seller Snap min_markup_on_cost 5.74). ROI here is Seller Snap's own
// definition: profit / cost (cost without the additional cost), which is
// what its ROI column shows.
//
// Zach's rules (2026-09-30):
//   - the suggestion takes the Buy Box: the highest price ending in 7 cents
//     (.07, .17 ... .97) that is strictly below the Buy Box;
//   - it may go down to break-even, never a loss - if the .x7 price loses
//     money the suggestion is "Don't change";
//   - ROI and margin at the suggested price are always shown.

const TREND_DEAD_BAND = 0.15;

const cents = (v) => Math.round(Number(v) * 100);
const round2 = (v) => Math.round(v * 100) / 100;
const numOr = (v, d = null) => {
  if (v == null || v === "") return d;
  const n = typeof v === "number" ? v : Number(String(v).replace(/[$,%\s]/g, ""));
  return Number.isFinite(n) ? n : d;
};

// Amazon's referral fee as Seller Snap models it.
//   type "step": the reduced % on the WHOLE price at or under the threshold
//                (Amazon's $10 rule), the regular % above it.
//   type "portion above threshold": regular % up to the threshold, reduced %
//                on the part above it.
// Never below the minimum fee.
function referralFee(price, fees = {}) {
  const p = Number(price);
  const regular = numOr(fees.regularPerc, 15);
  const reduced = numOr(fees.reducedPerc, null);
  const threshold = numOr(fees.reducedThreshold, null);
  const type = String(fees.reducedType || "").toLowerCase();
  let fee;
  if (reduced != null && threshold != null && type === "step") {
    fee = p * ((p <= threshold ? reduced : regular) / 100);
  } else if (reduced != null && threshold != null && type.indexOf("portion") === 0) {
    fee = p <= threshold ? p * (regular / 100) : threshold * (regular / 100) + (p - threshold) * (reduced / 100);
  } else {
    fee = p * (regular / 100);
  }
  const minFee = numOr(fees.minFee, 0) || 0;
  return Math.max(fee, minFee);
}

// FBA fee: the first tier whose "up" is at or above the price (null = no top).
// No tiers -> the one fee Seller Snap reported for the current price.
function fbaFee(price, fees = {}) {
  const tiers = Array.isArray(fees.fbaTiers) ? fees.fbaTiers : [];
  for (const t of tiers) {
    if (!t) continue;
    const up = t.up == null ? null : Number(t.up);
    if (up == null || Number(price) <= up) return numOr(t.value, 0);
  }
  return numOr(fees.fbaFee, 0) || 0;
}

// { profit, margin, roi } at a price, or null when cost is unknown.
function profitAt(price, row) {
  const p = numOr(price);
  const cost = numOr(row && row.cost);
  if (p == null || p <= 0 || cost == null) return null;
  const addl = numOr(row.additionalCost, 0) || 0;
  const fees = row.fees || {};
  const profit = p - referralFee(p, fees) - fbaFee(p, fees) - cost - addl;
  return {
    price: round2(p),
    profit: round2(profit),
    margin: round2((profit / p) * 100),
    roi: cost > 0 ? round2((profit / cost) * 100) : null,
  };
}

// The lowest price (to the cent) that does not lose money, searched up to
// the ceiling. null = none found under it.
function breakEven(row, ceiling = 1000) {
  const top = cents(ceiling);
  for (let c = 1; c <= top; c++) {
    const r = profitAt(c / 100, row);
    if (!r) return null;
    if (r.profit >= 0) return c / 100;
  }
  return null;
}

// The highest price ending in 7 cents that is strictly below the Buy Box.
function highestSevenBelow(bb) {
  const b = cents(bb);
  if (!Number.isFinite(b) || b <= 7) return null;
  const top = b - 1;
  const c = top - ((((top - 7) % 10) + 10) % 10);
  return c > 0 ? c / 100 : null;
}

// Shopper's suggestion for a row: { price, profit, margin, roi } or
// { price: null, reason, breakEven }.
function suggestPrice(row) {
  const bb = numOr(row && row.bb);
  if (bb == null || bb <= 0) return { price: null, reason: "No Buy Box price right now." };
  const s = highestSevenBelow(bb);
  if (s == null) return { price: null, reason: "The Buy Box is too low to price under." };
  const at = profitAt(s, row);
  if (!at) return { price: null, reason: "Seller Snap has no cost for this listing." };
  if (at.profit < 0) {
    const be = breakEven(row, Math.max(bb, numOr(row.min, bb)) + 50);
    return {
      price: null,
      breakEven: be,
      reason: `Can't beat the Buy Box ($${bb.toFixed(2)}) without a loss - break-even is ${be == null ? "unknown" : "$" + be.toFixed(2)}.`,
    };
  }
  return at;
}

// Speeding up / slowing down: this 7 days' velocity against the 7 before.
function velocityTrend(now, before) {
  const a = numOr(now);
  const b = numOr(before);
  if (a == null && b == null) return { dir: "none", label: "no sales data" };
  if (b == null || b === 0) {
    if (a == null || a === 0) return { dir: "flat", label: "no sales either week" };
    return { dir: "up", label: "new sales this week" };
  }
  const change = ((a || 0) - b) / b;
  const pct = Math.round(change * 100);
  if (change > TREND_DEAD_BAND) return { dir: "up", label: `speeding up (+${pct}%)`, pct };
  if (change < -TREND_DEAD_BAND) return { dir: "down", label: `slowing down (${pct}%)`, pct };
  return { dir: "flat", label: `steady (${pct >= 0 ? "+" : ""}${pct}%)`, pct };
}

// A price Zach typed: a positive number with at most two decimals.
function parsePrice(text) {
  const t = String(text == null ? "" : text).trim().replace(/^\$/, "");
  if (!/^\d+(\.\d{1,2})?$/.test(t)) return null;
  const n = Number(t);
  return n > 0 ? n : null;
}
__m["sellersnap-price.js"] = { TREND_DEAD_BAND, referralFee, fbaFee, profitAt, breakEven, highestSevenBelow, suggestPrice, velocityTrend, parsePrice };
})();
// ---- lib/keepa-chart-svg.js ----
(function () {
"use strict";
// Shopper (v2.0.2, B-746): draws the three small Keepa panels on a Below Min
// card - Buy Box price / sales rank + monthly sold / new offer count - from
// lib/keepa-charts.js compactChart(). Import-free and DOM-agnostic (takes
// `doc`), so the phone runs this same file (remote/belowmin-lib.js bundle).
// Colours are classes (kc-*), set with --s-* tokens in each stylesheet.
const NS = "http://www.w3.org/2000/svg";
const KC_W = 320;
const KC_PAD_L = 38;
const KC_PAD_R = 38;
const KC_PANELS = [
  { key: "bb", title: "Buy Box", h: 64 },
  { key: "rank", title: "Sales rank · monthly sold", h: 64 },
  { key: "offers", title: "Offers", h: 48 },
];

function el(doc, tag, attrs = {}, text) {
  const n = doc.createElementNS(NS, tag);
  for (const [k, v] of Object.entries(attrs)) n.setAttribute(k, String(v));
  if (text != null) n.textContent = String(text);
  return n;
}

function extent(points) {
  const vals = (points || []).map((p) => p[1]).filter((v) => v != null && Number.isFinite(v));
  if (!vals.length) return null;
  let lo = Math.min(...vals);
  let hi = Math.max(...vals);
  if (lo === hi) { lo = lo * 0.95; hi = hi * 1.05 || 1; }
  return [lo, hi];
}

// A step line (Keepa series hold their value until the next point), with
// gaps where the value is null, held to the right edge.
function stepPath(points, days, x0, x1, y0, y1, ext) {
  if (!points || !points.length || !ext) return "";
  const X = (d) => x0 + (Math.max(0, Math.min(days, d)) / days) * (x1 - x0);
  const Y = (v) => y1 - ((v - ext[0]) / (ext[1] - ext[0])) * (y1 - y0);
  let d = "";
  let open = false;
  for (let i = 0; i < points.length; i++) {
    const [t, v] = points[i];
    const tNext = i + 1 < points.length ? points[i + 1][0] : days;
    if (v == null) { open = false; continue; }
    const x = X(t).toFixed(1), y = Y(v).toFixed(1), xe = X(tNext).toFixed(1);
    d += open ? `V${y}H${xe}` : `M${x},${y}H${xe}`;
    open = true;
  }
  return d;
}

const fmtMoney = (v) => "$" + (v >= 100 ? v.toFixed(0) : v.toFixed(2));
const fmtK = (v) => (v >= 10000 ? Math.round(v / 1000) + "k" : String(Math.round(v)));
const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
const fmtDay = (ms) => { const d = new Date(ms); return `${MONTHS[d.getUTCMonth()]} ${d.getUTCDate()}`; };

// Returns a <div class="kc"> holding the three panels, or a note when
// there is no chart yet.
function drawKeepaCharts(doc, chart, { asOf = null } = {}) {
  const wrap = doc.createElement("div");
  wrap.className = "kc";
  if (!chart) {
    const p = doc.createElement("div");
    p.className = "kc-empty";
    p.textContent = "Keepa charts not loaded yet - they are bought a few at a time (3 Keepa tokens each) and kept a day.";
    wrap.append(p);
    return wrap;
  }
  const days = chart.days || 90;
  const x0 = KC_PAD_L, x1 = KC_W - KC_PAD_R;
  KC_PANELS.forEach((panel, idx) => {
    const last = idx === KC_PANELS.length - 1;
    const H = panel.h + (last ? 14 : 0);
    const svg = el(doc, "svg", { viewBox: `0 0 ${KC_W} ${H}`, class: "kc-svg", role: "img", "aria-label": panel.title, preserveAspectRatio: "xMidYMid meet" });
    const y0 = 12, y1 = panel.h - 4;
    svg.append(el(doc, "text", { x: x0, y: 9, class: "kc-title" }, panel.title));
    svg.append(el(doc, "rect", { x: x0, y: y0, width: x1 - x0, height: y1 - y0, class: "kc-frame" }));
    const addLine = (pts, cls, ext) => { const d = stepPath(pts, days, x0, x1, y0, y1, ext); if (d) svg.append(el(doc, "path", { d, class: cls })); };
    const axis = (ext, side, fmt, cls) => {
      if (!ext) return;
      const x = side === "l" ? x0 - 3 : x1 + 3;
      const anchor = side === "l" ? "end" : "start";
      svg.append(el(doc, "text", { x, y: y0 + 7, "text-anchor": anchor, class: "kc-axis " + cls }, fmt(ext[1])));
      svg.append(el(doc, "text", { x, y: y1, "text-anchor": anchor, class: "kc-axis " + cls }, fmt(ext[0])));
    };
    if (panel.key === "bb") {
      const e = extent(chart.bb);
      addLine(chart.bb, "kc-line kc-bb", e);
      axis(e, "l", fmtMoney, "kc-bb-t");
      if (!e) svg.append(el(doc, "text", { x: (x0 + x1) / 2, y: (y0 + y1) / 2 + 3, "text-anchor": "middle", class: "kc-axis" }, "no Buy Box history"));
    } else if (panel.key === "rank") {
      const er = extent(chart.rank);
      const es = extent((chart.sold || []).map(([t, v]) => [t, v]).concat([[0, 0]]));
      addLine(chart.rank, "kc-line kc-rank", er);
      addLine(chart.sold, "kc-line kc-sold", es);
      axis(es, "l", fmtK, "kc-sold-t");
      axis(er, "r", (v) => "#" + fmtK(v), "kc-rank-t");
    } else {
      const e = extent((chart.offers || []).concat([[0, 0]]));
      addLine(chart.offers, "kc-line kc-offers", e);
      axis(e, "l", fmtK, "kc-offers-t");
      const startMs = chart.startMs, endMs = chart.endMs;
      [[x0, startMs, "start"], [(x0 + x1) / 2, (startMs + endMs) / 2, "middle"], [x1, endMs, "end"]].forEach(([x, ms, a]) => {
        svg.append(el(doc, "text", { x, y: H - 2, "text-anchor": a, class: "kc-axis" }, fmtDay(ms)));
      });
    }
    wrap.append(svg);
  });
  const note = doc.createElement("div");
  note.className = "kc-note";
  note.textContent = `Keepa, last ${days} days${asOf ? ` · as of ${fmtDay(asOf)}` : ""}`;
  wrap.append(note);
  return wrap;
}
__m["keepa-chart-svg.js"] = { KC_W, KC_PAD_L, KC_PAD_R, KC_PANELS, extent, stepPath, drawKeepaCharts };
})();
root.ShopperPrice = Object.freeze(Object.assign({}, ...Object.values(__m)));
})(self);
