// remote/belowmin-lib.js - GENERATED by test/_belowmin-bundle.mjs (B-741 v2.01, B-746 v2.0.2). DO NOT EDIT.
// The phone's copy of lib/sellersnap-price.js, lib/keepa-chart-svg.js, lib/sold-per-day.js, wrapped unchanged.
// Edit lib/, then: node test/_belowmin-bundle.mjs --write
(function (root) {
const __m = {};
// ---- lib/sellersnap-price.js ----
(function () {
"use strict";
// Shopper 2 (v2.01, B-741): profit at a price, the way Seller Snap works it
// out, and the price Shopper suggests when the Buy Box is under Zach's min.
// PURE - no chrome, no fetch, no I/O.
//
// Measured 2026-09-30 against Seller Snap's own numbers (scope doc
// claude/b741-bb-below-min-scope-2026-09-30.md section 3): B0C1HPL15D at its
// $16.37 min -> profit $0.51, margin 3.14% (Seller Snap 3.15%), ROI 5.74%
// (Seller Snap min_markup_on_cost 5.74). ROI here is Seller Snap's own
// definition: profit / cost (cost without the additional cost), which is
// what its ROI column shows.
//
// Zach's rules (2026-09-30):
//   - the suggestion takes the Buy Box: the highest price ending in 7 cents
//     (.07, .17 ... .97) that is strictly below the Buy Box;
//   - it may go down to break-even, never a loss - if the .x7 price loses
//     money the suggestion is "Don't change";
//   - ROI and margin at the suggested price are always shown.

const TREND_DEAD_BAND = 0.15;

const cents = (v) => Math.round(Number(v) * 100);
const round2 = (v) => Math.round(v * 100) / 100;
const numOr = (v, d = null) => {
  if (v == null || v === "") return d;
  const n = typeof v === "number" ? v : Number(String(v).replace(/[$,%\s]/g, ""));
  return Number.isFinite(n) ? n : d;
};

// Amazon's referral fee as Seller Snap models it.
//   type "step": the reduced % on the WHOLE price at or under the threshold
//                (Amazon's $10 rule), the regular % above it.
//   type "portion above threshold": regular % up to the threshold, reduced %
//                on the part above it.
// Never below the minimum fee.
function referralFee(price, fees = {}) {
  const p = Number(price);
  const regular = numOr(fees.regularPerc, 15);
  const reduced = numOr(fees.reducedPerc, null);
  const threshold = numOr(fees.reducedThreshold, null);
  const type = String(fees.reducedType || "").toLowerCase();
  let fee;
  if (reduced != null && threshold != null && type === "step") {
    fee = p * ((p <= threshold ? reduced : regular) / 100);
  } else if (reduced != null && threshold != null && type.indexOf("portion") === 0) {
    fee = p <= threshold ? p * (regular / 100) : threshold * (regular / 100) + (p - threshold) * (reduced / 100);
  } else {
    fee = p * (regular / 100);
  }
  const minFee = numOr(fees.minFee, 0) || 0;
  return Math.max(fee, minFee);
}

// FBA fee: the first tier whose "up" is at or above the price (null = no top).
// No tiers -> the one fee Seller Snap reported for the current price.
function fbaFee(price, fees = {}) {
  const tiers = Array.isArray(fees.fbaTiers) ? fees.fbaTiers : [];
  for (const t of tiers) {
    if (!t) continue;
    const up = t.up == null ? null : Number(t.up);
    if (up == null || Number(price) <= up) return numOr(t.value, 0);
  }
  return numOr(fees.fbaFee, 0) || 0;
}

// { profit, margin, roi } at a price, or null when cost is unknown.
function profitAt(price, row) {
  const p = numOr(price);
  const cost = numOr(row && row.cost);
  if (p == null || p <= 0 || cost == null) return null;
  const addl = numOr(row.additionalCost, 0) || 0;
  const fees = row.fees || {};
  const profit = p - referralFee(p, fees) - fbaFee(p, fees) - cost - addl;
  return {
    price: round2(p),
    profit: round2(profit),
    margin: round2((profit / p) * 100),
    roi: cost > 0 ? round2((profit / cost) * 100) : null,
  };
}

// The lowest price (to the cent) that does not lose money, searched up to
// the ceiling. null = none found under it.
function breakEven(row, ceiling = 1000) {
  const top = cents(ceiling);
  for (let c = 1; c <= top; c++) {
    const r = profitAt(c / 100, row);
    if (!r) return null;
    if (r.profit >= 0) return c / 100;
  }
  return null;
}

// The highest price ending in 7 cents that is strictly below the Buy Box.
function highestSevenBelow(bb) {
  const b = cents(bb);
  if (!Number.isFinite(b) || b <= 7) return null;
  const top = b - 1;
  const c = top - ((((top - 7) % 10) + 10) % 10);
  return c > 0 ? c / 100 : null;
}

// Shopper's suggestion for a row: { price, profit, margin, roi } or
// { price: null, reason, breakEven }.
function suggestPrice(row) {
  const bb = numOr(row && row.bb);
  if (bb == null || bb <= 0) return { price: null, reason: "No Buy Box price right now." };
  const s = highestSevenBelow(bb);
  if (s == null) return { price: null, reason: "The Buy Box is too low to price under." };
  const at = profitAt(s, row);
  if (!at) return { price: null, reason: "Seller Snap has no cost for this listing." };
  if (at.profit < 0) {
    const be = breakEven(row, Math.max(bb, numOr(row.min, bb)) + 50);
    return {
      price: null,
      breakEven: be,
      reason: `Can't beat the Buy Box ($${bb.toFixed(2)}) without a loss - break-even is ${be == null ? "unknown" : "$" + be.toFixed(2)}.`,
    };
  }
  return at;
}

// Speeding up / slowing down: this 7 days' velocity against the 7 before.
function velocityTrend(now, before) {
  const a = numOr(now);
  const b = numOr(before);
  if (a == null && b == null) return { dir: "none", label: "no sales data" };
  if (b == null || b === 0) {
    if (a == null || a === 0) return { dir: "flat", label: "no sales either week" };
    return { dir: "up", label: "new sales this week" };
  }
  const change = ((a || 0) - b) / b;
  const pct = Math.round(change * 100);
  if (change > TREND_DEAD_BAND) return { dir: "up", label: `speeding up (+${pct}%)`, pct };
  if (change < -TREND_DEAD_BAND) return { dir: "down", label: `slowing down (${pct}%)`, pct };
  return { dir: "flat", label: `steady (${pct >= 0 ? "+" : ""}${pct}%)`, pct };
}

// A price Zach typed: a positive number with at most two decimals.
function parsePrice(text) {
  const t = String(text == null ? "" : text).trim().replace(/^\$/, "");
  if (!/^\d+(\.\d{1,2})?$/.test(t)) return null;
  const n = Number(t);
  return n > 0 ? n : null;
}
__m["sellersnap-price.js"] = { TREND_DEAD_BAND, referralFee, fbaFee, profitAt, breakEven, highestSevenBelow, suggestPrice, velocityTrend, parsePrice };
})();
// ---- lib/keepa-chart-svg.js ----
(function () {
"use strict";
// Shopper (v2.0.2, B-746): draws the three small Keepa panels on a Below Min
// card - Buy Box price / sales rank + monthly sold / new offer count - from
// lib/keepa-charts.js compactChart(). Import-free and DOM-agnostic (takes
// `doc`), so the phone runs this same file (remote/belowmin-lib.js bundle).
// Colours are classes (kc-*), set with --s-* tokens in each stylesheet.
//
// v2.0.4 (B-758): interactive. Keepa's own chart cannot be framed (MEASURED
// 2026-09-30: keepa.com answers with frame-ancestors = Keepa's extension,
// keepa.com and amazon.* only - Shopper's pages and the phone are refused),
// so these panels became the interactive ones: range buttons (30 days,
// 90 days, 6 months, 1 year - up to what was bought; a year since v2.0.4),
// and a crosshair - hover (laptop) or touch-and-drag (phone) shows the date
// and every panel's value at that moment. The chosen range is remembered per
// device (localStorage, best effort).
const NS = "http://www.w3.org/2000/svg";
const KC_W = 320;
const KC_PAD_L = 38;
const KC_PAD_R = 38;
const KC_PANELS = [
  { key: "bb", title: "Buy Box", h: 64 },
  { key: "rank", title: "Sales rank · monthly sold", h: 64 },
  { key: "offers", title: "Offers", h: 48 },
];
const KC_RANGES = [
  { days: 30, label: "30d" },
  { days: 90, label: "90d" },
  { days: 180, label: "6m" },
  { days: 365, label: "1y" },
];
const KC_DEFAULT_RANGE = 90;
const RANGE_KEY = "shopperKeepaRange";

function el(doc, tag, attrs = {}, text) {
  const n = doc.createElementNS(NS, tag);
  for (const [k, v] of Object.entries(attrs)) n.setAttribute(k, String(v));
  if (text != null) n.textContent = String(text);
  return n;
}

// Segments of a step series that show inside [from, days].
function visiblePoints(points, from, days) {
  const pts = points || [];
  return pts.filter((p, i) => {
    const tNext = i + 1 < pts.length ? pts[i + 1][0] : days;
    return tNext > from && p[0] <= days;
  });
}

function extent(points) {
  const vals = (points || []).map((p) => p[1]).filter((v) => v != null && Number.isFinite(v));
  if (!vals.length) return null;
  let lo = Math.min(...vals);
  let hi = Math.max(...vals);
  if (lo === hi) { lo = lo * 0.95; hi = hi * 1.05 || 1; }
  return [lo, hi];
}

// B-800 (v2.0.10): the drawn range runs a little past the data (8% of the
// span each side) so a line never sits on the frame; never below 0.
const KC_Y_PAD = 0.08;
function padExtent(ext, frac = KC_Y_PAD) {
  if (!ext) return null;
  const span = ext[1] - ext[0] || Math.abs(ext[1]) * 0.1 || 1;
  return [Math.max(0, ext[0] - span * frac), ext[1] + span * frac];
}

// A step line (Keepa series hold their value until the next point), with
// gaps where the value is null, held to the right edge. `from` (days) is the
// left edge of the window; a value set before it is drawn from the edge.
function stepPath(points, days, x0, x1, y0, y1, ext, from = 0) {
  if (!points || !points.length || !ext) return "";
  const span = days - from || 1;
  const X = (d) => x0 + ((Math.max(from, Math.min(days, d)) - from) / span) * (x1 - x0);
  const Y = (v) => y1 - ((v - ext[0]) / (ext[1] - ext[0])) * (y1 - y0);
  let d = "";
  let open = false;
  for (let i = 0; i < points.length; i++) {
    const [t, v] = points[i];
    const tNext = i + 1 < points.length ? points[i + 1][0] : days;
    if (v == null || tNext <= from) { open = false; continue; }
    const x = X(t).toFixed(1), y = Y(v).toFixed(1), xe = X(tNext).toFixed(1);
    d += open ? `V${y}H${xe}` : `M${x},${y}H${xe}`;
    open = true;
  }
  return d;
}

// The value in force at `day` (a step series), or null.
function valueAt(points, day) {
  let v = null;
  for (const [t, val] of points || []) {
    if (t > day) break;
    v = val;
  }
  return v;
}

const fmtMoney = (v) => "$" + (v >= 100 ? v.toFixed(0) : v.toFixed(2));
const fmtK = (v) => (v >= 10000 ? Math.round(v / 1000) + "k" : String(Math.round(v)));
const fmtInt = (v) => String(Math.round(v)).replace(/\B(?=(\d{3})+(?!\d))/g, ",");
const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
const fmtDay = (ms) => { const d = new Date(ms); return `${MONTHS[d.getUTCMonth()]} ${d.getUTCDate()}`; };

// The ranges a chart can show: every standard one up to what was bought,
// plus the whole span when it is not one of them.
function rangesFor(chart) {
  const days = (chart && chart.days) || KC_DEFAULT_RANGE;
  const list = KC_RANGES.filter((r) => r.days <= days);
  if (!list.some((r) => r.days === days)) list.push({ days, label: `${days}d` });
  return list;
}

function pickRange(chart, wanted) {
  const list = rangesFor(chart);
  const w = Number(wanted);
  if (list.some((r) => r.days === w)) return w;
  return list.some((r) => r.days === KC_DEFAULT_RANGE) ? KC_DEFAULT_RANGE : list[list.length - 1].days;
}

// "Sep 12 · Buy Box $16.37 · Rank #12,345 · Sold 300/mo · Offers 7"
function readoutText(chart, day) {
  const bits = [fmtDay(chart.startMs + day * 86400000)];
  const bb = valueAt(chart.bb, day);
  const rank = valueAt(chart.rank, day);
  const sold = valueAt(chart.sold, day);
  const offers = valueAt(chart.offers, day);
  bits.push(bb == null ? "Buy Box -" : `Buy Box ${fmtMoney(bb)}`);
  if (rank != null) bits.push(`Rank #${fmtInt(rank)}`);
  if (sold != null) bits.push(`Sold ${fmtInt(sold)}/mo`);
  if (offers != null) bits.push(`Offers ${fmtInt(offers)}`);
  return bits.join(" · ");
}

function readRange() {
  try { return typeof localStorage !== "undefined" ? Number(localStorage.getItem(RANGE_KEY)) || null : null; } catch { return null; }
}
function saveRange(days) {
  try { if (typeof localStorage !== "undefined") localStorage.setItem(RANGE_KEY, String(days)); } catch { /* per-device nicety */ }
}
const on = (n, type, fn) => { if (n && typeof n.addEventListener === "function") n.addEventListener(type, fn); };

// The three panels for one window, plus a cursor line in each.
function drawPanels(doc, chart, from) {
  const days = chart.days || KC_DEFAULT_RANGE;
  const x0 = KC_PAD_L, x1 = KC_W - KC_PAD_R;
  const svgs = [];
  KC_PANELS.forEach((panel, idx) => {
    const last = idx === KC_PANELS.length - 1;
    const H = panel.h + (last ? 14 : 0);
    const svg = el(doc, "svg", { viewBox: `0 0 ${KC_W} ${H}`, class: "kc-svg", role: "img", "aria-label": panel.title, preserveAspectRatio: "xMidYMid meet" });
    const y0 = 12, y1 = panel.h - 4;
    svg.append(el(doc, "text", { x: x0, y: 9, class: "kc-title" }, panel.title));
    svg.append(el(doc, "rect", { x: x0, y: y0, width: x1 - x0, height: y1 - y0, class: "kc-frame" }));
    const vis = (pts) => visiblePoints(pts, from, days);
    // B-800: lines are drawn on the padded range; the axis labels still name
    // the real high and low, placed level with them.
    const addLine = (pts, cls, ext) => { const d = stepPath(pts, days, x0, x1, y0, y1, padExtent(ext), from); if (d) svg.append(el(doc, "path", { d, class: cls })); };
    const axis = (ext, side, fmt, cls) => {
      if (!ext) return;
      const pe = padExtent(ext);
      const yOf = (v) => y1 - ((v - pe[0]) / (pe[1] - pe[0])) * (y1 - y0);
      const x = side === "l" ? x0 - 3 : x1 + 3;
      const anchor = side === "l" ? "end" : "start";
      const yHi = Math.max(y0 + 7, Math.min(y1, yOf(ext[1]) + 3.5));
      const yLo = Math.max(yHi + 8, Math.min(y1, yOf(ext[0]) + 3.5));
      svg.append(el(doc, "text", { x, y: +yHi.toFixed(1), "text-anchor": anchor, class: "kc-axis " + cls }, fmt(ext[1])));
      svg.append(el(doc, "text", { x, y: +yLo.toFixed(1), "text-anchor": anchor, class: "kc-axis " + cls }, fmt(ext[0])));
    };
    if (panel.key === "bb") {
      const e = extent(vis(chart.bb));
      addLine(chart.bb, "kc-line kc-bb", e);
      axis(e, "l", fmtMoney, "kc-bb-t");
      if (!e) svg.append(el(doc, "text", { x: (x0 + x1) / 2, y: (y0 + y1) / 2 + 3, "text-anchor": "middle", class: "kc-axis" }, "no Buy Box history"));
    } else if (panel.key === "rank") {
      const er = extent(vis(chart.rank));
      const es = extent(vis(chart.sold).concat([[from, 0]]));
      addLine(chart.rank, "kc-line kc-rank", er);
      addLine(chart.sold, "kc-line kc-sold", es);
      axis(es, "l", fmtK, "kc-sold-t");
      axis(er, "r", (v) => "#" + fmtK(v), "kc-rank-t");
    } else {
      const e = extent(vis(chart.offers).concat([[from, 0]]));
      addLine(chart.offers, "kc-line kc-offers", e);
      axis(e, "l", fmtK, "kc-offers-t");
      const startMs = chart.startMs + from * 86400000, endMs = chart.endMs;
      [[x0, startMs, "start"], [(x0 + x1) / 2, (startMs + endMs) / 2, "middle"], [x1, endMs, "end"]].forEach(([x, ms, a]) => {
        svg.append(el(doc, "text", { x, y: H - 2, "text-anchor": a, class: "kc-axis" }, fmtDay(ms)));
      });
    }
    const cursor = el(doc, "line", { x1: x0, x2: x0, y1: y0, y2: y1, class: "kc-cursor", visibility: "hidden" });
    svg.append(cursor);
    svgs.push({ svg, cursor });
  });
  return svgs;
}

// Returns a <div class="kc"> holding the range buttons, the readout, the
// three panels and a note - or a note when there is no chart yet.
function drawKeepaCharts(doc, chart, { asOf = null, range = null } = {}) {
  const wrap = doc.createElement("div");
  wrap.className = "kc";
  if (!chart) {
    const p = doc.createElement("div");
    p.className = "kc-empty";
    p.textContent = "Keepa charts not loaded yet - they are bought a few at a time (3 Keepa tokens each) and kept a day.";
    wrap.append(p);
    return wrap;
  }
  const days = chart.days || KC_DEFAULT_RANGE;
  let current = pickRange(chart, range != null ? range : readRange());

  const bar = doc.createElement("div");
  bar.className = "kc-ranges";
  const readout = doc.createElement("div");
  readout.className = "kc-readout";
  const panels = doc.createElement("div");
  panels.className = "kc-panels";
  const note = doc.createElement("div");
  note.className = "kc-note";
  const buttons = [];

  const render = () => {
    const from = Math.max(0, days - current);
    panels.textContent = "";
    const svgs = drawPanels(doc, chart, from);
    for (const { svg } of svgs) panels.append(svg);
    readout.textContent = "Point at a chart to read its values";
    note.textContent = `Keepa, last ${current} days${asOf ? ` · as of ${fmtDay(asOf)}` : ""}`;
    for (const b of buttons) b.node.className = "kc-range" + (b.days === current ? " kc-range-on" : "");
    const x0 = KC_PAD_L, x1 = KC_W - KC_PAD_R;
    const show = (evt, svg) => {
      if (!svg || typeof svg.getBoundingClientRect !== "function") return;
      const rect = svg.getBoundingClientRect();
      if (!rect || !rect.width) return;
      const xSvg = ((evt.clientX - rect.left) / rect.width) * KC_W;
      const xc = Math.max(x0, Math.min(x1, xSvg));
      const day = from + ((xc - x0) / (x1 - x0)) * (days - from);
      for (const s of svgs) {
        s.cursor.setAttribute("x1", xc.toFixed(1));
        s.cursor.setAttribute("x2", xc.toFixed(1));
        s.cursor.setAttribute("visibility", "visible");
      }
      readout.textContent = readoutText(chart, day);
    };
    const hide = () => { for (const s of svgs) s.cursor.setAttribute("visibility", "hidden"); };
    for (const { svg } of svgs) {
      on(svg, "pointermove", (e) => show(e, svg));
      on(svg, "pointerdown", (e) => show(e, svg));
      on(svg, "pointerleave", hide);
    }
  };

  for (const r of rangesFor(chart)) {
    const b = doc.createElement("button");
    b.type = "button";
    b.textContent = r.label;
    if (typeof b.setAttribute === "function") b.setAttribute("aria-label", `Show the last ${r.days} days`);
    on(b, "click", () => { current = r.days; saveRange(current); render(); });
    buttons.push({ node: b, days: r.days });
    bar.append(b);
  }
  render();
  wrap.append(bar, readout, panels, note);
  return wrap;
}
__m["keepa-chart-svg.js"] = { KC_W, KC_PAD_L, KC_PAD_R, KC_PANELS, KC_RANGES, KC_DEFAULT_RANGE, visiblePoints, extent, KC_Y_PAD, padExtent, stepPath, valueAt, rangesFor, pickRange, readoutText, drawKeepaCharts };
})();
// ---- lib/sold-per-day.js ----
(function () {
"use strict";
// B-813 (v2.0.16): the Below Min card's "Sold per day" column chart - the
// last 30 days, units or dollars. Data = the Amazon orders report the Buy
// Score already keeps (shopperAspDaily, lib/asp-daily-refresh.js: per ASIN,
// per America/Chicago day, {units, sales}, 30 days kept). An ASIN with no
// sale on a day has no entry, so inside the store's covered days a missing
// day is 0; a day outside them (before the first report, after the last
// one) is "no data" - drawn as a faint stub, never as a real zero.
// Pure series builder + a DOM/SVG drawer (doc passed in; no chrome APIs).

const SOLD_DAYS = 30;
const SOLD_VIEW_KEY = "shopperBelowMinSoldView"; // "units" | "dollars"

function addDays(dayIso, n) {
  const t = Date.parse(`${dayIso}T12:00:00Z`);
  if (!Number.isFinite(t)) return null;
  return new Date(t + n * 86400000).toISOString().slice(0, 10);
}

// days = {"YYYY-MM-DD": {units, sales}} for one ASIN (or null/undefined);
// cover = {firstDay, lastDay} of the whole store; endDay = the chart's last
// day (today in Chicago). -> [{day, units, sales, known}] oldest first.
function soldSeries(days, cover, endDay, n = SOLD_DAYS) {
  const out = [];
  if (!endDay || !/^\d{4}-\d{2}-\d{2}$/.test(endDay)) return out;
  const first = cover && cover.firstDay ? cover.firstDay : null;
  const last = cover && cover.lastDay ? cover.lastDay : null;
  for (let i = n - 1; i >= 0; i--) {
    const day = addDays(endDay, -i);
    const known = !!(first && last && day >= first && day <= last);
    const v = days && days[day];
    out.push({
      day,
      known,
      units: known ? Math.max(0, Number(v && v.units) || 0) : 0,
      sales: known ? Math.max(0, Math.round((Number(v && v.sales) || 0) * 100) / 100) : 0,
    });
  }
  return out;
}

// Totals over the known days. -> {units, sales, knownDays}
function soldTotals(series) {
  let units = 0, sales = 0, knownDays = 0;
  for (const s of series || []) {
    if (!s.known) continue;
    knownDays++;
    units += s.units;
    sales += s.sales;
  }
  return { units, sales: Math.round(sales * 100) / 100, knownDays };
}

// The whole store's covered range: earliest and latest day any ASIN has.
function soldCover(store) {
  let firstDay = null, lastDay = null;
  const by = store && store.byAsin ? store.byAsin : {};
  for (const days of Object.values(by)) {
    for (const d of Object.keys(days || {})) {
      if (!firstDay || d < firstDay) firstDay = d;
      if (!lastDay || d > lastDay) lastDay = d;
    }
  }
  return { firstDay, lastDay };
}

// B-821 (v2.0.17): what a card needs, for the laptop page and the phone's
// Min tab alike: the given ASINs' days, the whole store's covered range and
// today. store = readAspStore()'s value; todayIso = Chicago today.
function soldForAsins(store, asins, todayIso) {
  const by = store && store.byAsin ? store.byAsin : {};
  const byAsin = {};
  for (const a of asins || []) {
    const k = String(a || "").trim().toUpperCase();
    if (k && by[k]) byAsin[k] = by[k];
  }
  return { byAsin, cover: soldCover(store), today: todayIso || null, updatedAt: (store && store.updatedAt) || null };
}

const fmtMoney = (v) => "$" + (Math.round(v) >= 1000 ? Math.round(v).toLocaleString("en-US") : (Math.round(v * 100) / 100).toFixed(v >= 100 ? 0 : 2));
const fmtVal = (mode, v) => (mode === "dollars" ? fmtMoney(v) : String(v));
const shortDay = (d) => `${Number(d.slice(5, 7))}/${Number(d.slice(8, 10))}`;

// Draw the chart into a new element and return it. mode = "units" | "dollars".
function drawSoldChart(doc, series, mode = "units") {
  const NS = "http://www.w3.org/2000/svg";
  const wrap = doc.createElement("div");
  wrap.className = "sold-chart";
  const list = Array.isArray(series) ? series : [];
  const key = mode === "dollars" ? "sales" : "units";
  const anyKnown = list.some((s) => s.known);
  if (!list.length || !anyKnown) {
    const empty = doc.createElement("div");
    empty.className = "sold-empty";
    empty.textContent = "No Amazon sales report on file yet - it is read once a day (Buy Score sale-price trend).";
    wrap.append(empty);
    return wrap;
  }
  const max = Math.max(0, ...list.map((s) => s[key]));
  const W = 300, H = 120, top = 14, bottom = 16, left = 2, right = 2;
  const plotH = H - top - bottom;
  const step = (W - left - right) / list.length;
  const barW = Math.max(2, step * 0.72);
  const svg = doc.createElementNS(NS, "svg");
  svg.setAttribute("viewBox", `0 0 ${W} ${H}`);
  svg.setAttribute("class", "sold-svg");
  svg.setAttribute("role", "img");
  svg.setAttribute("preserveAspectRatio", "none");
  const t = soldTotals(list);
  svg.setAttribute("aria-label", `Sold per day, last ${list.length} days: ${mode === "dollars" ? fmtMoney(t.sales) : t.units + " units"} in total`);
  const base = doc.createElementNS(NS, "line");
  base.setAttribute("x1", "0"); base.setAttribute("x2", String(W));
  base.setAttribute("y1", String(H - bottom)); base.setAttribute("y2", String(H - bottom));
  base.setAttribute("class", "sold-base");
  svg.append(base);
  list.forEach((s, i) => {
    const x = left + i * step + (step - barW) / 2;
    const r = doc.createElementNS(NS, "rect");
    let h;
    if (!s.known) { h = 2; r.setAttribute("class", "sold-bar sold-nodata"); }
    else if (s[key] <= 0) { h = 1; r.setAttribute("class", "sold-bar sold-zero"); }
    else { h = max > 0 ? Math.max(2, (s[key] / max) * plotH) : 0; r.setAttribute("class", "sold-bar"); }
    r.setAttribute("x", x.toFixed(2));
    r.setAttribute("y", (H - bottom - h).toFixed(2));
    r.setAttribute("width", barW.toFixed(2));
    r.setAttribute("height", h.toFixed(2));
    r.setAttribute("data-day", s.day);
    const tip = doc.createElementNS(NS, "title");
    tip.textContent = s.known ? `${shortDay(s.day)}: ${s.units} unit${s.units === 1 ? "" : "s"} · ${fmtMoney(s.sales)}` : `${shortDay(s.day)}: no data`;
    r.append(tip);
    svg.append(r);
  });
  wrap.append(svg);
  // Axis: first day, middle, last day, and the tallest bar's value.
  const axis = doc.createElement("div");
  axis.className = "sold-axis";
  for (const i of [0, Math.floor(list.length / 2), list.length - 1]) {
    const sp = doc.createElement("span");
    sp.textContent = shortDay(list[i].day);
    axis.append(sp);
  }
  wrap.append(axis);
  const foot = doc.createElement("div");
  foot.className = "sold-foot";
  foot.textContent = `Total ${mode === "dollars" ? fmtMoney(t.sales) : t.units + " units"} · best day ${fmtVal(mode, max)}` + (t.knownDays < list.length ? ` · ${list.length - t.knownDays} days no data` : "");
  wrap.append(foot);
  return wrap;
}
__m["sold-per-day.js"] = { SOLD_DAYS, SOLD_VIEW_KEY, soldSeries, soldTotals, soldCover, soldForAsins, drawSoldChart };
})();
root.ShopperPrice = Object.freeze(Object.assign({}, ...Object.values(__m)));
})(self);
