// remote/belowmin-lib.js - GENERATED by test/_belowmin-bundle.mjs (B-741, v2.01). DO NOT EDIT.
// The phone's copy of lib/sellersnap-price.js, wrapped unchanged.
// Edit lib/, then: node test/_belowmin-bundle.mjs --write
(function (root) {
const __m = {};
// ---- lib/sellersnap-price.js ----
(function () {
"use strict";
// Shopper 2 (v2.01, B-741): profit at a price, the way Seller Snap works it
// out, and the price Shopper suggests when the Buy Box is under Zach's min.
// PURE - no chrome, no fetch, no I/O.
//
// Measured 2026-09-30 against Seller Snap's own numbers (scope doc
// claude/b741-bb-below-min-scope-2026-09-30.md section 3): B0C1HPL15D at its
// $16.37 min -> profit $0.51, margin 3.14% (Seller Snap 3.15%), ROI 5.74%
// (Seller Snap min_markup_on_cost 5.74). ROI here is Seller Snap's own
// definition: profit / cost (cost without the additional cost), which is
// what its ROI column shows.
//
// Zach's rules (2026-09-30):
//   - the suggestion takes the Buy Box: the highest price ending in 7 cents
//     (.07, .17 ... .97) that is strictly below the Buy Box;
//   - it may go down to break-even, never a loss - if the .x7 price loses
//     money the suggestion is "Don't change";
//   - ROI and margin at the suggested price are always shown.

const TREND_DEAD_BAND = 0.15;

const cents = (v) => Math.round(Number(v) * 100);
const round2 = (v) => Math.round(v * 100) / 100;
const numOr = (v, d = null) => {
  if (v == null || v === "") return d;
  const n = typeof v === "number" ? v : Number(String(v).replace(/[$,%\s]/g, ""));
  return Number.isFinite(n) ? n : d;
};

// Amazon's referral fee as Seller Snap models it.
//   type "step": the reduced % on the WHOLE price at or under the threshold
//                (Amazon's $10 rule), the regular % above it.
//   type "portion above threshold": regular % up to the threshold, reduced %
//                on the part above it.
// Never below the minimum fee.
function referralFee(price, fees = {}) {
  const p = Number(price);
  const regular = numOr(fees.regularPerc, 15);
  const reduced = numOr(fees.reducedPerc, null);
  const threshold = numOr(fees.reducedThreshold, null);
  const type = String(fees.reducedType || "").toLowerCase();
  let fee;
  if (reduced != null && threshold != null && type === "step") {
    fee = p * ((p <= threshold ? reduced : regular) / 100);
  } else if (reduced != null && threshold != null && type.indexOf("portion") === 0) {
    fee = p <= threshold ? p * (regular / 100) : threshold * (regular / 100) + (p - threshold) * (reduced / 100);
  } else {
    fee = p * (regular / 100);
  }
  const minFee = numOr(fees.minFee, 0) || 0;
  return Math.max(fee, minFee);
}

// FBA fee: the first tier whose "up" is at or above the price (null = no top).
// No tiers -> the one fee Seller Snap reported for the current price.
function fbaFee(price, fees = {}) {
  const tiers = Array.isArray(fees.fbaTiers) ? fees.fbaTiers : [];
  for (const t of tiers) {
    if (!t) continue;
    const up = t.up == null ? null : Number(t.up);
    if (up == null || Number(price) <= up) return numOr(t.value, 0);
  }
  return numOr(fees.fbaFee, 0) || 0;
}

// { profit, margin, roi } at a price, or null when cost is unknown.
function profitAt(price, row) {
  const p = numOr(price);
  const cost = numOr(row && row.cost);
  if (p == null || p <= 0 || cost == null) return null;
  const addl = numOr(row.additionalCost, 0) || 0;
  const fees = row.fees || {};
  const profit = p - referralFee(p, fees) - fbaFee(p, fees) - cost - addl;
  return {
    price: round2(p),
    profit: round2(profit),
    margin: round2((profit / p) * 100),
    roi: cost > 0 ? round2((profit / cost) * 100) : null,
  };
}

// The lowest price (to the cent) that does not lose money, searched up to
// the ceiling. null = none found under it.
function breakEven(row, ceiling = 1000) {
  const top = cents(ceiling);
  for (let c = 1; c <= top; c++) {
    const r = profitAt(c / 100, row);
    if (!r) return null;
    if (r.profit >= 0) return c / 100;
  }
  return null;
}

// The highest price ending in 7 cents that is strictly below the Buy Box.
function highestSevenBelow(bb) {
  const b = cents(bb);
  if (!Number.isFinite(b) || b <= 7) return null;
  const top = b - 1;
  const c = top - ((((top - 7) % 10) + 10) % 10);
  return c > 0 ? c / 100 : null;
}

// Shopper's suggestion for a row: { price, profit, margin, roi } or
// { price: null, reason, breakEven }.
function suggestPrice(row) {
  const bb = numOr(row && row.bb);
  if (bb == null || bb <= 0) return { price: null, reason: "No Buy Box price right now." };
  const s = highestSevenBelow(bb);
  if (s == null) return { price: null, reason: "The Buy Box is too low to price under." };
  const at = profitAt(s, row);
  if (!at) return { price: null, reason: "Seller Snap has no cost for this listing." };
  if (at.profit < 0) {
    const be = breakEven(row, Math.max(bb, numOr(row.min, bb)) + 50);
    return {
      price: null,
      breakEven: be,
      reason: `Can't beat the Buy Box ($${bb.toFixed(2)}) without a loss - break-even is ${be == null ? "unknown" : "$" + be.toFixed(2)}.`,
    };
  }
  return at;
}

// Speeding up / slowing down: this 7 days' velocity against the 7 before.
function velocityTrend(now, before) {
  const a = numOr(now);
  const b = numOr(before);
  if (a == null && b == null) return { dir: "none", label: "no sales data" };
  if (b == null || b === 0) {
    if (a == null || a === 0) return { dir: "flat", label: "no sales either week" };
    return { dir: "up", label: "new sales this week" };
  }
  const change = ((a || 0) - b) / b;
  const pct = Math.round(change * 100);
  if (change > TREND_DEAD_BAND) return { dir: "up", label: `speeding up (+${pct}%)`, pct };
  if (change < -TREND_DEAD_BAND) return { dir: "down", label: `slowing down (${pct}%)`, pct };
  return { dir: "flat", label: `steady (${pct >= 0 ? "+" : ""}${pct}%)`, pct };
}

// A price Zach typed: a positive number with at most two decimals.
function parsePrice(text) {
  const t = String(text == null ? "" : text).trim().replace(/^\$/, "");
  if (!/^\d+(\.\d{1,2})?$/.test(t)) return null;
  const n = Number(t);
  return n > 0 ? n : null;
}
__m["sellersnap-price.js"] = { TREND_DEAD_BAND, referralFee, fbaFee, profitAt, breakEven, highestSevenBelow, suggestPrice, velocityTrend, parsePrice };
})();
root.ShopperPrice = Object.freeze(__m["sellersnap-price.js"]);
})(self);
