// remote/cashflow-lib.js - GENERATED by test/_cashflow-bundle.mjs (B-765 v2.0.8). DO NOT EDIT.
// The phone's copy of lib/s-chart.js, wrapped unchanged.
// Edit lib/, then: node test/_cashflow-bundle.mjs --write
(function (root) {
const __m = {};
// ---- lib/s-chart.js ----
(function () {
"use strict";
// Shopper 2 (v2.00, B-732/B-731): ONE plain-SVG chart style (no library - an
// MV3 page cannot load a CDN). Colours come from CSS classes on the marks
// (.s-mark-1 ... .s-mark-5, .s-band, .s-bar) defined in lib/shopper-ui.css,
// so light and dark both work. Pure DOM; returns the <svg>.
const NS = "http://www.w3.org/2000/svg";
function el(name, attrs = {}, parent = null) {
  const n = document.createElementNS(NS, name);
  for (const [k, v] of Object.entries(attrs)) if (v != null) n.setAttribute(k, String(v));
  if (parent) parent.appendChild(n);
  return n;
}

function niceMax(v) {
  if (!(v > 0)) return 1;
  const p = Math.pow(10, Math.floor(Math.log10(v)));
  const m = v / p;
  const step = m <= 1 ? 1 : m <= 2 ? 2 : m <= 2.5 ? 2.5 : m <= 5 ? 5 : 10;
  return step * p;
}

function fmtMoneyShort(v) {
  const a = Math.abs(v);
  const s = a >= 1e6 ? (a / 1e6).toFixed(1) + "M" : a >= 1e4 ? Math.round(a / 1e3) + "k" : a >= 1e3 ? (a / 1e3).toFixed(1) + "k" : String(Math.round(a));
  return (v < 0 ? "-$" : "$") + s;
}

function shortDay(d) {
  const t = new Date(d + "T12:00:00Z");
  return t.toLocaleDateString("en-US", { month: "short", day: "numeric", timeZone: "UTC" });
}

// opts: { days: [YYYY-MM-DD], bars: [n|null], lines: [{ values, cls, label, dash }],
//   band: { low: [], high: [] }, ref: number (horizontal line), height, yFormat,
//   yMin (default 0), split: index where the forecast starts, title }
function drawChart(container, opts) {
  const W = Math.max(320, container.clientWidth || 900);
  const H = opts.height || 260;
  const pad = { l: 56, r: 12, t: 12, b: 28 };
  const n = opts.days.length;
  const all = [];
  (opts.bars || []).forEach((v) => v != null && all.push(v));
  (opts.lines || []).forEach((l) => l.values.forEach((v) => v != null && all.push(v)));
  if (opts.band) opts.band.high.forEach((v) => v != null && all.push(v));
  if (opts.ref != null) all.push(opts.ref);
  const hi = niceMax(Math.max(0, ...all));
  const lo = opts.yMin != null ? opts.yMin : Math.min(0, ...all);
  const x = (i) => pad.l + (n <= 1 ? 0 : (i / (n - 1)) * (W - pad.l - pad.r));
  const bw = Math.max(1, ((W - pad.l - pad.r) / Math.max(1, n)) * 0.72);
  const y = (v) => pad.t + (1 - (v - lo) / (hi - lo || 1)) * (H - pad.t - pad.b);
  const fmt = opts.yFormat || fmtMoneyShort;
  container.textContent = "";
  const svg = el("svg", { class: "s-chart", viewBox: `0 0 ${W} ${H}`, width: "100%", role: "img", "aria-label": opts.title || "chart" }, container);
  for (let k = 0; k <= 4; k++) {
    const v = lo + ((hi - lo) * k) / 4;
    el("line", { class: "grid", x1: pad.l, x2: W - pad.r, y1: y(v), y2: y(v) }, svg);
    const t = el("text", { class: "label", x: pad.l - 8, y: y(v) + 4, "text-anchor": "end" }, svg);
    t.textContent = fmt(v);
  }
  // v2.0.8 (B-765): about one date label per 64px, so a phone-width chart
  // does not print them on top of each other.
  const ticks = Math.min(8, n, Math.max(2, Math.floor((W - pad.l - pad.r) / 64)));
  for (let k = 0; k < ticks; k++) {
    const i = Math.round((k * (n - 1)) / Math.max(1, ticks - 1));
    const t = el("text", { class: "label", x: x(i), y: H - 8, "text-anchor": k === 0 ? "start" : k === ticks - 1 ? "end" : "middle" }, svg);
    t.textContent = shortDay(opts.days[i]);
  }
  if (opts.split != null && opts.split > 0 && opts.split < n) {
    el("rect", { class: "s-forecast-zone", x: x(opts.split), y: pad.t, width: W - pad.r - x(opts.split), height: H - pad.t - pad.b }, svg);
  }
  if (opts.band) {
    const pts = [];
    opts.band.high.forEach((v, i) => v != null && pts.push(`${x(i)},${y(v)}`));
    for (let i = opts.band.low.length - 1; i >= 0; i--) if (opts.band.low[i] != null) pts.push(`${x(i)},${y(opts.band.low[i])}`);
    if (pts.length > 2) el("polygon", { class: "s-band", points: pts.join(" ") }, svg);
  }
  (opts.bars || []).forEach((v, i) => {
    if (v == null) return;
    const top = y(Math.max(0, v)), base = y(Math.min(0, v) || 0);
    el("rect", { class: "s-bar" + (v < 0 ? " neg" : ""), x: x(i) - bw / 2, y: Math.min(top, base), width: bw, height: Math.max(0.5, Math.abs(base - top)) }, svg);
  });
  if (opts.ref != null) el("line", { class: "s-ref", x1: pad.l, x2: W - pad.r, y1: y(opts.ref), y2: y(opts.ref) }, svg);
  for (const l of opts.lines || []) {
    let d = "";
    let pen = false;
    l.values.forEach((v, i) => {
      if (v == null) { pen = false; return; }
      d += `${pen ? "L" : "M"}${x(i).toFixed(1)},${y(v).toFixed(1)}`;
      pen = true;
    });
    if (d) el("path", { class: `s-line ${l.cls || "s-mark-1"}${l.dash ? " dash" : ""}`, d }, svg);
  }
  // Hover read-out: nearest day.
  const tip = el("g", { class: "s-tip", visibility: "hidden" }, svg);
  const vline = el("line", { class: "s-tip-line", y1: pad.t, y2: H - pad.b }, tip);
  const box = el("rect", { class: "s-tip-box", rx: 6, height: 20 + 16 * ((opts.lines || []).length + (opts.bars ? 1 : 0)) }, tip);
  const text = el("text", { class: "s-tip-text" }, tip);
  svg.addEventListener("mousemove", (ev) => {
    const r = svg.getBoundingClientRect();
    const px = ((ev.clientX - r.left) / r.width) * W;
    const i = Math.max(0, Math.min(n - 1, Math.round(((px - pad.l) / (W - pad.l - pad.r)) * (n - 1))));
    vline.setAttribute("x1", x(i)); vline.setAttribute("x2", x(i));
    text.textContent = "";
    const rows = [shortDay(opts.days[i])];
    if (opts.bars) rows.push(`${opts.barLabel || "Day"}: ${opts.bars[i] == null ? "-" : fmt(opts.bars[i])}`);
    for (const l of opts.lines || []) rows.push(`${l.label}: ${l.values[i] == null ? "-" : fmt(l.values[i])}`);
    const bx = x(i) + 10 + 190 > W ? x(i) - 200 : x(i) + 10;
    rows.forEach((s, k) => { const t = el("tspan", { x: bx + 8, y: pad.t + 16 + k * 16 }, text); t.textContent = s; });
    box.setAttribute("x", bx); box.setAttribute("y", pad.t); box.setAttribute("width", 190);
    tip.setAttribute("visibility", "visible");
  });
  svg.addEventListener("mouseleave", () => tip.setAttribute("visibility", "hidden"));
  return svg;
}

// Stacked areas (e.g. Available / Inbound / FC transfer at cost).
function drawStacked(container, { days, series, height = 220, yFormat }) {
  const W = Math.max(320, container.clientWidth || 900);
  const H = height;
  const pad = { l: 56, r: 12, t: 12, b: 28 };
  const n = days.length;
  const tops = days.map((_, i) => series.reduce((s, se) => s + (Number(se.values[i]) || 0), 0));
  const hi = niceMax(Math.max(1, ...tops));
  const x = (i) => pad.l + (n <= 1 ? (W - pad.l - pad.r) / 2 : (i / (n - 1)) * (W - pad.l - pad.r));
  const y = (v) => pad.t + (1 - v / hi) * (H - pad.t - pad.b);
  const fmt = yFormat || fmtMoneyShort;
  container.textContent = "";
  const svg = el("svg", { class: "s-chart", viewBox: `0 0 ${W} ${H}`, width: "100%", role: "img" }, container);
  for (let k = 0; k <= 4; k++) {
    const v = (hi * k) / 4;
    el("line", { class: "grid", x1: pad.l, x2: W - pad.r, y1: y(v), y2: y(v) }, svg);
    const t = el("text", { class: "label", x: pad.l - 8, y: y(v) + 4, "text-anchor": "end" }, svg);
    t.textContent = fmt(v);
  }
  const ticks = Math.min(6, n, Math.max(2, Math.floor((W - pad.l - pad.r) / 64)));
  for (let k = 0; k < ticks; k++) {
    const i = Math.round((k * (n - 1)) / Math.max(1, ticks - 1));
    const t = el("text", { class: "label", x: x(i), y: H - 8, "text-anchor": "middle" }, svg);
    t.textContent = shortDay(days[i]);
  }
  const base = days.map(() => 0);
  series.forEach((se) => {
    const upper = base.map((b, i) => b + (Number(se.values[i]) || 0));
    const pts = [...upper.map((v, i) => `${x(i)},${y(v)}`), ...base.map((v, i) => `${x(i)},${y(v)}`).reverse()];
    el("polygon", { class: `s-area ${se.cls}`, points: pts.join(" ") }, svg);
    upper.forEach((v, i) => (base[i] = v));
  });
  return svg;
}
__m["s-chart.js"] = { niceMax, fmtMoneyShort, drawChart, drawStacked };
})();
root.ShopperChart = Object.freeze(Object.assign({}, ...Object.values(__m)));
})(self);
