// remote/catalog-lib.js - GENERATED by test/_catalog-bundle.mjs (B-1023 v2.0.49). DO NOT EDIT.
// The phone's copy of lib/table-sort.js, lib/catalog-view.js, wrapped unchanged.
// Edit lib/, then: node test/_catalog-bundle.mjs --write
(function (root) {
const __m = {};
// ---- lib/table-sort.js ----
(function () {
"use strict";
// Shopper - one table sort, for every table on the pipeline page.
//
// P-328 (v3.99). ⚠⚠⚠ A SECOND IMPLEMENTATION OF "PUT THESE ROWS IN ORDER"
// IS THE MISTAKE THIS PROJECT HAS PAID FOR FIVE TIMES (P-147), and a sort
// is exactly the kind of thing that grows a private copy per table because
// each table's COLUMNS differ. The columns differ; the ordering does not.
// Each caller supplies a value accessor and nothing else.
//
// ⚠⚠ IMPORT-FREE LEAF ON PURPOSE: it lives here rather than inside
// pipeline/pipeline.js so it can be EXECUTED by a test. The decision below
// about blanks is worth more than a comment claiming it was made.

// ⚠⚠⚠ A BLANK IS NOT A ZERO. This is the load-bearing line in the file.
//
// A blank "Vs last count" means "between counts, on purpose - you cannot
// know what is lost between them". A blank RP figure means Replen Pulse
// does not carry that product at all, which is the system staying silent,
// never the system asserting zero. Sorting either as 0 would quietly tell
// Zach something false about a row he has no data for.
function isBlankSortValue(v) {
  return v === null || v === undefined || v === "" || (typeof v === "number" && Number.isNaN(v));
}

/**
 * `state` is {key, type, dir} or null. `dir` is 1 or -1. `type` is "text"
 * or anything else (numeric).
 *
 * ⚠⚠ BLANKS SORT LAST IN BOTH DIRECTIONS - they are not "smallest", they
 * are "no answer", and no answer belongs at the bottom whichever way the
 * arrow points.
 *
 * Returns a NEW array; the caller's own list is never reordered in place.
 * PURE.
 */
function sortRowsBy(rows, state, valueOf) {
  const list = Array.isArray(rows) ? rows : [];
  if (!state || !state.key || typeof valueOf !== "function") return list;
  const dir = state.dir === -1 ? -1 : 1;
  const text = state.type === "text";
  return [...list].sort((a, b) => {
    const av = valueOf(a, state.key);
    const bv = valueOf(b, state.key);
    const ab = isBlankSortValue(av);
    const bb = isBlankSortValue(bv);
    if (ab && bb) return 0;
    if (ab) return 1;
    if (bb) return -1;
    if (text) return String(av).localeCompare(String(bv)) * dir;
    // ⚠ NUMBERS AS NUMBERS. "9" before "10" is a string sort, and every
    // numeric column here would read wrong the moment a figure passes 9.
    return (Number(av) - Number(bv)) * dir;
  });
}

/** The next state for a heading click: same column flips, new column starts ascending. */
function nextSortState(current, key, type) {
  if (current && current.key === key) return { key, type, dir: current.dir === 1 ? -1 : 1 };
  return { key, type, dir: 1 };
}
__m["table-sort.js"] = { isBlankSortValue, sortRowsBy, nextSortState };
})();
// ---- lib/catalog-view.js ----
(function () {
"use strict";
// lib/catalog-view.js - B-1023 (v2.0.49): the Catalog's PURE rules - which
// rows show, in what order, and how a figure is written. Shared by the
// laptop page (catalog/catalog.js imports it) and the phone's Catalog tab
// (remote/catalog-lib.js is this file + lib/table-sort.js, wrapped unchanged
// by test/_catalog-bundle.mjs). No chrome, no fetch, no storage.
//
// Zach 10/10: "A fast, easily searchable and filterable catalog of all my
// ASINs ... I'll need to filter between listings with stock and all
// listings. I need to be able to very quickly search ... by name, asin, etc".
const { sortRowsBy, nextSortState } = __m["table-sort.js"];

// The snapshot's storage key - a copy of lib/catalog.js CATALOG_KEY so the
// page does not import the builder (test v2049-c asserts the two are equal).
const PAGE_CATALOG_KEY = "shopperCatalog";
// The page's remembered filter + sort (this browser only).
const CATALOG_VIEW_KEY = "shopperCatalogView";

const CATALOG_FILTER_STOCK = "stock";
const CATALOG_FILTER_ALL = "all";
// Phone-only filters inside "with stock" (the phone gets with-stock rows only).
const CATALOG_FILTER_AVAILABLE = "available";
const CATALOG_FILTER_COMING = "coming";

// The columns, in the order the laptop table shows them. `type` "text" sorts
// A-Z first; every other column sorts biggest first on its first click.
// `tip` is the heading's hover text; the snapshot's `tips` (lib/catalog.js
// mergeCatalog) replaces it with the read's own window and source for Sold
// 7d (B-1032) and 30d margin (B-1035) - columnTip() below.
const CATALOG_COLUMNS = Object.freeze([
  Object.freeze({ key: "title", label: "Product", type: "text", tip: "Name, ASIN and SKU - the name opens the Amazon page" }),
  Object.freeze({ key: "avail", label: "Available", type: "num", fmt: "int", tip: "Qty Available (Replen Pulse)" }),
  Object.freeze({ key: "fcTransfer", label: "FC transfer", type: "num", fmt: "int", tip: "Qty FC Transfer (Replen Pulse)" }),
  Object.freeze({ key: "inbound", label: "Inbound", type: "num", fmt: "int", tip: "Qty Inbound (Replen Pulse)" }),
  Object.freeze({ key: "ordered", label: "Ordered", type: "num", fmt: "int", tip: "Qty Already Ordered (Replen Pulse)" }),
  Object.freeze({ key: "units30", label: "Sold 30d", type: "num", fmt: "int", tip: "Units sold in the last 30 days (Replen Pulse)" }),
  Object.freeze({ key: "units7", label: "Sold 7d", type: "num", fmt: "int", tip: "Units sold in the last 7 whole days, Central time (Amazon's orders report)" }),
  Object.freeze({ key: "velocity", label: "Velocity", type: "num", fmt: "dec", tip: "Units a day (Replen Pulse)" }),
  Object.freeze({ key: "bbMargin", label: "BB margin", type: "num", fmt: "pct", tip: "Margin at the Buy Box (Replen Pulse's own figure)" }),
  Object.freeze({ key: "sbMargin30", label: "30d margin", type: "num", fmt: "pct", tip: "Last 30 days: net profit / sales (Sellerboard)" }),
  Object.freeze({ key: "cost", label: "Cost", type: "num", fmt: "money", tip: "Cost (Replen Pulse)" }),
  Object.freeze({ key: "bbPrice", label: "Buy Box", type: "num", fmt: "money", tip: "Buy Box price (Seller Snap)" }),
  Object.freeze({ key: "myPrice", label: "My price", type: "num", fmt: "money", tip: "Your listed price (Seller Snap)" }),
]);

const isNum = (v) => typeof v === "number" && Number.isFinite(v);

// Zach's rule: a listing "with stock" has Available, FC Transfer or Inbound
// above 0. Ordered (not yet at Amazon) does not count. An unreadable field
// is not "above 0" - it is no answer, so it never makes a row count.
function hasStock(row) {
  return !!row && ((isNum(row.avail) && row.avail > 0) || (isNum(row.fcTransfer) && row.fcTransfer > 0) || (isNum(row.inbound) && row.inbound > 0));
}

// True when not one row carries any of the three stock figures - the
// With stock filter would then hide everything for a reason that is not
// "nothing has stock", so the page says so instead of showing 0 rows.
function stockFieldsMissing(rows) {
  const list = Array.isArray(rows) ? rows : [];
  if (!list.length) return false;
  return !list.some((r) => r && (isNum(r.avail) || isNum(r.fcTransfer) || isNum(r.inbound)));
}

// One lowercase string per row: title, ASIN and every SKU. Built once per
// data load; a keystroke only runs `includes` over it.
function searchText(row) {
  if (!row) return "";
  const skus = Array.isArray(row.skus) ? row.skus : [];
  return `${row.title || ""} ${row.asin || ""} ${skus.join(" ")}`.toLowerCase();
}

// Every word typed must appear somewhere (any order): "crest 3d" finds
// "Crest 3D White ...", "b07x" finds the ASIN, a SKU fragment finds its row.
function queryTerms(q) {
  return String(q || "").toLowerCase().split(/\s+/).filter(Boolean);
}
function matchesTerms(hay, terms) {
  for (const t of terms) if (hay.indexOf(t) < 0) return false;
  return true;
}

function filterKeeps(row, filter) {
  if (filter === CATALOG_FILTER_ALL) return true;
  if (filter === CATALOG_FILTER_AVAILABLE) return isNum(row.avail) && row.avail > 0;
  if (filter === CATALOG_FILTER_COMING) return (isNum(row.fcTransfer) && row.fcTransfer > 0) || (isNum(row.inbound) && row.inbound > 0);
  return hasStock(row);
}

function catalogValueOf(row, key) {
  const v = row ? row[key] : null;
  return v === undefined ? null : v;
}

// The rows to show, in order. `hay` = rows.map(searchText), computed once by
// the caller (same order as rows). Sort: lib/table-sort.js (blanks last in
// both directions - a blank is "no answer", never 0).
function selectCatalogRows(rows, { filter = CATALOG_FILTER_STOCK, query = "", sort = null, hay = null } = {}) {
  const list = Array.isArray(rows) ? rows : [];
  const terms = queryTerms(query);
  const out = [];
  for (let i = 0; i < list.length; i++) {
    const r = list[i];
    if (!r || !filterKeeps(r, filter)) continue;
    if (terms.length && !matchesTerms(hay ? hay[i] : searchText(r), terms)) continue;
    out.push(r);
  }
  return sort && sort.key ? sortRowsBy(out, sort, catalogValueOf) : out;
}

// The heading's hover text: the snapshot's own (window + source) when it has one.
function columnTip(col, tips) {
  const t = tips && col && typeof tips[col.key] === "string" && tips[col.key] ? tips[col.key] : null;
  return t || (col && (col.tip || col.label)) || "";
}

// A heading click: the same column flips; a new number column starts
// biggest first (who has the most stock / sells the most), text A-Z.
function catalogNextSort(current, key) {
  const col = CATALOG_COLUMNS.find((c) => c.key === key);
  const type = col && col.type === "text" ? "text" : "num";
  const next = nextSortState(current, key, type);
  if (!(current && current.key === key) && type !== "text") next.dir = -1;
  return next;
}

const DEFAULT_CATALOG_SORT = Object.freeze({ key: "units30", type: "num", dir: -1 });

// A stored view setting, checked: anything unknown falls back to the default.
function normalizeCatalogView(v) {
  const o = v && typeof v === "object" ? v : {};
  const filter = o.filter === CATALOG_FILTER_ALL ? CATALOG_FILTER_ALL : CATALOG_FILTER_STOCK;
  const col = o.sort && CATALOG_COLUMNS.find((c) => c.key === o.sort.key);
  const sort = col ? { key: col.key, type: col.type === "text" ? "text" : "num", dir: o.sort.dir === 1 ? 1 : -1 } : { ...DEFAULT_CATALOG_SORT };
  return { filter, sort };
}

// ---------------------------------------------------------------- writing

// "—" for no answer: a blank is never written as 0 (rule 59).
const NO_VALUE = "—";
function fmtCatalog(v, fmt) {
  if (!isNum(v)) return NO_VALUE;
  if (fmt === "money") return (v < 0 ? "-$" : "$") + Math.abs(v).toFixed(2);
  if (fmt === "pct") return `${v.toFixed(1)}%`;
  if (fmt === "dec") return v >= 10 ? v.toFixed(1) : v.toFixed(2);
  return Math.round(v).toLocaleString("en-US");
}

function fmtCount(n) {
  return isNum(n) ? Math.round(n).toLocaleString("en-US") : "0";
}

// "312 of 1,301"
function catalogCountLine(shown, total) {
  return `${fmtCount(shown)} of ${fmtCount(total)}`;
}

function agoText(ms, now = Date.now()) {
  if (!isNum(ms) || ms <= 0) return "never";
  const m = Math.round((now - ms) / 60000);
  if (m < 1) return "just now";
  if (m < 60) return `${m} min ago`;
  const h = Math.round(m / 60);
  return h < 48 ? `${h} h ago` : `${Math.round(h / 24)} days ago`;
}

// One line per source for the page and the phone: where each column group
// comes from, when it was last read, and - when the newest try failed -
// that the figures on screen are the last good ones.
function sourceLines(sources, now = Date.now()) {
  const out = [];
  for (const s of Array.isArray(sources) ? sources : []) {
    if (!s) continue;
    if (!s.at && !s.error) { out.push({ key: s.key, stale: true, text: `${s.label}: not read yet${s.when ? ` (${s.when})` : ""}.` }); continue; }
    if (s.stale) {
      out.push({
        key: s.key,
        stale: true,
        text: `${s.label}: the last read failed (${s.error || "no reason given"}) ${agoText(s.errorAt, now)} - ${s.at ? `showing the figures read ${agoText(s.at, now)}` : "nothing read yet"}.`,
      });
    } else {
      out.push({ key: s.key, stale: false, text: `${s.label}: read ${agoText(s.at, now)}${s.when ? ` (${s.when})` : ""}.` });
    }
  }
  return out;
}

// Amazon's image host, shortened on the phone payload (the id alone).
const AMAZON_IMAGE_PREFIX = "https://m.media-amazon.com/images/I/";
function thumbFromPayload(t) {
  const s = String(t || "");
  if (!s) return "";
  return /^https?:\/\//i.test(s) ? s : AMAZON_IMAGE_PREFIX + s;
}

// The phone payload's rows are arrays in `cols` order (lib/catalog.js
// projectCatalogForRemote) - back into { asin, title, ... } here.
function unpackCatalogRow(cols, arr) {
  const o = {};
  (Array.isArray(cols) ? cols : []).forEach((k, i) => { o[k] = Array.isArray(arr) && arr[i] !== undefined ? arr[i] : null; });
  o.skus = o.sku ? [o.sku] : [];
  return o;
}
__m["catalog-view.js"] = { PAGE_CATALOG_KEY, CATALOG_VIEW_KEY, CATALOG_FILTER_STOCK, CATALOG_FILTER_ALL, CATALOG_FILTER_AVAILABLE, CATALOG_FILTER_COMING, CATALOG_COLUMNS, hasStock, stockFieldsMissing, searchText, queryTerms, matchesTerms, catalogValueOf, selectCatalogRows, columnTip, catalogNextSort, DEFAULT_CATALOG_SORT, normalizeCatalogView, NO_VALUE, fmtCatalog, fmtCount, catalogCountLine, agoText, sourceLines, AMAZON_IMAGE_PREFIX, thumbFromPayload, unpackCatalogRow };
})();
root.ShopperCatalog = Object.freeze(Object.assign({}, ...Object.values(__m)));
})(typeof self !== "undefined" ? self : globalThis);
