// remote/dash-lib.js - GENERATED by test/_dash-bundle.mjs (B-833 v2.0.18). DO NOT EDIT.
// The phone's copy of lib/dashboard-todo.js, wrapped unchanged.
// Edit lib/, then: node test/_dash-bundle.mjs --write
(function (root) {
const __m = {};
// ---- lib/dashboard-todo.js ----
(function () {
"use strict";
// lib/dashboard-todo.js - B-833 (v2.0.18): the Dashboard's "Glance + To-do".
//
// Zach: "It feels like a mish mash of a bunch of random information instead
// of a true dashboard that can be used as a quick glance at the most
// pertinent info and a launching point for what I need to do next."
// He chose "Glance + To-do": five big number tiles on top, a ranked "Do next"
// list under them (one row per thing that needs him, ONE button each), and a
// one-line status at the bottom.
//
// PURE and import-free: the laptop page (dashboard/dashboard.js) and the
// phone's Home tab (remote/dash-lib.js, generated from this file by
// test/_dash-bundle.mjs) run the SAME code. Nothing here reads storage or
// recomputes a figure - it only arranges what the snapshot already holds
// (a mirror, not a second opinion).
//
// Targets are names, not messages: the laptop maps them to
// SHOPPER_OPEN_*_TAB, the phone maps them to its own tabs.
//   buylist buyqueue pipeline arrivals belowmin runreviews fba wizard
//   cashflow bank expand

const TARGETS = Object.freeze(["buylist", "buyqueue", "pipeline", "arrivals", "belowmin", "runreviews", "fba", "wizard", "cashflow", "bank", "expand"]);

// Order = priority (Zach's list). Rows with nothing to do are not built.
const DO_NEXT_ORDER = Object.freeze(["urgent", "owed", "needsYou", "belowMin", "arrivals", "runReviews", "fba", "shipment"]);
const SHIPMENT_NOTIFICATION_TYPE = "shipment_prompt";

const num = (v) => {
  if (v == null || v === "") return null;
  const x = Number(v);
  return Number.isFinite(x) ? x : null;
};
const plural = (n, one, many) => `${n} ${n === 1 ? one : many || one + "s"}`;

function money0(v) {
  const x = num(v);
  if (x == null) return "-";
  return (x < 0 ? "-$" : "$") + Math.round(Math.abs(x)).toLocaleString("en-US");
}
function money2(v) {
  const x = num(v);
  if (x == null) return "-";
  return (x < 0 ? "-$" : "$") + Math.abs(x).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

// "+12.3% vs the 7 days before", or "" when there is nothing to compare.
function changeLine(now, before) {
  const a = num(now), b = num(before);
  if (a == null || !(b > 0)) return { text: "", dir: "flat" };
  const p = Math.round(((a - b) / b) * 1000) / 10;
  return { text: `${p > 0 ? "+" : ""}${p}% vs the 7 days before`, dir: p > 0 ? "up" : p < 0 ? "down" : "flat" };
}

const SEV_RANK = { critical: 3, high: 2, medium: 1, info: 0 };
function topSeverity(list) {
  let best = "info";
  for (const n of list || []) if ((SEV_RANK[n && n.severity] || 0) > SEV_RANK[best]) best = n.severity;
  return best;
}

// input (everything optional; null = "not read"):
//   loaded            the snapshot exists (false -> no rows, no "caught up")
//   notifications     the OPEN notifications (after Done / Dismiss) - [{key,type,severity,title,count,detail}]
//   notificationCount how many are open in all, when `notifications` is a capped list (the phone's)
//   nextRun           { state: "owed"|"caughtUp"|"unknown", neededToday, spentToday }
//   nightlyReady      tonight's buy list is built and fresh
//   needsYou          pipeline questions waiting on Zach
//   arrivalsToday     orders due today        overdue   orders overdue
//   belowMin          listings with the Buy Box under the min
//   runReviews        { latestRunSevere }
//   fbaAlerts         [{ text }]
// -> [{ id, rank, severity, title, detail, go: { label, target }, notifs?: [...], count }]
function buildDoNext(input = {}) {
  const rows = [];
  if (!input || !input.loaded) return rows;
  const notifs = Array.isArray(input.notifications) ? input.notifications : [];
  const shipment = notifs.filter((n) => n && n.type === SHIPMENT_NOTIFICATION_TYPE);
  const urgent = notifs.filter((n) => n && n.type !== SHIPMENT_NOTIFICATION_TYPE);
  const add = (r) => rows.push(r);

  if (urgent.length) {
    const sorted = urgent.slice().sort((a, b) => (SEV_RANK[b.severity] || 0) - (SEV_RANK[a.severity] || 0));
    const heads = sorted.slice(0, 2).map((n) => String(n.title || "").trim()).filter(Boolean);
    const all = Number.isFinite(Number(input.notificationCount)) ? Math.max(urgent.length, Number(input.notificationCount) - shipment.length) : urgent.length;
    add({
      id: "urgent",
      severity: topSeverity(urgent),
      title: `${plural(all, "notification")} need${all === 1 ? "s" : ""} a look`,
      detail: heads.join(" · ") + (all > heads.length ? ` · +${all - heads.length} more` : ""),
      go: { label: "Review", target: "expand" },
      notifs: sorted,
      count: all,
    });
  }

  const next = input.nextRun || {};
  const needed = num(next.neededToday);
  if (next.state === "owed" && needed != null && needed > 0) {
    const spent = num(next.spentToday);
    add({
      id: "owed",
      severity: "high",
      title: `${money0(needed)} still to buy today`,
      detail: (spent != null ? `${money0(spent)} spent so far today.` : "") + (input.nightlyReady ? " Tonight's buy list is ready." : ""),
      go: { label: "Buylist", target: "buylist" },
      count: 1,
    });
  }

  const needsYou = num(input.needsYou) || 0;
  if (needsYou > 0) {
    add({
      id: "needsYou",
      severity: "medium",
      title: `${plural(needsYou, "thing")} waiting on your answer`,
      detail: "Pipeline questions - an order, a count or a shipment.",
      go: { label: "Answer", target: "pipeline" },
      count: needsYou,
    });
  }

  const below = num(input.belowMin) || 0;
  if (below > 0) {
    add({
      id: "belowMin",
      severity: "medium",
      title: `${plural(below, "listing")} below your Seller Snap min`,
      detail: "The Buy Box is under your min price.",
      go: { label: "Below Min", target: "belowmin" },
      count: below,
    });
  }

  const today = num(input.arrivalsToday) || 0;
  const overdue = num(input.overdue) || 0;
  if (today > 0 || overdue > 0) {
    const bits = [];
    if (today > 0) bits.push(`${plural(today, "order")} arriving today`);
    if (overdue > 0) bits.push(`${overdue} overdue`);
    add({
      id: "arrivals",
      severity: overdue > 0 ? "high" : "medium",
      title: bits.join(" · "),
      detail: overdue > 0 ? "Check the overdue ones - did they arrive?" : "Count them in when they land.",
      go: { label: "Pipeline", target: "arrivals" },
      count: today + overdue,
    });
  }

  const severe = num(input.runReviews && input.runReviews.latestRunSevere) || 0;
  if (severe > 0) {
    add({
      id: "runReviews",
      severity: "high",
      title: `${plural(severe, "severe finding")} on the latest run`,
      detail: "The run review flagged things worth a look.",
      go: { label: "Run reviews", target: "runreviews" },
      count: severe,
    });
  }

  const alerts = Array.isArray(input.fbaAlerts) ? input.fbaAlerts.filter(Boolean) : [];
  if (alerts.length) {
    const first = String(alerts[0].text || "").replace(/^Supply squeeze: /, "Supply squeeze - ");
    add({
      id: "fba",
      severity: "medium",
      title: plural(alerts.length, "FBA alert"),
      detail: first.length > 140 ? first.slice(0, 137).replace(/\s+\S*$/, "") + "…" : first,
      go: { label: "FBA Inventory", target: "fba" },
      count: alerts.length,
    });
  }

  if (shipment.length) {
    add({
      id: "shipment",
      severity: "medium",
      title: String(shipment[0].title || "A shipment is ready to build"),
      detail: String(shipment[0].detail || "").slice(0, 160),
      go: { label: "Ship to Amazon", target: "wizard" },
      notifs: shipment,
      count: shipment.length,
    });
  }
  rows.forEach((r, i) => { r.rank = i + 1; });
  return rows;
}

// The five tiles. input:
//   spend { spentToday, neededToday }   bank (number)
//   cash  the Cash Flow summary (sales7, salesPrev7, through, payoutNext30?, next30?)
//   stock { house, prep, inTransit, fba }  dollars at cost, null = unknown
// -> [{ id, label, value, sub, tone, target, split? }]
function buildTiles(input = {}) {
  const i = input || {};
  const spend = i.spend || {};
  const cash = i.cash || null;
  const out = [];

  const ch = cash ? changeLine(cash.sales7, cash.salesPrev7) : { text: "", dir: "flat" };
  out.push({
    id: "sales",
    label: "7-day sales",
    value: cash ? money0(cash.sales7) : "-",
    sub: cash ? ch.text || `7 days to ${cash.through || "-"}` : "Cash Flow not read yet",
    tone: cash ? ch.dir : "flat",
    target: "cashflow",
  });

  const spent = num(spend.spentToday), needed = num(spend.neededToday);
  out.push({
    id: "spend",
    label: "Spent today",
    value: money0(spent),
    sub: needed != null ? `${money0(needed)} needed today` : "Needed today: not loaded",
    tone: needed != null && needed > 0 ? "warn" : "flat",
    target: "buyqueue",
  });

  const bank = num(i.bank);
  out.push({
    id: "bank",
    label: "Bank balance",
    value: money2(bank),
    sub: "",
    tone: bank != null && bank < 0 ? "down" : "flat",
    target: "bank",
  });

  // Cash in the next 30 days: the payout forecast; until the Cash Flow
  // summary carries it (one built before v2.0.18 does not), the sales
  // forecast - and the tile says which it is.
  const payout = cash && cash.payoutNext30 ? cash.payoutNext30 : null;
  const sales30 = cash && cash.next30 ? cash.next30 : null;
  const f = payout || sales30;
  out.push({
    id: "cash30",
    label: "Next 30 days",
    value: f ? money0(f.total) : "-",
    sub: f ? `${payout ? "payout" : "sales"}, projected · ${money0(f.low)} to ${money0(f.high)}` : cash ? "Needs 3 weeks of history" : "Cash Flow not read yet",
    tone: "flat",
    target: "cashflow",
  });

  const st = i.stock || {};
  const parts = [["House", num(st.house)], ["Prep", num(st.prep)], ["In transit", num(st.inTransit)], ["FBA", num(st.fba)]];
  const known = parts.filter(([, v]) => v != null);
  out.push({
    id: "stock",
    label: "Stock at cost",
    value: known.length ? money0(known.reduce((s, [, v]) => s + v, 0)) : "-",
    sub: known.length && known.length < parts.length ? `${parts.filter(([, v]) => v == null).map(([n]) => n).join(", ")} not read yet` : "",
    tone: "flat",
    target: "pipeline",
    split: parts.map(([label, v]) => ({ label, value: v == null ? "-" : money0(v) })),
  });
  return out;
}

// FBA stage $ = what is at Amazon, at cost: Available + Inbound + Reserved
// (Unfulfillable is not sellable stock). tiles = fbaCardModel().tiles.
function fbaStockValue(tiles) {
  if (!Array.isArray(tiles) || !tiles.length) return null;
  let total = 0;
  let any = false;
  for (const t of tiles) {
    if (t && (t.key === "available" || t.key === "inboundAll" || t.key === "reservedTotal")) {
      const v = num(t.value);
      if (v != null) { total += v; any = true; }
    }
  }
  return any ? Math.round(total * 100) / 100 : null;
}
__m["dashboard-todo.js"] = { TARGETS, DO_NEXT_ORDER, SHIPMENT_NOTIFICATION_TYPE, money0, money2, changeLine, topSeverity, buildDoNext, buildTiles, fbaStockValue };
})();
root.ShopperGlance = Object.freeze(Object.assign({}, ...Object.values(__m)));
})(self);
