// remote/dash-lib.js - GENERATED by test/_dash-bundle.mjs (B-833 v2.0.18). DO NOT EDIT.
// The phone's copy of lib/dashboard-todo.js, wrapped unchanged.
// Edit lib/, then: node test/_dash-bundle.mjs --write
(function (root) {
const __m = {};
// ---- lib/dashboard-todo.js ----
(function () {
"use strict";
// lib/dashboard-todo.js - B-833 (v2.0.18): the Dashboard's "Glance + To-do".
//
// Zach: "It feels like a mish mash of a bunch of random information instead
// of a true dashboard that can be used as a quick glance at the most
// pertinent info and a launching point for what I need to do next."
// He chose "Glance + To-do": five big number tiles on top, a ranked "Do next"
// list under them (one row per thing that needs him, ONE button each), and a
// one-line status at the bottom.
//
// PURE and import-free: the laptop page (dashboard/dashboard.js) and the
// phone's Home tab (remote/dash-lib.js, generated from this file by
// test/_dash-bundle.mjs) run the SAME code. Nothing here reads storage or
// recomputes a figure - it only arranges what the snapshot already holds
// (a mirror, not a second opinion).
//
// Targets are names, not messages: the laptop maps them to
// SHOPPER_OPEN_*_TAB, the phone maps them to its own tabs.
//   buylist buyqueue pipeline arrivals belowmin runreviews fba wizard
//   cashflow bank expand plaid
// B-838 (v2.0.20): "plaid" = the Plaid balances tile. The laptop opens
// Settings -> Accounts (where the Plaid card is); the phone opens Bank.

// B-941 (v2.0.35): "voc" = Seller Central's Voice of the Customer page (the
// laptop opens it in a tab, the phone in the browser).
const TARGETS = Object.freeze(["buylist", "buyqueue", "pipeline", "arrivals", "belowmin", "runreviews", "fba", "wizard", "cashflow", "bank", "expand", "plaid", "voc"]);

// Order = priority (Zach's list). Rows with nothing to do are not built.
// B-837 (v2.0.20): "stranded" - units Amazon holds but cannot sell.
// B-862 (v2.0.23): "pricingErrors" - listings Amazon deactivated for a
// suspected pricing error (lib/pricing-errors.js), right after Below Min.
// B-941 (v2.0.35): "voc" - listings at Poor / Very poor CX Health (Voice of the
// Customer), right after pricing errors: a listing Amazon may suppress.
const DO_NEXT_ORDER = Object.freeze(["urgent", "owed", "needsYou", "belowMin", "pricingErrors", "voc", "arrivals", "runReviews", "fba", "stranded", "shipment"]);
const SHIPMENT_NOTIFICATION_TYPE = "shipment_prompt";

const num = (v) => {
  if (v == null || v === "") return null;
  const x = Number(v);
  return Number.isFinite(x) ? x : null;
};
const plural = (n, one, many) => `${n} ${n === 1 ? one : many || one + "s"}`;

// B-861 / B-862 (v2.0.23): product lines inside a Do next row.
const DO_NEXT_LINE_MAX = 10;
function shortTitle(t, max = 60) {
  const s = String(t || "").replace(/\s+/g, " ").trim();
  return s.length > max ? s.slice(0, max - 1).replace(/\s+\S*$/, "") + "…" : s;
}
// A stranded product: "B0XXXXXXXX Title (25 units)".
function strandedLineText(it) {
  const id = String((it && (it.asin || it.sku)) || "");
  const t = shortTitle(it && it.title);
  return `${id}${t ? " " + t : " (title not on file)"} (${plural(num(it && it.units) || 0, "unit")})`;
}
// Words for a stored offer reading (lib/pricing-errors.js pricingGlance
// item.offer): "$40.10 3G SUPPLIER (Seller Snap, 2h ago)" /
// "none from another seller" / "not read yet". Never a guess.
function pricingOfferText(offer, now = null) {
  if (!offer) return "not read yet";
  const when = now != null && offer.at ? ageText(offer.at, now) : "";
  const src = [offer.via, when].filter(Boolean).join(", ");
  if (offer.error) return `not read yet (${offer.error})`;
  const p = num(offer.price);
  if (p == null) return offer.none ? `none from another seller${src ? ` (${src})` : ""}` : "not read yet";
  return `${money2(p)}${offer.seller ? ` ${offer.seller}` : ""}${src ? ` (${src})` : ""}`;
}
// A pricing-error listing: "B0XXXXXXXX Title - ours $35.27, highest other offer $40.10 … ".
function pricingLineText(it, now = null) {
  const id = String((it && (it.asin || it.sku)) || "");
  const t = shortTitle(it && it.title);
  const ours = num(it && it.price);
  return `${id}${t ? " " + t : ""} - ours ${ours == null ? "not on file" : money2(ours)}, highest other offer ${pricingOfferText(it && it.offer, now)}`;
}
function linesDetail(texts, total, moreWhere) {
  const shown = texts.slice(0, DO_NEXT_LINE_MAX);
  const more = total - shown.length;
  return shown.join(" · ") + (more > 0 ? ` · +${more} more on the ${moreWhere} page` : "");
}

function money0(v) {
  const x = num(v);
  if (x == null) return "-";
  return (x < 0 ? "-$" : "$") + Math.round(Math.abs(x)).toLocaleString("en-US");
}
function money2(v) {
  const x = num(v);
  if (x == null) return "-";
  return (x < 0 ? "-$" : "$") + Math.abs(x).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

// "+12.3% vs the 7 days before", or "" when there is nothing to compare.
function changeLine(now, before) {
  const a = num(now), b = num(before);
  if (a == null || !(b > 0)) return { text: "", dir: "flat" };
  const p = Math.round(((a - b) / b) * 1000) / 10;
  return { text: `${p > 0 ? "+" : ""}${p}% vs the 7 days before`, dir: p > 0 ? "up" : p < 0 ? "down" : "flat" };
}

const SEV_RANK = { critical: 3, high: 2, medium: 1, info: 0 };
function topSeverity(list) {
  let best = "info";
  for (const n of list || []) if ((SEV_RANK[n && n.severity] || 0) > SEV_RANK[best]) best = n.severity;
  return best;
}

// input (everything optional; null = "not read"):
//   loaded            the snapshot exists (false -> no rows, no "caught up")
//   notifications     the OPEN notifications (after Done / Dismiss) - [{key,type,severity,title,count,detail}]
//   notificationCount how many are open in all, when `notifications` is a capped list (the phone's)
//   nextRun           { state: "owed"|"caughtUp"|"unknown", neededToday, spentToday }
//   nightlyReady      tonight's buy list is built and fresh
//   needsYou          pipeline questions waiting on Zach
//   arrivalsToday     orders due today        overdue   orders overdue
//   belowMin          listings with the Buy Box under the min
//   runReviews        { latestRunSevere }
//   fbaAlerts         [{ text }]
//   stranded          strandedGlance() (lib/stranded.js) - { known, units, skus, items? }
//   pricingErrors     pricingGlance() (lib/pricing-errors.js) - { known, count, items } - B-862
//   voc               vocGlance() (lib/voc-health.js) - { known, bad, atRisk, badCount, atRiskCount, pcxBadCount, changes } - B-941
//   now               ms, for "2h ago" on an offer reading (optional)
// -> [{ id, rank, severity, title, detail, go: { label, target }, notifs?: [...], count }]
function buildDoNext(input = {}) {
  const rows = [];
  if (!input || !input.loaded) return rows;
  const notifs = Array.isArray(input.notifications) ? input.notifications : [];
  const shipment = notifs.filter((n) => n && n.type === SHIPMENT_NOTIFICATION_TYPE);
  const urgent = notifs.filter((n) => n && n.type !== SHIPMENT_NOTIFICATION_TYPE);
  const add = (r) => rows.push(r);

  if (urgent.length) {
    const sorted = urgent.slice().sort((a, b) => (SEV_RANK[b.severity] || 0) - (SEV_RANK[a.severity] || 0));
    const heads = sorted.slice(0, 2).map((n) => String(n.title || "").trim()).filter(Boolean);
    const all = Number.isFinite(Number(input.notificationCount)) ? Math.max(urgent.length, Number(input.notificationCount) - shipment.length) : urgent.length;
    add({
      id: "urgent",
      severity: topSeverity(urgent),
      title: `${plural(all, "notification")} need${all === 1 ? "s" : ""} a look`,
      detail: heads.join(" · ") + (all > heads.length ? ` · +${all - heads.length} more` : ""),
      go: { label: "Review", target: "expand" },
      notifs: sorted,
      count: all,
    });
  }

  const next = input.nextRun || {};
  const needed = num(next.neededToday);
  if (next.state === "owed" && needed != null && needed > 0) {
    const spent = num(next.spentToday);
    add({
      id: "owed",
      severity: "high",
      title: `${money0(needed)} still to buy today`,
      detail: (spent != null ? `${money0(spent)} spent so far today.` : "") + (input.nightlyReady ? " Tonight's buy list is ready." : ""),
      go: { label: "Buylist", target: "buylist" },
      count: 1,
    });
  }

  const needsYou = num(input.needsYou) || 0;
  if (needsYou > 0) {
    add({
      id: "needsYou",
      severity: "medium",
      title: `${plural(needsYou, "thing")} waiting on your answer`,
      detail: "Pipeline questions - an order, a count or a shipment.",
      go: { label: "Answer", target: "pipeline" },
      count: needsYou,
    });
  }

  const below = num(input.belowMin) || 0;
  if (below > 0) {
    add({
      id: "belowMin",
      severity: "medium",
      title: `${plural(below, "listing")} below your Seller Snap min`,
      detail: "The Buy Box is under your min price.",
      go: { label: "Pricing", target: "belowmin" },
      count: below,
    });
  }

  // B-862 (v2.0.23): listings deactivated for a suspected pricing error.
  const pe = input.pricingErrors || null;
  const peItems = pe && Array.isArray(pe.items) ? pe.items.filter(Boolean) : [];
  const peCount = pe && pe.known ? Math.max(num(pe.count) || 0, peItems.length) : 0;
  if (peCount > 0) {
    const now = num(input.now);
    add({
      id: "pricingErrors",
      severity: "high",
      title: `${plural(peCount, "listing")} deactivated for a pricing error`,
      detail: linesDetail(peItems.map((it) => pricingLineText(it, now)), peCount, "Pricing") + ". Fix the price, then mark it fixed on the Pricing page.",
      lines: peItems.map((it) => ({ asin: String(it.asin || ""), sku: String(it.sku || ""), title: String(it.title || ""), price: num(it.price), offer: pricingOfferText(it.offer, now), text: pricingLineText(it, now) })),
      go: { label: "Pricing", target: "belowmin" },
      count: peCount,
    });
  }

  // B-941 (v2.0.35): Voice of the Customer - every listing at Poor / Very poor
  // CX Health (the standing list) and every listing at risk of the high-return-
  // rate flag; what changed on the last read leads the detail.
  const vg = input.voc || null;
  const vBad = vg && vg.known && Array.isArray(vg.bad) ? vg.bad.filter(Boolean) : [];
  const vRisk = vg && vg.known && Array.isArray(vg.atRisk) ? vg.atRisk.filter((x) => x && !vBad.some((b) => b.asin === x.asin)) : [];
  const vBadCount = vg && vg.known ? Math.max(num(vg.badCount) || 0, vBad.length) : 0;
  const vRiskCount = vg && vg.known ? Math.max((num(vg.atRiskCount) || 0) - (vg.atRisk || []).filter((x) => x && vBad.some((b) => b.asin === x.asin)).length, vRisk.length) : 0;
  if (vBadCount + vRiskCount > 0) {
    const veryPoor = vBad.some((x) => x.grade === "VERY_POOR");
    const changed = Array.isArray(vg.changes) ? vg.changes.filter(Boolean) : [];
    const items = [...vBad, ...vRisk];
    const bits = [];
    if (vBadCount) bits.push(`${plural(vBadCount, "listing")} at Poor / Very poor CX Health`);
    if (vRiskCount) bits.push(`${vRiskCount} at risk of the return-rate flag`);
    const pcx = num(vg.pcxBadCount);
    add({
      id: "voc",
      severity: veryPoor || vRiskCount > 0 || changed.length ? "high" : "medium",
      title: bits.join(" · "),
      detail: (changed.length ? `Changed on the last read: ${changed.slice(0, 3).map((c) => String(c.text || c.asin)).join("; ")}${changed.length > 3 ? ` (+${changed.length - 3} more)` : ""}. ` : "")
        + linesDetail(items.map((x) => String(x.text || x.asin)), vBadCount + vRiskCount, "Voice of the Customer")
        + `. Voice of the Customer in Seller Central${pcx ? ` (its PCX grade puts ${pcx} at Poor / Very poor - not alerted on)` : ""}.`,
      lines: items.map((x) => ({ asin: String(x.asin || ""), title: String(x.title || ""), grade: String(x.grade || ""), text: String(x.text || x.asin || "") })),
      go: { label: "Voice of the Customer", target: "voc" },
      count: vBadCount + vRiskCount,
    });
  }

  const today = num(input.arrivalsToday) || 0;
  const overdue = num(input.overdue) || 0;
  if (today > 0 || overdue > 0) {
    const bits = [];
    if (today > 0) bits.push(`${plural(today, "order")} arriving today`);
    if (overdue > 0) bits.push(`${overdue} overdue`);
    add({
      id: "arrivals",
      severity: overdue > 0 ? "high" : "medium",
      title: bits.join(" · "),
      detail: overdue > 0 ? "Check the overdue ones - did they arrive?" : "Count them in when they land.",
      go: { label: "Pipeline", target: "arrivals" },
      count: today + overdue,
    });
  }

  const severe = num(input.runReviews && input.runReviews.latestRunSevere) || 0;
  if (severe > 0) {
    add({
      id: "runReviews",
      severity: "high",
      title: `${plural(severe, "severe finding")} on the latest run`,
      detail: "The run review flagged things worth a look.",
      go: { label: "Run reviews", target: "runreviews" },
      count: severe,
    });
  }

  const alerts = Array.isArray(input.fbaAlerts) ? input.fbaAlerts.filter(Boolean) : [];
  if (alerts.length) {
    const first = String(alerts[0].text || "").replace(/^Supply squeeze: /, "Supply squeeze - ");
    add({
      id: "fba",
      severity: "medium",
      title: plural(alerts.length, "FBA alert"),
      detail: first.length > 140 ? first.slice(0, 137).replace(/\s+\S*$/, "") + "…" : first,
      go: { label: "FBA Inventory", target: "fba" },
      count: alerts.length,
    });
  }

  const sg = input.stranded || null;
  const strandedUnits = sg && sg.known ? num(sg.units) || 0 : 0;
  if (strandedUnits > 0) {
    const skus = num(sg.skus) || 0;
    // B-861 (v2.0.23): every stranded product - ASIN, title, stranded units.
    const items = Array.isArray(sg.items) ? sg.items.filter(Boolean) : [];
    add({
      id: "stranded",
      severity: "medium",
      title: `${plural(strandedUnits, "unit")} stranded at Amazon`,
      detail: items.length
        ? `${linesDetail(items.map(strandedLineText), Math.max(skus, items.length), "FBA Inventory")}. No active listing - Amazon holds them but cannot sell them. Fix the listing or send a removal.`
        : `${plural(skus, "SKU")} with no active listing - Amazon holds them but cannot sell them. Fix the listing or send a removal.`,
      lines: items.map((it) => ({ asin: String(it.asin || ""), sku: String(it.sku || ""), title: String(it.title || ""), units: num(it.units) || 0, text: strandedLineText(it) })),
      go: { label: "FBA Inventory", target: "fba" },
      count: strandedUnits,
    });
  }

  if (shipment.length) {
    add({
      id: "shipment",
      severity: "medium",
      title: String(shipment[0].title || "A shipment is ready to build"),
      detail: String(shipment[0].detail || "").slice(0, 160),
      go: { label: "Ship to Amazon", target: "wizard" },
      notifs: shipment,
      count: shipment.length,
    });
  }
  rows.forEach((r, i) => { r.rank = i + 1; });
  return rows;
}

// ---- B-858 (v2.0.22): the Sellerboard "Yesterday" / "This Month" cards ----
// Zach 10/5: replace the 7-day sales tile with two cards copied from his
// Sellerboard dashboard. "Yesterday" = the day before the CURRENT BUYING DAY,
// which rolls over at 4 AM America/Chicago (not midnight): at 2 AM on 10/6
// the card still shows 10/4; from 4 AM it shows 10/5. "This Month" = the 1st
// of yesterday's month through yesterday - so on the 1st (no full day of the
// new month yet) it is the whole previous month, headed "Last Month".
// Days come from the Cash Flow summary's `days` (compact SB Daily rows). A
// day that is not in it says "not read yet" - never $0.
const SB_DAY_ROLLOVER_HOUR = 4;

function chicagoClock(nowMs) {
  const parts = new Intl.DateTimeFormat("en-US", { timeZone: "America/Chicago", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", hourCycle: "h23" }).formatToParts(new Date(nowMs));
  const g = (t) => Number((parts.find((x) => x.type === t) || {}).value);
  return { day: `${g("year")}-${String(g("month")).padStart(2, "0")}-${String(g("day")).padStart(2, "0")}`, hour: g("hour") % 24 };
}

function dayKeyAdd(key, n) {
  const [y, m, d] = String(key).split("-").map(Number);
  return new Date(Date.UTC(y, m - 1, d + n)).toISOString().slice(0, 10);
}

// "2026-10-04" -> "10/4/2026" (Sellerboard's own date style).
function usDate(key) {
  const [y, m, d] = String(key).split("-").map(Number);
  return `${m}/${d}/${y}`;
}

function sbCardRange(nowMs) {
  const t = num(nowMs);
  if (t == null) return null;
  const c = chicagoClock(t);
  const buyingDay = c.hour < SB_DAY_ROLLOVER_HOUR ? dayKeyAdd(c.day, -1) : c.day;
  const yesterday = dayKeyAdd(buyingDay, -1);
  const monthStart = yesterday.slice(0, 8) + "01";
  const sameMonth = yesterday.slice(0, 7) === buyingDay.slice(0, 7);
  return { buyingDay, yesterday, monthStart, monthEnd: yesterday, monthHeader: sameMonth ? "This Month" : "Last Month" };
}

// Sums the days from..to (inclusive). read = days found, want = days in range.
function sumSbDays(days, from, to) {
  const out = { read: 0, want: 0, sales: 0, orders: 0, units: 0, refunds: 0, ads: 0, payout: 0, netProfit: 0, cogs: 0 };
  const byDay = new Map();
  for (const d of Array.isArray(days) ? days : []) if (d && typeof d.day === "string") byDay.set(d.day, d);
  for (let k = from, guard = 0; k <= to && guard < 400; k = dayKeyAdd(k, 1), guard++) {
    out.want++;
    const d = byDay.get(k);
    if (!d) continue;
    out.read++;
    for (const f of ["sales", "orders", "units", "refunds", "ads", "payout", "netProfit", "cogs"]) out[f] += num(d[f]) || 0;
  }
  for (const f of ["sales", "ads", "payout", "netProfit", "cogs"]) out[f] = Math.round(out[f] * 100) / 100;
  return out;
}

function pctText(n, d) {
  const a = num(n), b = num(d);
  if (a == null || b == null || !(Math.abs(b) > 0)) return "-";
  return `${Math.round((a / Math.abs(b)) * 100)}%`;
}

function sbCard(id, header, agg, note) {
  const has = agg && agg.read > 0;
  const missing = agg ? agg.want - agg.read : 0;
  const v = (f) => (has ? f() : "-");
  return {
    id,
    label: header,
    value: has ? money2(agg.sales) : "not read yet",
    sub: note || (has && missing > 0 ? `Sales · ${plural(missing, "day")} not read yet` : "Sales"),
    tone: "flat",
    target: "cashflow",
    split: [
      { label: "Orders / Items", value: v(() => `${agg.orders.toLocaleString("en-US")} / ${agg.units.toLocaleString("en-US")}`) },
      { label: "Returns", value: v(() => agg.refunds.toLocaleString("en-US")) },
      { label: "Ad cost", value: v(() => money2(agg.ads)) },
      { label: "Est payout", value: v(() => money2(agg.payout)) },
      // ROI = net profit / cost of goods; margin = net profit / sales.
      { label: "ROI / Margin", value: v(() => `${pctText(agg.netProfit, agg.cogs)} / ${pctText(agg.netProfit, agg.sales)}`) },
      { label: "Net profit", value: v(() => money2(agg.netProfit)) },
    ],
  };
}

// cash = the Cash Flow summary (its `days`), now = ms. -> the two cards.
function buildSbCards(cash, now) {
  const r = sbCardRange(now);
  const days = cash && Array.isArray(cash.days) ? cash.days : null;
  const yHead = r ? `Yesterday · ${usDate(r.yesterday)}` : "Yesterday";
  const mHead = r ? `${r.monthHeader} · ${usDate(r.monthStart)} to ${usDate(r.monthEnd)}` : "This Month";
  const note = !cash ? "Cash Flow not read yet" : !days || !r ? "Sales · not read yet" : "";
  return [
    sbCard("sbYesterday", yHead, days && r ? sumSbDays(days, r.yesterday, r.yesterday) : null, note),
    sbCard("sbMonth", mHead, days && r ? sumSbDays(days, r.monthStart, r.monthEnd) : null, note),
  ];
}

// The tiles (six since v2.0.20; v2.0.22 B-858: the 7-day sales tile became
// the two Sellerboard cards, so seven). input:
//   spend { spentToday, neededToday }   bank (number)
//   plaid plaidGlance() (lib/plaid-client.js) - B-838; now (ms) for its age
//   stranded strandedGlance() - B-837, a line under the Stock tile
//   cash  the Cash Flow summary (days [B-858], payoutNext30?, next30?); now (ms) also picks the cards' days
//   stock { house, prep, inTransit, fba }  dollars at cost, null = unknown
// -> [{ id, label, value, sub, tone, target, split? }]
function buildTiles(input = {}) {
  const i = input || {};
  const spend = i.spend || {};
  const cash = i.cash || null;
  const out = [];

  out.push(...buildSbCards(cash, i.now));

  const spent = num(spend.spentToday), needed = num(spend.neededToday);
  out.push({
    id: "spend",
    label: "Spent today",
    value: money0(spent),
    sub: needed != null ? `${money0(needed)} needed today` : "Needed today: not loaded",
    tone: needed != null && needed > 0 ? "warn" : "flat",
    target: "buyqueue",
  });

  const bank = num(i.bank);
  out.push({
    id: "bank",
    label: "Bank balance",
    value: money2(bank),
    sub: "",
    tone: bank != null && bank < 0 ? "down" : "flat",
    target: "bank",
  });

  out.push(plaidTile(i.plaid || null, num(i.now) || null));

  // Cash in the next 30 days: the payout forecast; until the Cash Flow
  // summary carries it (one built before v2.0.18 does not), the sales
  // forecast - and the tile says which it is.
  const payout = cash && cash.payoutNext30 ? cash.payoutNext30 : null;
  const sales30 = cash && cash.next30 ? cash.next30 : null;
  const f = payout || sales30;
  out.push({
    id: "cash30",
    label: "Next 30 days",
    value: f ? money0(f.total) : "-",
    sub: f ? `${payout ? "payout" : "sales"}, projected · ${money0(f.low)} to ${money0(f.high)}` : cash ? "Needs 3 weeks of history" : "Cash Flow not read yet",
    tone: "flat",
    target: "cashflow",
  });

  const st = i.stock || {};
  const parts = [["House", num(st.house)], ["Prep", num(st.prep)], ["In transit", num(st.inTransit)], ["FBA", num(st.fba)]];
  const known = parts.filter(([, v]) => v != null);
  const sg = i.stranded || null;
  const strandedUnits = sg && sg.known ? num(sg.units) : null;
  const notRead = known.length && known.length < parts.length ? `${parts.filter(([, v]) => v == null).map(([n]) => n).join(", ")} not read yet` : "";
  const strandedText = strandedUnits == null ? "" : `${strandedUnits.toLocaleString("en-US")} stranded at Amazon`;
  out.push({
    id: "stock",
    label: "Stock at cost",
    value: known.length ? money0(known.reduce((s, [, v]) => s + v, 0)) : "-",
    sub: [notRead, strandedText].filter(Boolean).join(" · "),
    tone: strandedUnits ? "warn" : "flat",
    target: "pipeline",
    split: parts.map(([label, v]) => ({ label, value: v == null ? "-" : money0(v) })),
  });
  return out;
}

// "2h ago" from two ms stamps (no clock read here - pure).
function ageText(at, now) {
  const a = num(at), n = num(now);
  if (a == null || n == null) return "";
  const m = Math.max(0, Math.floor((n - a) / 60000));
  if (m < 1) return "just now";
  if (m < 60) return `${m} min ago`;
  const h = Math.floor(m / 60);
  return h < 48 ? `${h}h ago` : `${Math.floor(h / 24)}d ago`;
}

// B-838 (v2.0.20): checking balance from Plaid; the card(s) owed and the age
// under it. g = plaidGlance(); null / not connected -> a "connect" tile.
function plaidTile(g, now) {
  const base = { id: "plaid", label: "Checking (Plaid)", target: "plaid" };
  if (!g || !g.connected) return { ...base, value: "-", sub: "Not connected - Settings → Plaid", tone: "flat" };
  const cur = g.checking ? num(g.checking.current) : null;
  const cards = Array.isArray(g.cards) ? g.cards : [];
  const owed = cards.map((c) => num(c && c.owed)).filter((v) => v != null);
  const bits = [];
  if (owed.length) bits.push(`${cards.length === 1 ? "Card" : "Cards"} owed ${money2(owed.reduce((s, v) => s + v, 0))}`);
  const age = ageText(g.at, now);
  if (age) bits.push(age);
  if (g.env === "sandbox") bits.push("Sandbox (test data)");
  if (g.error) bits.push(`Last read failed: ${String(g.error).slice(0, 80)}`);
  return {
    ...base,
    value: money2(cur),
    sub: bits.join(" · "),
    tone: g.error ? "warn" : cur != null && cur < 0 ? "down" : "flat",
  };
}

// FBA stage $ = what is at Amazon, at cost: Available + Inbound + Reserved
// (Unfulfillable is not sellable stock). tiles = fbaCardModel().tiles.
function fbaStockValue(tiles) {
  if (!Array.isArray(tiles) || !tiles.length) return null;
  let total = 0;
  let any = false;
  for (const t of tiles) {
    if (t && (t.key === "available" || t.key === "inboundAll" || t.key === "reservedTotal")) {
      const v = num(t.value);
      if (v != null) { total += v; any = true; }
    }
  }
  return any ? Math.round(total * 100) / 100 : null;
}
__m["dashboard-todo.js"] = { TARGETS, DO_NEXT_ORDER, SHIPMENT_NOTIFICATION_TYPE, DO_NEXT_LINE_MAX, shortTitle, strandedLineText, pricingOfferText, pricingLineText, money0, money2, changeLine, topSeverity, buildDoNext, SB_DAY_ROLLOVER_HOUR, chicagoClock, dayKeyAdd, usDate, sbCardRange, sumSbDays, buildSbCards, buildTiles, ageText, plaidTile, fbaStockValue };
})();
root.ShopperGlance = Object.freeze(Object.assign({}, ...Object.values(__m)));
})(self);
