// remote/fba-lib.js - GENERATED by test/_fba-bundle.mjs (B-510, v4.61). DO NOT EDIT.
// The phone's copy of lib/amzinv.js, lib/amzinv-chart.js, lib/amzinv-columns.js, lib/amzinv-chips.js, lib/fba-card.js, lib/remote-fba.js,
// wrapped unchanged. Edit lib/, then: node test/_fba-bundle.mjs --write
(function (root) {
const __m = {};
// ---- lib/amzinv.js ----
(function () {
"use strict";
// lib/amzinv.js - B-495 (v4.59). Amazon Inventory page, the PURE half.
//
// Reads the rows B-487 writes to "Shopper - Amazon Inventory History"
// (tab Hourly) and turns them into what the page draws: points per snapshot,
// the range slice (hourly for 24h, one point per local day otherwise), the
// previous-period overlay, the supply-squeeze (dip) warning, the extra
// alerts, shipment markers and the stacked-bar segments.
//
// ⚠ Every figure here is Amazon's RECORD at pull time, valued at the cost in
// effect when that row was written (rule 25). Nothing is predicted.
// ⚠ Leaf module: imports only lib/spapi.js (field list). No chrome, no DOM.
const { SPAPI_FIELDS } = { SPAPI_FIELDS: [] };

const AMZINV_SETTINGS_KEY = "shopperAmzInvSettings";
const DAY_MS = 86400000;

// ---- series ----------------------------------------------------------------
// Colour follows the ENTITY, never its rank (dataviz). Eight categorical slots
// (reference palette, light): the seven headline statuses + "Other". Sub-
// statuses reuse their parent's hue with a dash pattern (secondary encoding)
// so a ninth hue is never generated.
const SLOT = {
  blue: "#2a78d6", orange: "#eb6834", aqua: "#1baf7a", yellow: "#eda100",
  magenta: "#e87ba4", green: "#008300", violet: "#4a3aa7", red: "#e34948",
};
const INK = "#16112f", GREY = "#8a8698";
// [key, label, colour, dash, group] - group = headline key it refines.
const SERIES = [
  ["available", "Available", SLOT.blue, "", "available"],
  ["inboundAll", "Inbound (all)", SLOT.orange, "", "inboundAll"],
  ["inboundWorking", "Inbound Working", SLOT.orange, "2 3", "inboundAll"],
  ["inboundShipped", "Inbound Shipped", SLOT.orange, "6 3", "inboundAll"],
  ["inboundReceiving", "Inbound Receiving", SLOT.orange, "10 3 2 3", "inboundAll"],
  ["fcTransfer", "FC Transfer", SLOT.aqua, "", "fcTransfer"],
  ["fcProcessing", "FC Processing", SLOT.yellow, "", "fcProcessing"],
  ["customerOrders", "Customer Orders", SLOT.magenta, "", "customerOrders"],
  ["reservedTotal", "Reserved Total", GREY, "4 3", "reservedTotal"],
  ["unfulfillable", "Unfulfillable", SLOT.red, "", "unfulfillable"],
  ["unfCustomerDamaged", "Unf Customer Damaged", SLOT.red, "2 3", "unfulfillable"],
  ["unfWarehouseDamaged", "Unf Warehouse Damaged", SLOT.red, "6 3", "unfulfillable"],
  ["unfDistributorDamaged", "Unf Distributor Damaged", SLOT.red, "10 3 2 3", "unfulfillable"],
  ["unfCarrierDamaged", "Unf Carrier Damaged", SLOT.red, "1 4", "unfulfillable"],
  ["unfDefective", "Unf Defective", SLOT.red, "8 2", "unfulfillable"],
  ["unfExpired", "Unf Expired", SLOT.red, "4 2 1 2", "unfulfillable"],
  ["researching", "Researching", SLOT.violet, "", "researching"],
  ["researchShort", "Researching Short", SLOT.violet, "2 3", "researching"],
  ["researchMid", "Researching Mid", SLOT.violet, "6 3", "researching"],
  ["researchLong", "Researching Long", SLOT.violet, "10 3 2 3", "researching"],
  ["futureReserved", "Future Supply Reserved", GREY, "2 3", "future"],
  ["futureBuyable", "Future Supply Buyable", GREY, "6 3", "future"],
  ["total", "Total", INK, "", "total"],
  // B-547 (v4.68): Shopper's own figure (in transit + house + prep), NOT an
  // Amazon status - its own colour and a dotted line, never in a stack.
  ["ordered", "Ordered (Shopper)", "#8c6d46", "1 3", "ordered"],
];
// B-547: series that are NOT part of Amazon's Total - drawn as a line only,
// never stacked into a column or an area band.
const SEPARATE_SERIES = Object.freeze(["ordered"]);
const ORDERED_SERIES_HOVER = "Shopper's figure, not Amazon's: bought but not at Amazon yet = in transit + house + prep.";
// ⚠ Same labels as lib/ordered-inventory.js ORDERED_HISTORY_HEADER (this file
// is bundled for the phone and cannot import that one; a test holds them equal).
const ORDERED_COLS = Object.freeze({ units: "Ordered Units", value: "Ordered $", unpriced: "Ordered Unpriced Units" });
const SERIES_BY_KEY = Object.fromEntries(SERIES.map((s) => [s[0], { key: s[0], label: s[1], color: s[2], dash: s[3], group: s[4] }]));
const OTHER = { key: "other", label: "Other", color: SLOT.green, dash: "" };

// Stacked-bar segments must not overlap and must add up to Total. The rest
// of Total (anything Amazon counts that none of these covers) is "Other".
const BAR_BASE = ["available", "inboundAll", "fcTransfer", "fcProcessing", "customerOrders", "unfulfillable", "researching"];
const BAR_SPLIT = { inboundAll: ["inboundWorking", "inboundShipped", "inboundReceiving"] };

// ---- settings --------------------------------------------------------------
const AMZINV_DEFAULTS = Object.freeze({
  presets: [1, 7, 30, 90, 0], // days; 0 = All
  defaultRange: 30,
  measure: "value", // value | units
  // B-502 (v4.60): "columns" (one stacked column per day + lines on top) is the default.
  style: "columns", // columns | lines | area
  trendSeries: ["available", "inboundAll", "fcTransfer", "fcProcessing", "customerOrders", "unfulfillable", "researching", "ordered"],
  splitInboundInBars: false,
  showMarkers: true,
  showCompare: false,
  // B-515 (v4.63): the chosen series drawn as lines over the Columns chart,
  // and the top edge of each band on the Area chart. On by default (what
  // every release before this drew); the "Trendlines" button turns them off.
  showTrendlines: true,
  dip: { enabled: true, windowDays: 14, fireDays: 1, measure: "value" },
  alerts: {
    unfulfillableJump: { enabled: true, pct: 25, minUnits: 5 },
    researchingJump: { enabled: true, pct: 25, minUnits: 5 },
    // 100 units for 3 days: Receiving is non-zero whenever a shipment is being
    // checked in, so a low floor would warn on every normal shipment.
    receivingStuck: { enabled: true, minUnits: 100, days: 3 },
  },
});

const clampInt = (v, lo, hi, dflt) => {
  const n = Math.round(Number(v));
  return Number.isFinite(n) ? Math.min(hi, Math.max(lo, n)) : dflt;
};
const bool = (v, dflt) => (typeof v === "boolean" ? v : dflt);

function normalizeSettings(raw) {
  const d = AMZINV_DEFAULTS;
  const r = raw && typeof raw === "object" ? raw : {};
  let presets = Array.isArray(r.presets) ? r.presets.map((x) => clampInt(x, 0, 3650, null)).filter((x) => x !== null) : d.presets.slice();
  presets = [...new Set(presets)].sort((a, b) => (a === 0) - (b === 0) || a - b).slice(0, 8);
  if (!presets.length) presets = d.presets.slice();
  const defaultRange = presets.includes(clampInt(r.defaultRange, 0, 3650, -1)) ? clampInt(r.defaultRange, 0, 3650, 30) : presets.includes(d.defaultRange) ? d.defaultRange : presets[0];
  const trendSeries = Array.isArray(r.trendSeries) ? r.trendSeries.filter((k) => SERIES_BY_KEY[k]) : d.trendSeries.slice();
  // B-547 (v4.68): a series list saved before Ordered existed gets it once
  // (seriesVersion 2); after that, turning it off sticks.
  if (Array.isArray(r.trendSeries) && !(Number(r.seriesVersion) >= 2) && !trendSeries.includes("ordered")) trendSeries.push("ordered");
  const ra = r.alerts || {};
  const jump = (x, dd) => ({ enabled: bool(x && x.enabled, dd.enabled), pct: clampInt(x && x.pct, 1, 1000, dd.pct), minUnits: clampInt(x && x.minUnits, 0, 100000, dd.minUnits) });
  const rs = ra.receivingStuck || {};
  return {
    presets,
    defaultRange,
    measure: r.measure === "units" ? "units" : "value",
    style: r.style === "area" ? "area" : r.style === "lines" ? "lines" : "columns",
    trendSeries,
    splitInboundInBars: bool(r.splitInboundInBars, d.splitInboundInBars),
    showMarkers: bool(r.showMarkers, d.showMarkers),
    showCompare: bool(r.showCompare, d.showCompare),
    showTrendlines: bool(r.showTrendlines, d.showTrendlines),
    seriesVersion: 2,
    dip: {
      enabled: bool(r.dip && r.dip.enabled, d.dip.enabled),
      windowDays: clampInt(r.dip && r.dip.windowDays, 3, 90, d.dip.windowDays),
      fireDays: clampInt(r.dip && r.dip.fireDays, 1, 14, d.dip.fireDays),
      measure: r.dip && r.dip.measure === "units" ? "units" : "value",
    },
    alerts: {
      unfulfillableJump: jump(ra.unfulfillableJump, d.alerts.unfulfillableJump),
      researchingJump: jump(ra.researchingJump, d.alerts.researchingJump),
      receivingStuck: {
        enabled: bool(rs.enabled, d.alerts.receivingStuck.enabled),
        minUnits: clampInt(rs.minUnits, 1, 100000, d.alerts.receivingStuck.minUnits),
        days: clampInt(rs.days, 1, 30, d.alerts.receivingStuck.days),
      },
    },
  };
}

function rangeLabel(days) {
  if (days === 0) return "All";
  if (days === 1) return "24h";
  return `${days}d`;
}

// ---- history rows -> points ------------------------------------------------
const num = (v) => {
  if (v === "" || v == null) return null;
  const n = Number(String(v).replace(/[$,]/g, ""));
  return Number.isFinite(n) ? n : null;
};

// `values` = the Hourly tab as a 2-D array (row 1 = header). Columns are found
// by HEADER TEXT, so a future column added in the middle never shifts a field.
function parseHistory(values) {
  const rows = Array.isArray(values) ? values : [];
  if (rows.length < 2) return [];
  const head = rows[0].map((h) => String(h || "").trim());
  const col = (name) => head.indexOf(name);
  const tCol = col("Pulled At (UTC)");
  if (tCol < 0) return [];
  const map = SPAPI_FIELDS.map(([key, label]) => [key, col(`${label} Units`), col(`${label} $`)]);
  const unpricedCol = col("Unpriced Units");
  // B-547: blank / missing -> null (an older row has no Ordered figure).
  const oU = col(ORDERED_COLS.units), oV = col(ORDERED_COLS.value), oP = col(ORDERED_COLS.unpriced);
  const out = [];
  for (const r of rows.slice(1)) {
    const t = Date.parse(r[tCol]);
    if (!Number.isFinite(t)) continue;
    const units = {}, value = {};
    for (const [key, u, v] of map) {
      units[key] = u >= 0 ? num(r[u]) ?? 0 : 0;
      value[key] = v >= 0 ? num(r[v]) ?? 0 : 0;
    }
    units.inboundAll = units.inboundWorking + units.inboundShipped + units.inboundReceiving;
    value.inboundAll = value.inboundWorking + value.inboundShipped + value.inboundReceiving;
    units.ordered = oU >= 0 ? num(r[oU]) : null;
    value.ordered = oV >= 0 && units.ordered != null ? num(r[oV]) : null;
    const pt = { t, units, value, unpricedUnits: unpricedCol >= 0 ? num(r[unpricedCol]) ?? 0 : 0 };
    if (units.ordered != null) pt.orderedUnpriced = oP >= 0 ? num(r[oP]) ?? 0 : 0;
    out.push(pt);
  }
  out.sort((a, b) => a.t - b.t);
  return out;
}

// ---- US Central time (Zach's rule, v4.68) ----------------------------------
// Every date/time this page shows or groups by is US Central
// (America/Chicago), whatever the machine's clock is set to. Inline here, not
// lib/local-time.js: this file is bundled into the phone's remote/fba-lib.js,
// which carries only the lib/amzinv*.js / fba-card / remote-fba files.
const CT_ZONE = "America/Chicago";
const ctPartsFmt = new Intl.DateTimeFormat("en-US", { timeZone: CT_ZONE, year: "numeric", month: "numeric", day: "numeric", hour: "numeric", minute: "numeric", hourCycle: "h23" });
const ctDateTimeFmt = new Intl.DateTimeFormat("en-US", { timeZone: CT_ZONE, year: "numeric", month: "numeric", day: "numeric", hour: "numeric", minute: "2-digit" });
const ctDateFmt = new Intl.DateTimeFormat("en-US", { timeZone: CT_ZONE, year: "numeric", month: "numeric", day: "numeric" });

function centralParts(t) {
  const o = {};
  for (const p of ctPartsFmt.formatToParts(new Date(t))) if (p.type !== "literal") o[p.type] = Number(p.value);
  return { y: o.year, m: o.month, d: o.day, h: o.hour % 24, min: o.minute };
}

// "2026-09-24" - the Central calendar day of an instant.
function centralDayKey(t) {
  const p = centralParts(t);
  return `${p.y}-${String(p.m).padStart(2, "0")}-${String(p.d).padStart(2, "0")}`;
}
// Kept under its old name for existing callers; the day is Central now.
const localDayKey = centralDayKey;

// "9/24/2026, 3:05 PM CT" / "9/24/2026 CT" ("date").
function fmtCT(t, mode = "datetime") {
  if (t == null || !Number.isFinite(new Date(t).getTime())) return "—";
  return `${(mode === "date" ? ctDateFmt : ctDateTimeFmt).format(new Date(t))} CT`;
}

// The instant a Central calendar day ("YYYY-MM-DD") starts; null if bad.
function centralDayStart(ymd) {
  const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(String(ymd || ""));
  if (!m) return null;
  const wall = Date.UTC(+m[1], +m[2] - 1, +m[3]);
  let t = wall + 6 * 3600000; // CST guess
  for (let i = 0; i < 2; i++) {
    const p = centralParts(t);
    const offset = Date.UTC(p.y, p.m - 1, p.d, p.h, p.min) - t;
    t = wall - offset;
  }
  return t;
}
// The last second of that Central day (the old "T23:59:59" meaning).
function centralDayEnd(ymd) {
  const s = centralDayStart(ymd);
  if (s == null) return null;
  const next = centralDayKey(s + 30 * 3600000);
  return centralDayStart(next) - 1000;
}

// One point per Central day: the LAST snapshot of that day.
function dailyPoints(points) {
  const byDay = new Map();
  for (const p of points) byDay.set(localDayKey(p.t), p);
  return [...byDay.values()].sort((a, b) => a.t - b.t);
}

// days = 0 -> everything. 24h (days <= 2) keeps every hourly point.
function sliceRange(points, { days, now, from = null, to = null }) {
  let lo = -Infinity, hi = Infinity;
  if (from != null || to != null) { lo = from ?? -Infinity; hi = to ?? Infinity; }
  else if (days > 0) lo = now - days * DAY_MS;
  const inRange = points.filter((p) => p.t >= lo && p.t <= hi);
  const span = (Number.isFinite(hi) ? hi : now) - (Number.isFinite(lo) ? lo : (inRange[0] ? inRange[0].t : now));
  const hourly = span <= 2 * DAY_MS;
  return { points: hourly ? inRange : dailyPoints(inRange), hourly, lo, hi };
}

// The equal-length window just before [lo, hi], shifted forward so it lines
// up under the current one. Null when history does not reach back.
function previousPeriod(points, { lo, hi, hourly }) {
  if (!Number.isFinite(lo) || !Number.isFinite(hi)) return null;
  const len = hi - lo;
  const prev = points.filter((p) => p.t >= lo - len && p.t < lo);
  if (!prev.length || prev[0].t > lo - len + Math.max(len * 0.25, DAY_MS)) return null;
  const pts = hourly ? prev : dailyPoints(prev);
  return pts.map((p) => ({ ...p, t: p.t + len, shiftedFrom: p.t }));
}

// ---- warnings ----------------------------------------------------------------
const mean = (xs) => xs.reduce((a, b) => a + b, 0) / xs.length;

// Supply squeeze (Zach, 2026-09-22): Available BELOW its trailing average AND
// Inbound ABOVE its trailing average - stock stuck on the way in, less on the
// shelf. Daily points; average of the `windowDays` days BEFORE each day.
function dipSignal(points, dip, now = Date.now()) {
  const days = dailyPoints(points);
  const w = dip.windowDays;
  if (!dip.enabled) return { state: "off" };
  if (days.length < w + 1) return { state: "warming", have: days.length, need: w + 1 };
  const m = dip.measure === "units" ? "units" : "value";
  const flags = days.map((d, i) => {
    if (i < w) return null;
    const prior = days.slice(i - w, i);
    const availAvg = mean(prior.map((p) => p[m].available));
    const inbAvg = mean(prior.map((p) => p[m].inboundAll));
    return { t: d.t, fires: d[m].available < availAvg && d[m].inboundAll > inbAvg, available: d[m].available, availAvg, inbound: d[m].inboundAll, inbAvg };
  });
  let run = 0;
  for (let i = flags.length - 1; i >= 0 && flags[i] && flags[i].fires; i--) run++;
  const latest = flags[flags.length - 1];
  return { state: run >= dip.fireDays ? "firing" : "clear", run, latest, measure: m, bands: flags.filter((f) => f && f.fires).map((f) => f.t) };
}

function extraAlerts(points, alerts) {
  const days = dailyPoints(points);
  const out = [];
  const jump = (key, cfg, label) => {
    if (!cfg.enabled || days.length < 2) return;
    const a = days[days.length - 2].units[key], b = days[days.length - 1].units[key];
    const rise = b - a;
    if (rise >= cfg.minUnits && rise > 0 && (a === 0 || (rise / a) * 100 >= cfg.pct)) {
      out.push({ kind: key, text: `${label} jumped ${a} → ${b} units since the day before (+${rise}${a ? `, +${Math.round((rise / a) * 100)}%` : ""}).` });
    }
  };
  jump("unfulfillable", alerts.unfulfillableJump, "Unfulfillable");
  jump("researching", alerts.researchingJump, "Researching");
  const rs = alerts.receivingStuck;
  if (rs.enabled && days.length >= rs.days) {
    const tail = days.slice(-rs.days);
    if (tail.every((d) => d.units.inboundReceiving >= rs.minUnits)) {
      out.push({ kind: "receivingStuck", text: `Inbound Receiving has held at ${rs.minUnits}+ units for ${rs.days} day(s) in a row (now ${tail[tail.length - 1].units.inboundReceiving}) - check-in may be stuck.` });
    }
  }
  return out;
}

// ---- shipment markers --------------------------------------------------------
function parseScanpowerTime(s) {
  if (s == null) return null;
  if (typeof s === "number") return s;
  let t = String(s).trim().replace(" ", "T");
  t = t.replace(/([+-]\d\d)$/, "$1:00");
  const ms = Date.parse(t);
  return Number.isFinite(ms) ? ms : null;
}

// Batches past step 4 (sent), grouped per Central day of the batch's opened time.
function shipmentMarkers(batchMeta, { lo, hi }) {
  const byDay = new Map();
  for (const b of Array.isArray(batchMeta) ? batchMeta : []) {
    if (!b || !(Number(b.step) >= 4)) continue;
    const t = parseScanpowerTime(b.created);
    if (t == null || t < lo || t > hi) continue;
    const k = localDayKey(t);
    const m = byDay.get(k) || { t, names: [], units: 0 };
    m.names.push(b.name || b.batchId);
    m.units += Number(b.totalQuantity) || 0;
    byDay.set(k, m);
  }
  return [...byDay.values()].sort((a, b) => a.t - b.t);
}

// ---- stacked bars -------------------------------------------------------------
function barSegments(point, measure, splitInbound) {
  if (!point) return { segments: [], total: 0 };
  const m = measure === "units" ? "units" : "value";
  const keys = [];
  for (const k of BAR_BASE) {
    if (splitInbound && BAR_SPLIT[k]) keys.push(...BAR_SPLIT[k]);
    else keys.push(k);
  }
  const total = point[m].total;
  const segments = keys.map((k) => ({ ...SERIES_BY_KEY[k], v: point[m][k] || 0 }));
  const covered = segments.reduce((a, s) => a + s.v, 0);
  const rest = Math.round((total - covered) * 100) / 100;
  if (rest > 0) segments.push({ ...OTHER, v: rest });
  // A segment's share is of the bar's own total (or of the covered sum when
  // Amazon's Total is smaller - the bar must never overflow).
  const base = Math.max(total, covered);
  return { segments: segments.map((s) => ({ ...s, pct: base > 0 ? (s.v / base) * 100 : 0 })), total, base };
}

// ---- B-547: the "Ordered" row (Shopper's figure, apart from Amazon's) --------
const ORDERED_BAR_PARTS = Object.freeze([
  ["inTransit", "In transit", 1],
  ["house", "House", 0.7],
  ["prep", "Prep center", 0.45],
]);

// `ordered` = what SHOPPER_AMZINV_GET answers as `ordered` (or null).
// -> null when there is nothing to draw.
function orderedSegments(ordered, measure) {
  if (!ordered || !ordered.parts) return null;
  const m = measure === "units" ? "units" : "value";
  const color = SERIES_BY_KEY.ordered.color;
  const segments = ORDERED_BAR_PARTS.map(([k, label, opacity]) => {
    const part = ordered.parts[k] || {};
    const v = Number(part[m]) || 0;
    return { key: k, label, color, opacity, v };
  });
  const total = m === "units" ? Number(ordered.units) || 0 : Number(ordered.value) || 0;
  const base = segments.reduce((acc, x) => acc + Math.max(0, x.v), 0);
  return {
    total,
    unpricedUnits: Number(ordered.unpricedUnits) || 0,
    segments: segments.map((x) => ({ ...x, pct: base > 0 ? (Math.max(0, x.v) / base) * 100 : 0 })),
  };
}

// The line under the Ordered row. "" when nothing is on file.
function orderedNote(ordered) {
  if (!ordered || !ordered.parts) return "";
  const u = Number(ordered.unpricedUnits) || 0;
  const a = Number(ordered.unpricedAsinCount) || 0;
  const unpriced = u > 0 ? ` ${u} ordered unit(s)${a ? ` (${a} product${a === 1 ? "" : "s"})` : ""} have no cost on file - counted in units, left out of $.` : "";
  const when = ordered.asOf ? ` Pipeline as of ${fmtCT(ordered.asOf)}.` : "";
  return `Ordered is Shopper's own figure, not Amazon's: bought but not at Amazon yet = in transit + house + prep.${when}${unpriced}`;
}

// ---- formatting ----------------------------------------------------------------
function fmt(v, measure) {
  if (!Number.isFinite(v)) return "—";
  if (measure === "units") return Math.round(v).toLocaleString("en-US");
  return "$" + v.toLocaleString("en-US", { minimumFractionDigits: 0, maximumFractionDigits: 0 });
}
__m["amzinv.js"] = { AMZINV_SETTINGS_KEY, DAY_MS, SLOT, SERIES, SEPARATE_SERIES, ORDERED_SERIES_HOVER, ORDERED_COLS, SERIES_BY_KEY, OTHER, BAR_BASE, BAR_SPLIT, AMZINV_DEFAULTS, normalizeSettings, rangeLabel, parseHistory, CT_ZONE, centralParts, centralDayKey, localDayKey, fmtCT, centralDayStart, centralDayEnd, dailyPoints, sliceRange, previousPeriod, dipSignal, extraAlerts, parseScanpowerTime, shipmentMarkers, barSegments, ORDERED_BAR_PARTS, orderedSegments, orderedNote, fmt };
})();
// ---- lib/amzinv-chart.js ----
(function () {
"use strict";
// lib/amzinv-chart.js - B-495 (v4.59). The two charts on the Amazon
// Inventory page, drawn as plain SVG/HTML (no chart library - Zach: keep
// Shopper small; MV3 cannot load a CDN anyway). Every builder takes `doc`
// so tests hand in a tiny fake document. No innerHTML anywhere.
//
// Marks (dataviz): 2px lines, 2px surface gaps between stacked segments,
// recessive grid, legend always shown for >= 2 series, values in ink (never
// the series colour), a crosshair + tooltip on hover, a table view.
const { BAR_BASE, BAR_SPLIT, DAY_MS, ORDERED_SERIES_HOVER, SEPARATE_SERIES, SERIES_BY_KEY, centralParts, fmt, fmtCT } = __m["amzinv.js"];

const NS = "http://www.w3.org/2000/svg";
function svg(doc, tag, attrs = {}, kids = []) {
  const e = doc.createElementNS(NS, tag);
  for (const [k, v] of Object.entries(attrs)) if (v !== null && v !== undefined) e.setAttribute(k, String(v));
  for (const c of kids) if (c) e.appendChild(c);
  return e;
}
function el(doc, tag, cls, text) {
  const e = doc.createElement(tag);
  if (cls) e.className = cls;
  if (text != null) e.textContent = String(text);
  return e;
}

// ---- stacked bar (one per measure) ----------------------------------------
function drawStackedBar(doc, { title, segments, total, measure }) {
  const box = el(doc, "div", "ai-bar");
  const head = el(doc, "div", "ai-bar-head");
  head.append(el(doc, "span", "ai-bar-title", title), el(doc, "span", "ai-bar-total", fmt(total, measure)));
  const track = el(doc, "div", "ai-bar-track");
  track.setAttribute("role", "img");
  track.setAttribute("aria-label", `${title}: ` + segments.map((s) => `${s.label} ${fmt(s.v, measure)}`).join(", "));
  for (const s of segments) {
    if (!(s.v > 0)) continue;
    const seg = el(doc, "div", "ai-bar-seg");
    seg.style.width = `${s.pct}%`;
    seg.style.background = s.color;
    if (s.dash) seg.classList.add("ai-bar-seg-sub");
    seg.title = `${s.label}: ${fmt(s.v, measure)} (${s.pct.toFixed(1)}%)`;
    track.append(seg);
  }
  const legend = el(doc, "div", "ai-legend");
  for (const s of segments) {
    const item = el(doc, "span", "ai-legend-item");
    const sw = el(doc, "span", "ai-swatch");
    sw.style.background = s.color;
    if (s.dash) sw.classList.add("ai-swatch-sub");
    item.append(sw, el(doc, "span", "ai-legend-label", s.label), el(doc, "span", "ai-legend-val", `${fmt(s.v, measure)} · ${s.pct.toFixed(0)}%`));
    legend.append(item);
  }
  box.append(head, track, legend);
  return box;
}

// B-547 (v4.68): the "Ordered" row under Amazon's bars - Shopper's figure,
// its own bar, its own total, its own hover text. Never mixed into Amazon's.
function drawOrderedBar(doc, { title, seg, measure }) {
  const box = el(doc, "div", "ai-bar ai-bar-ordered");
  box.title = ORDERED_SERIES_HOVER;
  const head = el(doc, "div", "ai-bar-head");
  head.append(el(doc, "span", "ai-bar-title", title), el(doc, "span", "ai-bar-total", fmt(seg.total, measure)));
  const track = el(doc, "div", "ai-bar-track");
  track.setAttribute("role", "img");
  track.setAttribute("aria-label", `${title} (${ORDERED_SERIES_HOVER}) ` + seg.segments.map((s) => `${s.label} ${fmt(s.v, measure)}`).join(", "));
  for (const s of seg.segments) {
    if (!(s.v > 0)) continue;
    const d = el(doc, "div", "ai-bar-seg");
    d.style.width = `${s.pct}%`;
    d.style.background = s.color;
    d.style.opacity = String(s.opacity);
    d.title = `${s.label}: ${fmt(s.v, measure)} - ${ORDERED_SERIES_HOVER}`;
    track.append(d);
  }
  const legend = el(doc, "div", "ai-legend");
  for (const s of seg.segments) {
    const item = el(doc, "span", "ai-legend-item");
    const sw = el(doc, "span", "ai-swatch");
    sw.style.background = s.color;
    sw.style.opacity = String(s.opacity);
    item.append(sw, el(doc, "span", "ai-legend-label", s.label), el(doc, "span", "ai-legend-val", fmt(s.v, measure)));
    legend.append(item);
  }
  box.append(head, track, legend);
  return box;
}

// A line through the points that have a value; a gap (new "M") wherever a
// point has none (B-547: Ordered has no value on rows older than v4.68).
function gapPath(points, x, y, get) {
  let out = "", pen = false;
  for (const p of points) {
    const v = get(p);
    if (v == null || !Number.isFinite(v)) { pen = false; continue; }
    out += `${pen ? "L" : "M"}${x(p.t).toFixed(1)},${y(v).toFixed(1)}`;
    pen = true;
  }
  return out;
}

// Area mode stacks only statuses that do not overlap (a parent and its own
// parts would double-count): headline statuses, with Inbound replaced by its
// three parts when any part is chosen.
function stackableSeries(keys) {
  const chosen = new Set(keys);
  const out = [];
  for (const k of BAR_BASE) {
    const parts = BAR_SPLIT[k] ? BAR_SPLIT[k].filter((p) => chosen.has(p)) : [];
    if (parts.length) out.push(...parts);
    else if (chosen.has(k)) out.push(k);
  }
  return out;
}

function niceMax(v) {
  if (!(v > 0)) return 1;
  const p = Math.pow(10, Math.floor(Math.log10(v)));
  for (const m of [1, 2, 2.5, 5, 10]) if (m * p >= v) return m * p;
  return 10 * p;
}
// v4.68: US Central, whatever the machine's clock says.
function tickLabel(t, hourly) {
  const p = centralParts(t);
  return hourly ? `${p.h}:00` : `${p.m}/${p.d}`;
}

// ---- trend chart -------------------------------------------------------------
function drawTrend(doc, { points, keys, measure, style, compare = null, markers = [], bands = [], hourly, lo, hi, width = 860, height = 300, showLines = true }) {
  const m = measure === "units" ? "units" : "value";
  const wrap = el(doc, "div", "ai-trend");
  if (!points.length) {
    wrap.append(el(doc, "p", "ai-empty", "No history in this range yet - one row is added every hour."));
    return wrap;
  }
  const area = style === "area";
  // B-547: a separate series (Ordered) is never stacked - on Area it rides on top as a line.
  const shown = area ? [...stackableSeries(keys), ...keys.filter((k) => SEPARATE_SERIES.includes(k))] : keys.filter((k) => SERIES_BY_KEY[k]);
  const pad = { l: 64, r: 16, t: 14, b: 28 };
  const W = width - pad.l - pad.r, H = height - pad.t - pad.b;
  const t0 = Number.isFinite(lo) ? Math.min(lo, points[0].t) : points[0].t;
  const t1 = Number.isFinite(hi) ? hi : points[points.length - 1].t;
  const span = Math.max(t1 - t0, hourly ? 3600000 : DAY_MS);
  const x = (t) => pad.l + ((t - t0) / span) * W;

  const stacks = points.map((p) => {
    let acc = 0;
    const s = {};
    for (const k of shown) {
      const raw = p[m][k];
      if (SEPARATE_SERIES.includes(k)) { s[k] = [0, raw == null ? null : raw]; continue; }
      const v = raw || 0;
      s[k] = area ? [acc, (acc += v)] : [0, v];
    }
    return s;
  });
  let max = 0;
  for (const s of stacks) for (const k of shown) max = Math.max(max, s[k][1] || 0);
  if (compare && !area) for (const p of compare) for (const k of shown) max = Math.max(max, p[m][k] || 0);
  const yMax = niceMax(max);
  const y = (v) => pad.t + H - (v / yMax) * H;

  const root = svg(doc, "svg", { viewBox: `0 0 ${width} ${height}`, class: "ai-svg", role: "img", "aria-label": `${area ? "Stacked" : "Line"} trend of ${shown.map((k) => SERIES_BY_KEY[k].label).join(", ")}` });
  // grid + y ticks (recessive)
  for (let i = 0; i <= 4; i++) {
    const v = (yMax / 4) * i;
    root.append(svg(doc, "line", { x1: pad.l, x2: pad.l + W, y1: y(v), y2: y(v), class: "ai-grid" }));
    const lab = svg(doc, "text", { x: pad.l - 8, y: y(v) + 4, class: "ai-axis", "text-anchor": "end" });
    lab.textContent = fmt(v, m === "units" ? "units" : "value");
    root.append(lab);
  }
  // x ticks (<= 7)
  // B-510 (v4.61): at most 7 date labels, fewer on a narrow (phone) chart
  // so "9/12" and "9/15" never print on top of each other (~64px each).
  const maxTicks = Math.max(2, Math.min(7, Math.floor(W / 64)));
  const step = Math.max(1, Math.ceil(points.length / maxTicks));
  for (let i = 0; i < points.length; i += step) {
    const lab = svg(doc, "text", { x: x(points[i].t), y: height - 8, class: "ai-axis", "text-anchor": "middle" });
    lab.textContent = tickLabel(points[i].t, hourly);
    root.append(lab);
  }
  // dip bands (behind the data)
  for (const bt of bands) {
    const bx = x(bt - DAY_MS / 2);
    root.append(svg(doc, "rect", { x: Math.max(pad.l, bx), y: pad.t, width: Math.max(2, (DAY_MS / span) * W), height: H, class: "ai-band" }));
  }
  // previous period (dashed, lines mode only - a dashed stack would lie)
  if (compare && compare.length && !area) {
    for (const k of shown) {
      const d = gapPath(compare, x, y, (p) => (SEPARATE_SERIES.includes(k) ? p[m][k] : p[m][k] || 0));
      root.append(svg(doc, "path", { d, class: "ai-compare", stroke: SERIES_BY_KEY[k].color }));
    }
  }
  // series
  // Separate series (Ordered) last, so its line sits on top of the bands.
  const drawOrder = area ? [...shown.filter((k) => !SEPARATE_SERIES.includes(k)).reverse(), ...shown.filter((k) => SEPARATE_SERIES.includes(k))] : shown;
  for (const k of drawOrder) {
    const s = SERIES_BY_KEY[k];
    const sep = SEPARATE_SERIES.includes(k);
    const idx = new Map(points.map((p, i) => [p, i]));
    const top = gapPath(points, x, y, (p) => stacks[idx.get(p)][k][1]);
    if (area && !sep) {
      const bottom = points.map((p, i) => [x(p.t), y(stacks[i][k][0])]).reverse().map(([a, b]) => `L${a.toFixed(1)},${b.toFixed(1)}`).join("");
      root.append(svg(doc, "path", { d: top + bottom + "Z", fill: s.color, class: "ai-area", "data-key": k }));
    }
    // B-515 (v4.63): on the Area chart the band edges are the trendlines and
    // can be turned off; on the Lines chart the lines ARE the chart.
    if (!area || sep || showLines !== false) {
      root.append(svg(doc, "path", { d: top, stroke: s.color, "stroke-dasharray": s.dash || null, class: "ai-line", "data-key": k }));
    }
  }
  // shipment markers
  for (const mk of markers) {
    const mx = x(mk.t);
    if (mx < pad.l || mx > pad.l + W) continue;
    const g = svg(doc, "g", { class: "ai-marker" });
    g.append(svg(doc, "line", { x1: mx, x2: mx, y1: pad.t, y2: pad.t + H, class: "ai-marker-line" }));
    g.append(svg(doc, "path", { d: `M${mx - 6},${pad.t} L${mx + 6},${pad.t} L${mx},${pad.t + 9} Z`, class: "ai-marker-head" }));
    const tt = svg(doc, "title");
    tt.textContent = `Shipment sent: ${mk.names.join(", ")}${mk.units ? ` · ${mk.units} units` : ""}`;
    g.append(tt);
    root.append(g);
  }
  // hover: crosshair + tooltip
  const cross = svg(doc, "line", { x1: 0, x2: 0, y1: pad.t, y2: pad.t + H, class: "ai-cross", visibility: "hidden" });
  const hit = svg(doc, "rect", { x: pad.l, y: pad.t, width: W, height: H, class: "ai-hit" });
  root.append(cross, hit);
  const tip = el(doc, "div", "ai-tip");
  tip.hidden = true;
  const show = (clientX) => {
    const rect = root.getBoundingClientRect();
    const vx = ((clientX - rect.left) / rect.width) * width;
    let best = 0;
    for (let i = 1; i < points.length; i++) if (Math.abs(x(points[i].t) - vx) < Math.abs(x(points[best].t) - vx)) best = i;
    const p = points[best];
    cross.setAttribute("x1", x(p.t)); cross.setAttribute("x2", x(p.t)); cross.setAttribute("visibility", "visible");
    tip.textContent = "";
    tip.append(el(doc, "div", "ai-tip-head", fmtCT(p.t, hourly ? "datetime" : "date")));
    for (const k of shown) {
      if (p[m][k] == null) continue;
      const row = el(doc, "div", "ai-tip-row");
      const sw = el(doc, "span", "ai-swatch");
      sw.style.background = SERIES_BY_KEY[k].color;
      row.append(sw, el(doc, "span", "ai-tip-label", SERIES_BY_KEY[k].label), el(doc, "span", "ai-tip-val", fmt(p[m][k] || 0, m)));
      tip.append(row);
    }
    tip.hidden = false;
    tip.style.left = `${Math.min(88, Math.max(0, (x(p.t) / width) * 100))}%`;
  };
  // B-510 (v4.61): pointer events, so a finger works on the phone as well as
  // a mouse here - tap or drag to read a day. A mouse hides the tip when it
  // leaves; a finger lifting keeps it up until the next tap.
  hit.addEventListener("pointermove", (e) => show(e.clientX));
  hit.addEventListener("pointerdown", (e) => show(e.clientX));
  hit.addEventListener("pointerleave", (e) => {
    if (e && e.pointerType && e.pointerType !== "mouse") return;
    tip.hidden = true;
    cross.setAttribute("visibility", "hidden");
  });

  const legend = el(doc, "div", "ai-legend");
  for (const k of shown) {
    const s = SERIES_BY_KEY[k];
    const item = el(doc, "span", "ai-legend-item");
    const sw = el(doc, "span", "ai-swatch");
    sw.style.background = s.color;
    if (s.dash) sw.classList.add("ai-swatch-sub");
    item.append(sw, el(doc, "span", "ai-legend-label", s.label));
    if (SEPARATE_SERIES.includes(k)) item.title = ORDERED_SERIES_HOVER;
    legend.append(item);
  }
  if (compare && compare.length && !area) legend.append(el(doc, "span", "ai-legend-note", "Dashed = previous period"));
  if (markers.length) legend.append(el(doc, "span", "ai-legend-note", "▼ = shipment sent"));
  if (bands.length) legend.append(el(doc, "span", "ai-legend-note", "Shaded = supply-squeeze day"));
  const plot = el(doc, "div", "ai-plot");
  plot.append(root, tip);
  wrap.append(plot, legend);
  return wrap;
}

// ---- table view (accessibility + exact numbers) -----------------------------
function drawTable(doc, { points, keys, measure, hourly }) {
  const m = measure === "units" ? "units" : "value";
  const table = el(doc, "table", "ai-table");
  const tr = el(doc, "tr");
  tr.append(el(doc, "th", null, hourly ? "Time" : "Day"));
  for (const k of keys) tr.append(el(doc, "th", "ai-num", SERIES_BY_KEY[k].label));
  const thead = el(doc, "thead"); thead.append(tr);
  const tbody = el(doc, "tbody");
  for (const p of points.slice().reverse()) {
    const row = el(doc, "tr");
    row.append(el(doc, "td", null, fmtCT(p.t, hourly ? "datetime" : "date")));
    // B-547: an older row has no Ordered figure - "—", not 0.
    for (const k of keys) row.append(el(doc, "td", "ai-num", p[m][k] == null && SEPARATE_SERIES.includes(k) ? "—" : fmt(p[m][k] || 0, m)));
    tbody.append(row);
  }
  table.append(thead, tbody);
  return table;
}
__m["amzinv-chart.js"] = { svg, el, drawStackedBar, drawOrderedBar, gapPath, stackableSeries, niceMax, tickLabel, drawTrend, drawTable };
})();
// ---- lib/amzinv-columns.js ----
(function () {
"use strict";
// lib/amzinv-columns.js - B-502 (v4.60). The "Columns" style of the FBA
// Inventory "Over time" chart: one stacked column per day (per hour on the
// 24h range), its segments the same non-overlapping statuses as the "Right
// now" bar (lib/amzinv.js barSegments - one rule, one place), so each column
// adds up to Amazon's Total. The chip-selected series are drawn as lines on
// top of the columns.
//
// No innerHTML; takes `doc` so tests hand in a fake document.
const { DAY_MS, ORDERED_SERIES_HOVER, SEPARATE_SERIES, SERIES_BY_KEY, barSegments, fmt, fmtCT } = __m["amzinv.js"];
const { el, gapPath, niceMax, svg, tickLabel } = __m["amzinv-chart.js"];

// The columns for a list of points: [{ t, segments:[{key,label,color,dash,v,y0,y1}], total, top }].
function columnStacks(points, measure, splitInbound) {
  return points.map((p) => {
    const b = barSegments(p, measure, splitInbound);
    let acc = 0;
    const segments = b.segments.map((s) => ({ key: s.key, label: s.label, color: s.color, dash: s.dash, v: s.v, y0: acc, y1: (acc += s.v) }));
    return { t: p.t, segments, total: b.total, top: acc };
  });
}

function drawColumnsTrend(doc, { points, keys = [], measure, splitInbound = false, markers = [], bands = [], hourly, lo, hi, width = 860, height = 300, showLines = true }) {
  const m = measure === "units" ? "units" : "value";
  const wrap = el(doc, "div", "ai-trend");
  if (!points.length) {
    wrap.append(el(doc, "p", "ai-empty", "No history in this range yet - one row is added every hour."));
    return wrap;
  }
  // B-515 (v4.63): "Trendlines" off = columns only.
  const lines = showLines === false ? [] : keys.filter((k) => SERIES_BY_KEY[k]);
  const cols = columnStacks(points, m, splitInbound);
  const pad = { l: 64, r: 16, t: 14, b: 28 };
  const W = width - pad.l - pad.r, H = height - pad.t - pad.b;
  const slot = hourly ? 3600000 : DAY_MS;
  const t0 = Math.min(Number.isFinite(lo) ? lo : points[0].t, points[0].t) - slot / 2;
  const t1 = Math.max(Number.isFinite(hi) ? hi : points[points.length - 1].t, points[points.length - 1].t) + slot / 2;
  const span = Math.max(t1 - t0, slot);
  const x = (t) => pad.l + ((t - t0) / span) * W;
  const colW = Math.max(2, Math.min(40, (slot / span) * W * 0.72));

  let max = 0;
  for (const c of cols) max = Math.max(max, c.top, c.total);
  for (const p of points) for (const k of lines) max = Math.max(max, p[m][k] || 0);
  const yMax = niceMax(max);
  const y = (v) => pad.t + H - (v / yMax) * H;

  const root = svg(doc, "svg", { viewBox: `0 0 ${width} ${height}`, class: "ai-svg", role: "img", "aria-label": `Stacked columns by status${lines.length ? ` with lines for ${lines.map((k) => SERIES_BY_KEY[k].label).join(", ")}` : ""}` });
  for (let i = 0; i <= 4; i++) {
    const v = (yMax / 4) * i;
    root.append(svg(doc, "line", { x1: pad.l, x2: pad.l + W, y1: y(v), y2: y(v), class: "ai-grid" }));
    const lab = svg(doc, "text", { x: pad.l - 8, y: y(v) + 4, class: "ai-axis", "text-anchor": "end" });
    lab.textContent = fmt(v, m);
    root.append(lab);
  }
  // B-510 (v4.61): at most 7 date labels, fewer on a narrow (phone) chart
  // so "9/12" and "9/15" never print on top of each other (~64px each).
  const maxTicks = Math.max(2, Math.min(7, Math.floor(W / 64)));
  const step = Math.max(1, Math.ceil(points.length / maxTicks));
  for (let i = 0; i < points.length; i += step) {
    const lab = svg(doc, "text", { x: x(points[i].t), y: height - 8, class: "ai-axis", "text-anchor": "middle" });
    lab.textContent = tickLabel(points[i].t, hourly);
    root.append(lab);
  }
  for (const bt of bands) {
    const bx = x(bt) - (DAY_MS / span) * W / 2;
    root.append(svg(doc, "rect", { x: Math.max(pad.l, bx), y: pad.t, width: Math.max(2, (DAY_MS / span) * W), height: H, class: "ai-band" }));
  }
  // columns - 1px surface gap between segments (drawn as a white stroke)
  for (const c of cols) {
    const g = svg(doc, "g", { class: "ai-col", "data-t": c.t });
    for (const s of c.segments) {
      if (!(s.v > 0)) continue;
      g.append(svg(doc, "rect", {
        x: (x(c.t) - colW / 2).toFixed(1), y: y(s.y1).toFixed(1), width: colW.toFixed(1), height: Math.max(0.5, y(s.y0) - y(s.y1)).toFixed(1),
        fill: s.color, class: "ai-col-seg" + (s.dash ? " ai-col-seg-sub" : ""), "data-key": s.key,
      }));
    }
    root.append(g);
  }
  // lines on top
  for (const k of lines) {
    const s = SERIES_BY_KEY[k];
    // B-547: Ordered (a separate series) breaks where a row has no value.
    const d = gapPath(points, x, y, (p) => (SEPARATE_SERIES.includes(k) ? p[m][k] : p[m][k] || 0));
    root.append(svg(doc, "path", { d, stroke: s.color, "stroke-dasharray": s.dash || null, class: "ai-line ai-line-over", "data-key": k }));
  }
  for (const mk of markers) {
    const mx = x(mk.t);
    if (mx < pad.l || mx > pad.l + W) continue;
    const g = svg(doc, "g", { class: "ai-marker" });
    g.append(svg(doc, "line", { x1: mx, x2: mx, y1: pad.t, y2: pad.t + H, class: "ai-marker-line" }));
    g.append(svg(doc, "path", { d: `M${mx - 6},${pad.t} L${mx + 6},${pad.t} L${mx},${pad.t + 9} Z`, class: "ai-marker-head" }));
    const tt = svg(doc, "title");
    tt.textContent = `Shipment sent: ${mk.names.join(", ")}${mk.units ? ` · ${mk.units} units` : ""}`;
    g.append(tt);
    root.append(g);
  }
  const cross = svg(doc, "line", { x1: 0, x2: 0, y1: pad.t, y2: pad.t + H, class: "ai-cross", visibility: "hidden" });
  const hit = svg(doc, "rect", { x: pad.l, y: pad.t, width: W, height: H, class: "ai-hit" });
  root.append(cross, hit);
  const tip = el(doc, "div", "ai-tip");
  tip.hidden = true;
  const show = (clientX) => {
    const rect = root.getBoundingClientRect();
    const vx = ((clientX - rect.left) / rect.width) * width;
    let best = 0;
    for (let i = 1; i < cols.length; i++) if (Math.abs(x(cols[i].t) - vx) < Math.abs(x(cols[best].t) - vx)) best = i;
    const c = cols[best];
    cross.setAttribute("x1", x(c.t)); cross.setAttribute("x2", x(c.t)); cross.setAttribute("visibility", "visible");
    tip.textContent = "";
    tip.append(el(doc, "div", "ai-tip-head", `${fmtCT(c.t, hourly ? "datetime" : "date")} · Total ${fmt(c.total, m)}`));
    for (const s of c.segments.slice().reverse()) {
      if (!(s.v > 0)) continue;
      const row = el(doc, "div", "ai-tip-row");
      const sw = el(doc, "span", "ai-swatch");
      sw.style.background = s.color;
      row.append(sw, el(doc, "span", "ai-tip-label", s.label), el(doc, "span", "ai-tip-val", fmt(s.v, m)));
      tip.append(row);
    }
    // B-547: Ordered is not part of Amazon's Total - its own row under it.
    const pt = points[best];
    for (const k of lines) {
      if (!SEPARATE_SERIES.includes(k) || pt[m][k] == null) continue;
      const row = el(doc, "div", "ai-tip-row ai-tip-separate");
      const sw = el(doc, "span", "ai-swatch");
      sw.style.background = SERIES_BY_KEY[k].color;
      row.title = ORDERED_SERIES_HOVER;
      row.append(sw, el(doc, "span", "ai-tip-label", `${SERIES_BY_KEY[k].label} - not in Total`), el(doc, "span", "ai-tip-val", fmt(pt[m][k], m)));
      tip.append(row);
    }
    tip.hidden = false;
    tip.style.left = `${Math.min(88, Math.max(0, (x(c.t) / width) * 100))}%`;
  };
  // B-510 (v4.61): pointer events, so a finger works on the phone as well as
  // a mouse here - tap or drag to read a day. A mouse hides the tip when it
  // leaves; a finger lifting keeps it up until the next tap.
  hit.addEventListener("pointermove", (e) => show(e.clientX));
  hit.addEventListener("pointerdown", (e) => show(e.clientX));
  hit.addEventListener("pointerleave", (e) => {
    if (e && e.pointerType && e.pointerType !== "mouse") return;
    tip.hidden = true;
    cross.setAttribute("visibility", "hidden");
  });

  const legend = el(doc, "div", "ai-legend");
  const seen = new Set();
  for (const c of cols) for (const s of c.segments) {
    if (seen.has(s.key) || !(s.v > 0)) continue;
    seen.add(s.key);
    const item = el(doc, "span", "ai-legend-item");
    const sw = el(doc, "span", "ai-swatch");
    sw.style.background = s.color;
    if (s.dash) sw.classList.add("ai-swatch-sub");
    item.append(sw, el(doc, "span", "ai-legend-label", s.label));
    legend.append(item);
  }
  if (lines.length) legend.append(el(doc, "span", "ai-legend-note", `Lines: ${lines.map((k) => SERIES_BY_KEY[k].label).join(", ")}`));
  legend.append(el(doc, "span", "ai-legend-note", "Each column adds up to Total"));
  if (lines.some((k) => SEPARATE_SERIES.includes(k))) {
    const note = el(doc, "span", "ai-legend-note", "Ordered (dotted) = Shopper's in transit + house + prep, not in Total");
    note.title = ORDERED_SERIES_HOVER;
    legend.append(note);
  }
  if (markers.length) legend.append(el(doc, "span", "ai-legend-note", "▼ = shipment sent"));
  if (bands.length) legend.append(el(doc, "span", "ai-legend-note", "Shaded = supply-squeeze day"));
  const plot = el(doc, "div", "ai-plot");
  plot.append(root, tip);
  wrap.append(plot, legend);
  return wrap;
}
__m["amzinv-columns.js"] = { columnStacks, drawColumnsTrend };
})();
// ---- lib/amzinv-chips.js ----
(function () {
"use strict";
// lib/amzinv-chips.js - B-504 (v4.60). Which series chips the FBA Inventory
// "Over time" row shows. Headline statuses (a series whose group is itself)
// always show; sub-statuses (Inbound Working, Unf Expired, Future Supply ...)
// only after "More" - except one that is already switched on, which always
// shows so every line on the chart has a chip to turn it off.
function isHeadlineSeries(s) {
  return !!s && s.group === s.key;
}

function chipGroups(seriesList, onSet, showMore) {
  const on = onSet instanceof Set ? onSet : new Set(onSet || []);
  const shown = [];
  let hiddenCount = 0;
  for (const s of seriesList) {
    if (showMore || isHeadlineSeries(s) || on.has(s.key)) shown.push(s.key);
    else hiddenCount += 1;
  }
  return { shown, hiddenCount };
}
__m["amzinv-chips.js"] = { isHeadlineSeries, chipGroups };
})();
// ---- lib/fba-card.js ----
(function () {
"use strict";
// lib/fba-card.js - B-505 (v4.60). The Dashboard's FBA card, the PURE half.
//
// Zach, 2026-09-23: Available / Inbound / Reserved / Unfulfillable units and
// $ at cost with an "as of" time; the supply-squeeze and other FBA alerts as
// Dashboard banners; a 7-day sparkline of Available vs Inbound $; the card
// clicks through to the FBA Inventory page.
//
// ⚠ Reads the stored history only (the Hourly rows B-487 writes, via
// SHOPPER_AMZINV_GET) - never pulls from Amazon. Every figure is Amazon's
// RECORD at the newest pull (rule 25).
// ⚠ The alert wording lives HERE and the FBA Inventory page uses it too, so
// the Dashboard banner and the page banner can never say different things.
const { DAY_MS, ORDERED_SERIES_HOVER, dipSignal, extraAlerts, fmt, sliceRange } = __m["amzinv.js"];

const FBA_CARD_TILES = Object.freeze([
  ["available", "Available"],
  ["inboundAll", "Inbound"],
  ["reservedTotal", "Reserved"],
  ["unfulfillable", "Unfulfillable"],
]);
const FBA_SPARK_DAYS = 7;

function squeezeText(dip, settings) {
  const L = dip.latest, m = dip.measure;
  return `Supply squeeze: Available ${fmt(L.available, m)} is below its ${settings.dip.windowDays}-day average (${fmt(L.availAvg, m)}) while Inbound ${fmt(L.inbound, m)} is above its average (${fmt(L.inbAvg, m)}) - ${dip.run} day(s) running. Less is on the shelf for customers while more is stuck on the way in.`;
}

// Firing supply squeeze first, then the other alerts. [{ kind, text }]
function fbaAlerts(points, settings) {
  const out = [];
  const dip = dipSignal(points, settings.dip);
  if (dip.state === "firing") out.push({ kind: "squeeze", text: squeezeText(dip, settings) });
  return out.concat(extraAlerts(points, settings.alerts));
}

// B-547 (v4.68): the Ordered tile - Shopper's in transit + house + prep at
// the last pull (SHOPPER_AMZINV_GET's `ordered`), apart from Amazon's four.
// null when there is nothing on file.
function orderedTile(ordered) {
  if (!ordered || !ordered.parts) return null;
  const u = Number(ordered.unpricedUnits) || 0;
  return {
    key: "ordered",
    label: "Ordered",
    units: Number(ordered.units) || 0,
    value: Number(ordered.value) || 0,
    unpricedUnits: u,
    hover: ORDERED_SERIES_HOVER + (u > 0 ? ` ${u} unit(s) have no cost on file and are left out of $.` : ""),
  };
}

function fbaCardModel({ points, pulledAt = null, settings, now = Date.now(), ordered = null }) {
  const pts = Array.isArray(points) ? points : [];
  const latest = pts.length ? pts[pts.length - 1] : null;
  if (!latest) return { empty: true, tiles: [], alerts: [], spark: [], asOf: pulledAt || null, ordered: orderedTile(ordered) };
  const tiles = FBA_CARD_TILES.map(([key, label]) => ({
    key,
    label,
    units: latest.units[key] || 0,
    value: latest.value[key] || 0,
  }));
  const sl = sliceRange(pts, { days: FBA_SPARK_DAYS, now });
  const spark = sl.points.map((p) => ({ t: p.t, available: p.value.available || 0, inbound: p.value.inboundAll || 0 }));
  return {
    empty: false,
    asOf: pulledAt || latest.t,
    rowAt: latest.t,
    tiles,
    alerts: fbaAlerts(pts, settings),
    spark,
    unpricedUnits: latest.unpricedUnits || 0,
    ordered: orderedTile(ordered),
  };
}

// Two SVG path strings (Available, Inbound) over one shared y scale.
function sparkPaths(spark, { width = 240, height = 48, pad = 4 } = {}) {
  if (!spark.length) return { available: "", inbound: "", max: 0 };
  const max = Math.max(1, ...spark.map((p) => Math.max(p.available, p.inbound)));
  const t0 = spark[0].t, t1 = spark[spark.length - 1].t;
  const span = Math.max(t1 - t0, DAY_MS);
  const x = (t) => (spark.length === 1 ? width / 2 : pad + ((t - t0) / span) * (width - 2 * pad));
  const y = (v) => pad + (height - 2 * pad) * (1 - v / max);
  const path = (k) => spark.map((p, i) => `${i ? "L" : "M"}${x(p.t).toFixed(1)},${y(p[k]).toFixed(1)}`).join("");
  return { available: path("available"), inbound: path("inbound"), max };
}
__m["fba-card.js"] = { FBA_CARD_TILES, FBA_SPARK_DAYS, squeezeText, fbaAlerts, orderedTile, fbaCardModel, sparkPaths };
})();
// ---- lib/remote-fba.js ----
(function () {
"use strict";
// lib/remote-fba.js - B-510/B-511 (v4.61): FBA Inventory on the phone.
//
// Zach, 2026-09-23: "a mobile version of the FBA inventory window ...
// resized as necessary, but without really losing very much functionality",
// plus "an overview of that added to the mobile dashboard".
//
// A MIRROR, not a second model: the laptop parses the stored Hourly rows with
// lib/amzinv.js parseHistory() (the same call the FBA Inventory page makes)
// and the phone draws them with the SAME lib/amzinv*.js / lib/fba-card.js
// code, bundled into remote/fba-lib.js (see test/_fba-bundle.mjs). Nothing
// here recomputes a status, an alert or a squeeze.
//
// What travels, and why it is not every row: the phone polls the whole
// payload every 3 seconds, so the history is thinned to what the page can
// actually draw -
//   * every hourly row of the last FBA_REMOTE_HOURLY_DAYS days (the 24h view
//     and its previous-period overlay), and
//   * the LAST row of each local day (exactly what sliceRange() keeps for
//     every range longer than two days, and what the squeeze/alerts read),
//     newest FBA_REMOTE_MAX_DAYS days.
// The phone merges the two lists (dedupe on t), so sliceRange(), dipSignal(),
// extraAlerts() and previousPeriod() see the same points they would on the
// laptop. The one thing lost: a CUSTOM range of two days or less that ends
// before the hourly window shows one point per day instead of every hour.
//
// Each point is an array in FBA_REMOTE_KEYS order - [t, unpriced, ...units,
// ...value] - to keep the payload small. `decodeFbaPoints()` is the only
// reader; the phone's copy of it comes out of the same bundle.
//
// Read-only on purpose: no command, no write, no Amazon pull. The one Sheets
// read happens at most once every FBA_REMOTE_CACHE_MS.
const { SERIES, dailyPoints, normalizeSettings, parseHistory } = __m["amzinv.js"];

const FBA_REMOTE_HOURLY_DAYS = 3;
const FBA_REMOTE_MAX_DAYS = 400;
// The history gains one row an hour; the remote publishes up to once a
// second during a run. Re-read the workbook at most every 10 minutes.
const FBA_REMOTE_CACHE_MS = 10 * 60 * 1000;
const FBA_REMOTE_MAX_BATCHES = 30;
const FBA_REMOTE_KEYS = SERIES.map((s) => s[0]);

const DAY = 86400000;
const r2 = (v) => {
  const x = Number(v);
  return Number.isFinite(x) ? Math.round(x * 100) / 100 : 0;
};
const str = (v, max = 200) => (v == null ? null : String(v).slice(0, max));

// B-547 (v4.68): null stays null (an older row has no Ordered figure - the
// phone must draw a gap there, not a zero).
const r2n = (v) => (v == null ? null : r2(v));
function encodeFbaPoint(p) {
  const out = [Number(p.t), r2(p.unpricedUnits)];
  for (const k of FBA_REMOTE_KEYS) out.push(r2n(p.units && p.units[k]));
  for (const k of FBA_REMOTE_KEYS) out.push(r2n(p.value && p.value[k]));
  return out;
}

// `keys` = the key order the laptop sent (so an older phone bundle can still
// read a newer laptop's payload by name, not by position).
function decodeFbaPoints(rows, keys = FBA_REMOTE_KEYS) {
  const n = keys.length;
  const out = [];
  for (const a of Array.isArray(rows) ? rows : []) {
    if (!Array.isArray(a) || !Number.isFinite(Number(a[0]))) continue;
    const units = {}, value = {};
    for (let i = 0; i < n; i++) {
      units[keys[i]] = a[2 + i] === null ? null : Number(a[2 + i]) || 0;
      value[keys[i]] = a[2 + n + i] === null ? null : Number(a[2 + n + i]) || 0;
    }
    // Derived exactly as parseHistory() derives it (the sum of its three
    // parts), so the phone's figure is the laptop's to the last float bit.
    if (units.inboundWorking != null) {
      units.inboundAll = units.inboundWorking + units.inboundShipped + units.inboundReceiving;
      value.inboundAll = value.inboundWorking + value.inboundShipped + value.inboundReceiving;
    }
    out.push({ t: Number(a[0]), units, value, unpricedUnits: Number(a[1]) || 0 });
  }
  return out;
}

// Merge the daily and hourly lists back into one time-ordered list.
function mergeFbaPoints(daily, hourly) {
  const byT = new Map();
  for (const p of [...(daily || []), ...(hourly || [])]) byT.set(p.t, p);
  return [...byT.values()].sort((a, b) => a.t - b.t);
}

function shapeBatch(b) {
  return {
    batchId: str(b && b.batchId, 40),
    name: str(b && b.name, 80),
    created: b && typeof b.created === "number" ? b.created : str(b && b.created, 40),
    step: Number(b && b.step) || 0,
    totalQuantity: Number.isFinite(Number(b && b.totalQuantity)) ? Number(b.totalQuantity) : null,
  };
}

// B-547: only the figures the phone draws.
function shapeOrdered(o) {
  if (!o || !o.parts) return null;
  const part = (k) => ({ units: r2(o.parts[k] && o.parts[k].units), value: r2(o.parts[k] && o.parts[k].value), unpricedUnits: r2(o.parts[k] && o.parts[k].unpricedUnits) });
  return {
    available: true,
    units: r2(o.units),
    value: r2(o.value),
    unpricedUnits: r2(o.unpricedUnits),
    unpricedAsinCount: Number(o.unpricedAsinCount) || 0,
    parts: { inTransit: part("inTransit"), house: part("house"), prep: part("prep") },
    asOf: Number.isFinite(Number(o.asOf)) ? Number(o.asOf) : null,
  };
}

// Pure. `res` = what SHOPPER_AMZINV_GET answers (or { loadError }).
// `rawSettings` = the laptop's stored shopperAmzInvSettings (normalized here,
// so the phone starts on the same range, measure, style and series).
function projectFba(res, rawSettings, { nowMs = Date.now() } = {}) {
  const settings = normalizeSettings(rawSettings);
  if (!res || res.loadError) {
    return { available: false, loadError: str(res && res.loadError) || "no answer from Shopper", settings, builtAt: nowMs };
  }
  const points = parseHistory(res.values);
  const hourlyFrom = points.length ? points[points.length - 1].t - FBA_REMOTE_HOURLY_DAYS * DAY : 0;
  const hourly = points.filter((p) => p.t >= hourlyFrom);
  const daily = dailyPoints(points).slice(-FBA_REMOTE_MAX_DAYS);
  return {
    available: true,
    builtAt: nowMs,
    pulledAt: res.pulledAt || null,
    connected: res.connected !== false,
    error: str(res.error, 400),
    historyError: str(res.historyError, 400),
    historyUrl: str(res.historyUrl, 300),
    rowCount: points.length,
    settings,
    keys: FBA_REMOTE_KEYS.slice(),
    hourly: hourly.map(encodeFbaPoint),
    daily: daily.map(encodeFbaPoint),
    batches: (Array.isArray(res.batches) ? res.batches : []).slice(0, FBA_REMOTE_MAX_BATCHES).map(shapeBatch),
    // B-547 (v4.68): Shopper's Ordered at the last pull, for the phone's row + tile.
    ordered: shapeOrdered(res.ordered),
  };
}

let cache = { at: 0, value: null };

// For tests only.
function resetFbaCache() {
  cache = { at: 0, value: null };
}

// `read` = async () => ({ res, settings }). background.js passes the same
// read SHOPPER_AMZINV_GET makes. A failed read keeps the previous projection
// rather than blanking the phone; with nothing earlier it says so.
async function readFbaForRemote(read, { nowMs = Date.now(), ttlMs = FBA_REMOTE_CACHE_MS } = {}) {
  if (cache.value && nowMs - cache.at < ttlMs) return cache.value;
  try {
    const got = await read();
    cache = { at: nowMs, value: projectFba(got && got.res, got && got.settings, { nowMs }) };
  } catch (err) {
    if (cache.value) return cache.value;
    // Not cached: a failed read is retried on the next publish.
    return projectFba({ loadError: (err && err.message) || String(err) }, null, { nowMs });
  }
  return cache.value;
}
__m["remote-fba.js"] = { FBA_REMOTE_HOURLY_DAYS, FBA_REMOTE_MAX_DAYS, FBA_REMOTE_CACHE_MS, FBA_REMOTE_MAX_BATCHES, FBA_REMOTE_KEYS, encodeFbaPoint, decodeFbaPoints, mergeFbaPoints, shapeOrdered, projectFba, resetFbaCache, readFbaForRemote };
})();
root.ShopperFBA = Object.freeze(Object.assign({}, ...Object.values(__m)));
})(typeof self !== "undefined" ? self : globalThis);
