// remote/run-lib.js - GENERATED by test/_run-bundle.mjs (B-774 v2.0.9). DO NOT EDIT.
// The phone's copy of lib/queue-order.js, lib/line-outcome.js, lib/buy-stage.js, lib/spend-left.js, lib/queue-order-live.js, lib/last-report.js, wrapped unchanged.
// Edit lib/, then: node test/_run-bundle.mjs --write
(function (root) {
const __m = {};
// ---- lib/queue-order.js ----
(function () {
"use strict";
// lib/queue-order.js — P-260 (v3.44)
//
// ⚠⚠⚠ THE RULE, IN ZACH'S OWN WORDS (2026-09-15):
//   "I would like to get rid of that… the higher the score, the higher
//    priority it should have, while keeping it within its group of
//    confirmed versus contingency."
//
// ⚠⚠ WHAT WAS ACTUALLY THERE, MEASURED IN THE CODE BEFORE ANYTHING CHANGED.
// The backlog item said the queue "groups prep-center orders together and
// house orders together where it can." That is correct, and it is ONE
// comparator, in `nextPhaseLine()` inside `runBuyQueue()`:
//
//     .sort((a, b) => {
//       const addrDiff = (a.line.prepCenter ? 1 : 0) - (b.line.prepCenter ? 1 : 0);
//       return addrDiff !== 0 ? addrDiff : a.index - b.index;
//     });
//
// ⚠⚠⚠ THAT TERM OUTRANKED THE SCORE COMPLETELY. Every house line in a
// phase ran before every prep-centre line in the same phase, whatever
// either one scored — so a house line scoring 12 was bought before a prep
// line scoring 118. The sort was described in its own comment as "the
// address-grouping stable sort", which is exactly what it was; nothing was
// wrong with the code except that Zach does not want that rule.
//
// ⚠⚠⚠ AND IT MADE THE PAGE AND THE RUN DISAGREE — P-249's family, SIXTH
// INSTANCE. The Buy Queue page renders `state.lines` in array order, which
// IS score order (`compareByPriority`, applied when the preview is built).
// The run then re-sorted by address. **The screen showed one order and the
// money was spent in another**, and nothing said so. That matters because a
// run that stops early — budget, pause, abort — buys a PREFIX of the list.
//
// ⚠⚠ WHAT THE ADDRESS GROUPING WAS FOR, AND WHY REMOVING IT IS SAFE.
// Fewer shipping-address switches during a run. It is safe to remove
// because the address is not a run-level setting: `runRetailerQuantityBuy()`
// builds `run.targetShippingAddress` PER LINE from that line's own
// `prepCenter` flag, and checkout verifies the address it actually sees
// before placing the order. Interleaving costs address switches, not
// correctness — and `describeQueueOrder()` below PRINTS how many, every
// run, so the cost is visible rather than assumed.
//
// ⚠ CORRECTION TO THE BACKLOG ITEM, recorded here rather than only in the
// closure: it asked for a "deterministic tie-break (score → spend → ASIN)".
// The tie-break is ALREADY deterministic — `compareByPriority()` in
// lib/buylist.js is manualRank → priorityScore desc → ASIN, and the ASIN
// term was itself added in v2.34 (F/B9) for exactly this reason. Inserting
// a spend term would change the BUYLIST PAGE's own display order too (the
// comparator is deliberately shared, so the page and the queue agree), for
// no gain in determinism. `compareByPriority()` is therefore unchanged.
//
// ⚠ IMPORT-FREE ON PURPOSE, like lib/sent-fba (retired v3.91) and lib/arrival-cap (retired v3.91):
// `lib/buy-math.js` (which builds the queue state) and `background.js`
// (which runs it) both need this rule, and a leaf with no imports is the
// only shape neither can cycle against. Never two copies of one rule.

const QUEUE_ORDER_AUTOMATIC = "automatic";
const QUEUE_ORDER_MANUAL = "manual";

// The single explicit ordering field. Both the preview page and the run
// read it; nothing reads DOM order, and as of v3.44 nothing re-sorts.
//
// ⚠ Assigned as the array index at build time, so on a queue built before
// v3.44 (a persisted state restored after an upgrade) `queueOrderOf()`
// below falls back to the array index and behaves identically.
function assignQueueOrder(lines) {
  const list = Array.isArray(lines) ? lines : [];
  for (let i = 0; i < list.length; i++) {
    if (list[i]) list[i].queueOrder = i;
  }
  return list;
}

function queueOrderOf(line, index) {
  const q = Number(line && line.queueOrder);
  return Number.isFinite(q) ? q : Number(index) || 0;
}

// ⚠ A line inserted at the FRONT (a manually-added High-priority ASIN,
// v2.0.9) has to sort ahead of everything still pending. It gets a
// queueOrder BELOW the lowest one still in play rather than a renumber of
// the whole array — a renumber would rewrite the order of lines the run has
// already passed, and P-261's manual drag will want the same room.
function queueOrderBefore(lines, statuses) {
  const list = Array.isArray(lines) ? lines : [];
  const wanted = Array.isArray(statuses) ? statuses : [statuses];
  let min = null;
  for (let i = 0; i < list.length; i++) {
    const l = list[i];
    if (!l || !wanted.includes(l.status)) continue;
    const q = queueOrderOf(l, i);
    if (min === null || q < min) min = q;
  }
  return (min === null ? 0 : min) - 1;
}

// The comparator the run uses to pick its next line. Deliberately ONLY the
// order field — no address term, no score term, no status term. The score
// is already baked into the order field by the preview, and re-deriving it
// here is how the page and the run came to disagree in the first place.
function compareQueueOrder(a, b) {
  const qa = queueOrderOf(a && a.line, a && a.index);
  const qb = queueOrderOf(b && b.line, b && b.index);
  if (qa !== qb) return qa - qb;
  return (Number(a && a.index) || 0) - (Number(b && b.index) || 0);
}

function scoreOf(line) {
  const n = Number(line && line.priorityScore);
  return Number.isFinite(n) ? n : -1;
}

// ⚠ P-127 / P-159: the counter and the line that prints it ship together,
// and every field here prints even at zero.
//
// Reports three things about the order the run is ABOUT to execute:
//   1. how many lines are in each phase;
//   2. how many times the RETIRED address grouping would have put a
//      lower-scoring line ahead of a higher-scoring one — the measurement
//      that justifies the change, rather than an assertion that it helps;
//   3. how many times the shipping address changes under each rule — the
//      cost of the change, stated rather than hidden.
function describeQueueOrder(lines, { orderSource = QUEUE_ORDER_AUTOMATIC } = {}) {
  const list = Array.isArray(lines) ? lines : [];
  const out = {
    orderSource,
    pending: 0,
    pool: 0,
    addressSwitches: 0,
    addressSwitchesUnderOldRule: 0,
    overtakes: 0,
    worstOvertake: null,
  };

  for (const phase of ["pending", "pool"]) {
    const indexed = list
      .map((line, index) => ({ line, index }))
      .filter(({ line }) => line && line.status === phase);
    if (phase === "pending") out.pending = indexed.length;
    else out.pool = indexed.length;
    if (!indexed.length) continue;

    // The NEW order: the explicit field, nothing else.
    const now = [...indexed].sort(compareQueueOrder).map((x) => x.line);
    // The RETIRED order: every house line, then every prep line, each
    // group keeping its array order.
    const old = [...indexed]
      .sort((a, b) => {
        const addrDiff = (a.line.prepCenter ? 1 : 0) - (b.line.prepCenter ? 1 : 0);
        return addrDiff !== 0 ? addrDiff : a.index - b.index;
      })
      .map((x) => x.line);

    out.addressSwitches += countAddressSwitches(now);
    out.addressSwitchesUnderOldRule += countAddressSwitches(old);

    // Every pair the retired rule would have inverted. n is a few dozen at
    // most, so the honest O(n^2) count beats an approximation.
    for (let i = 0; i < old.length; i++) {
      for (let j = i + 1; j < old.length; j++) {
        const gap = scoreOf(old[j]) - scoreOf(old[i]);
        if (gap > 0) {
          out.overtakes += 1;
          if (!out.worstOvertake || gap > out.worstOvertake.gap) {
            out.worstOvertake = {
              gap,
              aheadAsin: String(old[i].asin || ""),
              aheadScore: scoreOf(old[i]),
              behindAsin: String(old[j].asin || ""),
              behindScore: scoreOf(old[j]),
            };
          }
        }
      }
    }
  }
  return out;
}

function countAddressSwitches(ordered) {
  let switches = 0;
  let prev = null;
  for (const line of ordered) {
    const here = !!(line && line.prepCenter);
    if (prev !== null && here !== prev) switches += 1;
    prev = here;
  }
  return switches;
}

// ─────────────────────────────────────────────────────────────────────────
// P-261 (v3.45) — THE MANUAL ORDER
// ─────────────────────────────────────────────────────────────────────────
//
// ⚠⚠⚠ ZACH, 2026-09-15: "a drag-and-drop system where I can reorder these,
// and then they will actually go down the list and buy in the order that I
// set."
//
// ⚠⚠ THE RUN EXECUTES FROM `queueOrder`, NEVER FROM DOM ORDER. A drag
// rewrites a stored list of ASINs; `buildBuyQueuePreview()` applies it to
// the two blocks it has just sorted by score; `freshBuyQueueState()` stamps
// `queueOrder` from the array as it then stands. One field, one order, the
// page and the run reading the same thing — which is the whole of P-260 and
// the reason this can be trusted at all.
//
// ⚠⚠ THE ORDER IS TIED TO ONE BUYLIST GENERATION. `generationId` is the
// buylist's own `finishedAt`. Regenerate the buylist and the id moves, the
// stored order stops applying, and the page SAYS SO rather than quietly
// half-applying yesterday's arrangement to today's lines.

const MANUAL_ORDER_VERSION = 1;

function buildManualOrder({ generationId, confirmed, contingency, savedAt = Date.now() }) {
  const clean = (xs) =>
    [...new Set((Array.isArray(xs) ? xs : []).map((a) => String(a || "")).filter(Boolean))];
  return {
    v: MANUAL_ORDER_VERSION,
    generationId: generationId == null ? null : generationId,
    confirmed: clean(confirmed),
    contingency: clean(contingency),
    savedAt,
  };
}

// ⚠ Declines rather than guessing, in four separate places. A stored order
// that cannot be trusted must read as "no manual order", never as a partial
// one — a half-applied arrangement is worse than none, because it looks
// deliberate.
function manualOrderState(stored, generationId) {
  if (!stored || typeof stored !== "object") return { usable: false, reason: "none" };
  if (stored.v !== MANUAL_ORDER_VERSION) return { usable: false, reason: "version" };
  if (!Array.isArray(stored.confirmed) || !Array.isArray(stored.contingency)) {
    return { usable: false, reason: "shape" };
  }
  if (stored.generationId == null || generationId == null) {
    return { usable: false, reason: "no-generation" };
  }
  if (String(stored.generationId) !== String(generationId)) {
    return { usable: false, reason: "regenerated" };
  }
  if (!stored.confirmed.length && !stored.contingency.length) {
    return { usable: false, reason: "empty" };
  }
  return { usable: true, reason: "ok" };
}

// Reorder one already-score-sorted block by a stored list of ASINs.
//
// ⚠ A line the stored order does not name goes to the END of its block, not
// into the middle by score. It is almost always a line approved AFTER the
// drag, and letting a new high scorer jump ahead of an arrangement Zach made
// by hand would silently overrule him. The count is reported so the page can
// say it out loud rather than leaving him to notice.
function applyOne(block, order) {
  const byAsin = new Map();
  for (const line of block || []) if (line && line.asin) byAsin.set(line.asin, line);
  const out = [];
  for (const asin of order || []) {
    const line = byAsin.get(asin);
    if (line) { out.push(line); byAsin.delete(asin); }
  }
  const unnamed = [...byAsin.values()];
  return { lines: [...out, ...unnamed], unnamed: unnamed.length };
}

function applyManualOrder(confirmed, contingency, stored, generationId) {
  const state = manualOrderState(stored, generationId);
  if (!state.usable) {
    return {
      confirmed: [...(confirmed || [])],
      contingency: [...(contingency || [])],
      orderSource: QUEUE_ORDER_AUTOMATIC,
      orderReason: state.reason,
      unnamed: 0,
    };
  }
  const c = applyOne(confirmed, stored.confirmed);
  const p = applyOne(contingency, stored.contingency);
  return {
    confirmed: c.lines,
    contingency: p.lines,
    orderSource: QUEUE_ORDER_MANUAL,
    orderReason: "ok",
    unnamed: c.unnamed + p.unnamed,
  };
}

// One list move, pure, used by the page's keyboard/tap fallback and by the
// drop handler alike — so the two paths cannot disagree about what a move
// means. Out-of-range indexes CLAMP rather than throw: a drop past the last
// row is a real gesture and means "put it last".
function moveAsin(list, asin, toIndex) {
  const arr = (Array.isArray(list) ? list : []).map((a) => String(a || ""));
  const from = arr.indexOf(String(asin || ""));
  if (from < 0) return arr;
  const without = arr.slice(0, from).concat(arr.slice(from + 1));
  const at = Math.max(0, Math.min(without.length, Number(toIndex) || 0));
  without.splice(at, 0, arr[from]);
  return without;
}
__m["queue-order.js"] = { QUEUE_ORDER_AUTOMATIC, QUEUE_ORDER_MANUAL, assignQueueOrder, queueOrderOf, queueOrderBefore, compareQueueOrder, describeQueueOrder, MANUAL_ORDER_VERSION, buildManualOrder, manualOrderState, applyManualOrder, moveAsin };
})();
// ---- lib/line-outcome.js ----
(function () {
"use strict";
// lib/line-outcome.js - B-774 (v2.0.9): OUT OF STOCK IS NOT A FAILURE.
//
// Until now the laptop coloured `failed` red together with the data-gap
// skips, `out_of_stock` grey together with "not attempted", the phone put
// out of stock with the skips, the dashboards never counted it at all, and a
// `partial` line that stopped because the retailer ran out read as a plain
// "Partial". Every screen now asks this file what a line's outcome is:
//
//   success | partial | outOfStock | failed | needsYou | skipped |
//   notStarted | inProgress | other
//
// and what its label is - "Partial - ran out of stock", "Partial - Walmart
// limit reached" (B-786), "Failed - recovery defect" (B-770), "... - retrying
// at the end of the run" (B-781/B-787/B-770 end-of-run retry).
//
// Pure. Laptop via buyqueue/run-view.js, phone via remote/run-lib.js (the
// same file, bundled), background via import (projection, last report).

const OUTCOME_KINDS = Object.freeze([
  "inProgress", "needsYou", "success", "partial", "outOfStock", "failed", "skipped", "notStarted", "other",
]);

const OUTCOME_META = Object.freeze({
  success: Object.freeze({ label: "Bought", plural: "Bought", tone: "good" }),
  partial: Object.freeze({ label: "Partial", plural: "Partial", tone: "partial" }),
  outOfStock: Object.freeze({ label: "Out of stock", plural: "Out of stock", tone: "oos" }),
  failed: Object.freeze({ label: "Failed", plural: "Failed", tone: "bad" }),
  needsYou: Object.freeze({ label: "Needs you", plural: "Need you", tone: "you" }),
  skipped: Object.freeze({ label: "Skipped", plural: "Skipped", tone: "quiet" }),
  notStarted: Object.freeze({ label: "Not started", plural: "Not started", tone: "plan" }),
  inProgress: Object.freeze({ label: "Buying", plural: "Buying", tone: "live" }),
  other: Object.freeze({ label: "Not bought", plural: "Not attempted / not needed", tone: "quiet" }),
});

const BY_STATUS = {
  bought: "success",
  confirmed_bought: "success",
  assumed_met: "success",
  partial: "partial",
  out_of_stock: "outOfStock",
  failed: "failed",
  error: "failed",
  needs_approval: "needsYou",
  needs_cap_approval: "needsYou",
  needs_confirmation: "needsYou",
  not_bought: "skipped",
  skipped_by_user: "skipped",
  skipped_no_url: "skipped",
  skipped_manual_retailer: "skipped",
  skipped_no_cost: "skipped",
  pending: "notStarted",
  pool: "notStarted",
  buying: "inProgress",
  confirming: "inProgress",
  not_attempted: "other",
  not_needed: "other",
};

function outcomeOf(line) {
  const status = String((line && line.status) || "pending");
  return BY_STATUS[status] || "other";
}

function isDefect(line) {
  if (!line) return false;
  if (line.recoveryDefect) return true;
  return /claude recovery defect/i.test(String(line.error || "") + " " + String(line.stopReason || ""));
}

function endedOutOfStock(line) {
  if (!line) return false;
  if (line.endedOutOfStock) return true;
  // Older lines (before the flag): the engine's own stop sentence.
  return /out of stock/i.test(String(line.stopReason || ""));
}

// `statusLabels` is the page's QUEUE_STATUS_LABELS (both pages already carry
// that map and a contract test keeps the two copies equal); `retryLater` is
// the queue's retryLaterLineIds (lines left for the end-of-run retry).
function outcomeLabel(line, statusLabels = {}, { retryLater = null } = {}) {
  const status = String((line && line.status) || "pending");
  const base = (statusLabels && statusLabels[status]) || OUTCOME_META[outcomeOf(line)].label;
  const kind = outcomeOf(line);
  const bits = [];
  if (kind === "partial") {
    if (line.limitReached) bits.push("Walmart limit reached");
    else if (endedOutOfStock(line)) bits.push("ran out of stock");
  }
  if ((kind === "failed" || kind === "partial") && isDefect(line)) bits.push("recovery defect");
  const later = retryLater && line && line.lineId != null && (
    (retryLater instanceof Set && retryLater.has(line.lineId)) ||
    (Array.isArray(retryLater) && retryLater.some((id) => String(id) === String(line.lineId)))
  );
  if (later && (kind === "failed" || kind === "partial")) bits.push("retrying at the end");
  return bits.length ? `${base} - ${bits.join(", ")}` : base;
}

function countOutcomes(lines) {
  const out = { total: 0 };
  for (const k of OUTCOME_KINDS) out[k] = 0;
  for (const l of Array.isArray(lines) ? lines : []) {
    out[outcomeOf(l)]++;
    out.total++;
  }
  return out;
}
__m["line-outcome.js"] = { OUTCOME_KINDS, OUTCOME_META, outcomeOf, outcomeLabel, countOutcomes };
})();
// ---- lib/buy-stage.js ----
(function () {
"use strict";
// lib/buy-stage.js - B-774 (v2.0.9): WHICH STEP OF A BUY SHOPPER IS ON.
//
// Before this file the only "right now" either screen had was
// buyQueueState.currentStep, which the queue sets once per line ("Opening X
// (ASIN)...") and then never touches while the engine works through the
// line - so both screens said "Opening X" for every order of a 15-order line.
// The engines' own narration (runState.currentStep, set by setStep()) never
// reached a screen at all.
//
// One pure rule now turns that narration into a stage id:
//   open -> check -> pack -> cap -> cart -> checkout -> (approve) -> place -> verify -> record
// stageForStep() is called inside setStep() for every engine step (no call
// site had to change); a site whose text is ambiguous may pass the stage as
// setStep's second argument instead. Queue-level moments (between lines,
// asking for a Source URL, the Sellerboard check before the first line, the
// end-of-queue checks, finished) are QUEUE_STAGES.
//
// Pure - no chrome, no DOM. Bundled unchanged for the phone into
// remote/run-lib.js (test/_run-bundle.mjs); the laptop page imports it
// through buyqueue/run-view.js. ONE copy of the labels.

const BUY_STAGES = Object.freeze([
  Object.freeze({ id: "open", label: "Open", long: "Opening the product page" }),
  Object.freeze({ id: "check", label: "Check", long: "Checking seller, price, shipping and rewards" }),
  Object.freeze({ id: "pack", label: "Pack size", long: "Working out the pack size" }),
  Object.freeze({ id: "cap", label: "Cap", long: "Reading the per-order cap" }),
  Object.freeze({ id: "cart", label: "Cart", long: "Putting the order in the cart" }),
  Object.freeze({ id: "checkout", label: "Checkout", long: "Going through checkout" }),
  Object.freeze({ id: "approve", label: "Approve", long: "Waiting for your approval", optional: true }),
  Object.freeze({ id: "place", label: "Place", long: "Placing the order" }),
  Object.freeze({ id: "verify", label: "Verify", long: "Confirming the order went through" }),
  Object.freeze({ id: "record", label: "Record", long: "Writing it to the sheets, Replen Pulse and Sellerboard" }),
]);

const QUEUE_STAGES = Object.freeze({
  next: "Moving on to the next line",
  collect: "Waiting for a Source URL",
  preflight: "Checking Sellerboard before the first line",
  wrapup: "Finishing up - double-checking the sheets",
  finished: "Finished",
});

const BUY_IDS = BUY_STAGES.map((s) => s.id);

function isBuyStage(id) {
  return BUY_IDS.includes(id);
}

function isQueueStage(id) {
  return Object.prototype.hasOwnProperty.call(QUEUE_STAGES, String(id || ""));
}

function stageIndex(id) {
  return BUY_IDS.indexOf(id);
}

// First match wins. The text is the engine's own setStep() sentence, with
// any "Walmart:" / "Target:" retailer prefix and any "[ASIN] " log prefix
// removed first. A sentence this does not know returns null and the stage
// on screen stays where it was - an unknown step never moves the tracker
// backwards or blanks it.
const STEP_RULES = [
  // Waiting on a person is an overlay on the stage, not a stage.
  [/^paused\b|^waiting for you:/, null],
  [/waiting for your approval/, "approve"],
  [/orders placed sheet|logging run to orders placed|updating replen pulse|updating sellerboard|order complete\b|recording /, "record"],
  [/verifying order #|waiting for order confirmation|confirmation page/, "verify"],
  [/placing order/, "place"],
  [/checkout|order review page|payment method|sms order updates/, "checkout"],
  [/reopening the product page|opening |required tabs|purchase-history tab|clearing .*cart|checking product page|^order \d+ of \d+/, "open"],
  [/cart\b|adding .*to cart|setting (cart )?quantity|preparing |filler item/, "cart"],
  [/order cap|per-item cap/, "cap"],
  [/multipack|pack size|pack sizes/, "pack"],
  [/reward|seller and price|shipping is the active|fulfillment method/, "check"],
];

function cleanStepText(text) {
  return String(text || "")
    .replace(/^\s*\[[A-Z0-9]{6,14}\]\s*/, "")
    .replace(/^\s*(walmart|target|sam's club|home depot|amazon)\s*:\s*/i, "")
    .trim();
}

function stageForStep(text) {
  const t = cleanStepText(text).toLowerCase();
  if (!t) return null;
  for (const [re, stage] of STEP_RULES) {
    if (re.test(t)) return stage;
  }
  return null;
}

// The queue's own sentences (qStep). "Opening <title> (<asin>)..." starts a
// line; everything else either names a queue moment or leaves the stage.
function stageForQueueStep(text) {
  const t = String(text || "").trim().toLowerCase();
  if (!t) return null;
  if (/^opening .*\([a-z0-9]{10}\)/.test(t)) return "open";
  if (/source database url|source url/.test(t)) return "collect";
  if (/sellerboard/.test(t) && /preflight|planner|before the first line/.test(t)) return "preflight";
  return null;
}

// "Order k of N" for the tracker headline. Before the order is placed, the
// order being worked on is the next one; from verify on it is the one just
// counted. Never 0, never above N when N is known.
function orderPosition(progress, stage) {
  const p = progress || {};
  const placed = Math.max(0, Number(p.ordersPlaced) || 0);
  const planned = Math.max(0, Number(p.ordersPlanned) || 0);
  const afterPlace = stageIndex(stage) >= stageIndex("verify");
  let k = afterPlace ? Math.max(1, placed) : placed + 1;
  if (planned && k > planned) k = planned;
  return {
    k,
    n: planned || null,
    estimated: !!p.ordersPlannedEstimated,
    text: planned ? `Order ${k} of ${p.ordersPlannedEstimated ? "~" : ""}${planned}` : `Order ${k}`,
  };
}

// What the tracker draws. `waiting` = a pause prompt or a pause is on
// screen: the current step turns amber ("waiting on you") instead of moving.
// The Approve step shows only when the run asks for approvals or is on it.
function trackerModel({ stage = null, status = "", waiting = false, approvalMode = "auto" } = {}) {
  const finished = status === "done" || status === "aborted" || status === "error" || stage === "finished";
  const showApprove = stage === "approve" || (approvalMode && approvalMode !== "auto");
  const stages = BUY_STAGES.filter((s) => !s.optional || showApprove);
  const cur = isBuyStage(stage) ? stages.findIndex((s) => s.id === stage) : -1;
  const steps = stages.map((s, i) => {
    let state = "todo";
    if (finished) state = "idle";
    else if (cur >= 0 && i < cur) state = "done";
    else if (cur >= 0 && i === cur) state = waiting ? "waiting" : "now";
    return { id: s.id, label: s.label, long: s.long, state };
  });
  const current = cur >= 0 ? stages[cur] : null;
  let headline = "";
  if (finished) headline = QUEUE_STAGES.finished;
  else if (isQueueStage(stage)) headline = QUEUE_STAGES[stage];
  else if (current) headline = waiting ? `Waiting on you - ${current.long.toLowerCase()}` : current.long;
  return { steps, current: current ? current.id : null, queueStage: isQueueStage(stage) ? stage : null, finished, headline };
}
__m["buy-stage.js"] = { BUY_STAGES, QUEUE_STAGES, isBuyStage, isQueueStage, stageIndex, cleanStepText, stageForStep, stageForQueueStep, orderPosition, trackerModel };
})();
// ---- lib/spend-left.js ----
(function () {
"use strict";
// lib/spend-left.js - B-774 (v2.0.9): THE MONEY BAND, ONE RULE.
//
// "Left to spend" was computed nowhere. The laptop's "Needed today" box
// showed the GOAL (stored goal, or the sheet's Needed Today when no goal is
// set) while the phone's "Needed today" showed the raw sheet figure - two
// different numbers under one label. Both screens now take every money
// figure from here:
//   run  - this run's spend against the target it was started with;
//   day  - every run today against today's goal.
// "Today's goal" is the stored goal when one is set, otherwise the sheet's
// Needed Today; `goalSource` says which, so the label can say so too.
//
// Pure. The laptop page imports it (buyqueue/run-view.js); the phone gets
// the RESULT in the projection (run.money) and never recomputes it.

const n = (v) => {
  const x = Number(v);
  return Number.isFinite(x) ? x : 0;
};
const cents = (v) => Math.round(v * 100) / 100;

function spendLeft({ totalSpent, spendTarget, goal, neededToday, spentToday, dayKnown = true } = {}) {
  const spent = n(totalSpent);
  const target = Math.max(0, n(spendTarget));
  const run = {
    spent: cents(spent),
    target: cents(target),
    left: cents(Math.max(0, target - spent)),
    met: target > 0 && spent >= target,
    pct: target > 0 ? Math.max(0, Math.min(100, (spent / target) * 100)) : 0,
  };
  if (!dayKnown) return { run, day: null };
  const stored = Math.max(0, n(goal));
  const needed = Math.max(0, n(neededToday));
  const dayGoal = stored > 0 ? stored : needed;
  const goalSource = stored > 0 ? "goal" : needed > 0 ? "needed" : "none";
  const today = n(spentToday);
  const day = {
    spent: cents(today),
    goal: cents(dayGoal),
    goalSource,
    neededToday: cents(needed),
    left: cents(Math.max(0, dayGoal - today)),
    met: dayGoal > 0 && today >= dayGoal,
    pct: dayGoal > 0 ? Math.max(0, Math.min(100, (today / dayGoal) * 100)) : 0,
  };
  return { run, day };
}

const GOAL_SOURCE_LABELS = Object.freeze({
  goal: "your daily goal",
  needed: "the sheet's Needed today (no goal set)",
  none: "no goal set",
});
__m["spend-left.js"] = { spendLeft, GOAL_SOURCE_LABELS };
})();
// ---- lib/queue-order-live.js ----
(function () {
"use strict";
// lib/queue-order-live.js - B-772 (v2.0.9): REORDER WHILE THE QUEUE RUNS.
//
// The running queue already re-picks its next line on every turn
// (nextPhaseLine() in background.js filters "pending", then "pool", and sorts
// by compareQueueOrder on line.queueOrder). So a live reorder only has to
// rewrite queueOrder on lines that have NOT started - the buy engine is not
// touched and cannot see a half-applied order (the handler runs between
// awaits).
//
// The rule:
//   - a block is "confirmed" (status pending) or "contingency" (status pool);
//   - the new order must name EXACTLY that block's not-started lines - a line
//     that started buying, finished or was skipped since the screen drew is
//     refused (the screen redraws), never silently dropped;
//   - those lines get the SAME queueOrder values they already hold, handed
//     out again in the new order. Locked rows (buying, bought, skipped) and
//     the other block never move, and a hand-added "High" line's
//     queueOrderBefore() slot survives.
//
// Pure. background.js (SHOPPER_BUY_QUEUE_REORDER_LIVE), the laptop page
// (drag, via buyqueue/run-view.js) and the phone (up/down, remote/run-lib.js).
const { queueOrderOf, compareQueueOrder, moveAsin } = __m["queue-order.js"];

const LIVE_BLOCK_STATUS = Object.freeze({ confirmed: "pending", contingency: "pool" });
const LIVE_REORDER_STATUSES = Object.freeze(["running", "paused", "collecting_urls"]);

const idKey = (id) => String(id);

// The block's not-started lines, in the order the run will take them.
function liveBlockLines(lines, block) {
  const status = LIVE_BLOCK_STATUS[block];
  if (!status) return [];
  return (Array.isArray(lines) ? lines : [])
    .map((line, index) => ({ line, index }))
    .filter(({ line }) => line && line.status === status)
    .sort(compareQueueOrder)
    .map(({ line }) => line);
}

function liveBlockIds(lines, block) {
  return liveBlockLines(lines, block).map((l) => l.lineId);
}

function canReorderLive(queueStatus) {
  return LIVE_REORDER_STATUSES.includes(String(queueStatus || ""));
}

// Mutates queueOrder on the block's lines ONLY when the whole request is
// valid. Returns { ok, reason, moved }.
function applyLiveOrder(lines, block, orderedLineIds) {
  if (!LIVE_BLOCK_STATUS[block]) return { ok: false, reason: `Unknown block "${block}".`, moved: 0 };
  const want = Array.isArray(orderedLineIds) ? orderedLineIds.map(idKey) : null;
  if (!want || !want.length) return { ok: false, reason: "No order was sent.", moved: 0 };
  if (new Set(want).size !== want.length) return { ok: false, reason: "The new order names a line twice.", moved: 0 };
  const current = liveBlockLines(lines, block);
  const byId = new Map(current.map((l) => [idKey(l.lineId), l]));
  for (const id of want) {
    if (!byId.has(id)) {
      const other = (Array.isArray(lines) ? lines : []).find((l) => l && idKey(l.lineId) === id);
      const why = other ? `it is ${other.status === "buying" ? "being bought now" : `"${other.status}"`}` : "it is not in this queue";
      return { ok: false, reason: `Line ${id} can't be moved - ${why}. The list was redrawn.`, moved: 0 };
    }
  }
  if (want.length !== current.length) {
    return { ok: false, reason: "The queue changed while you were moving lines (a line started or was added). The list was redrawn.", moved: 0 };
  }
  const slots = current.map((l) => queueOrderOf(l, lines.indexOf(l))).sort((a, b) => a - b);
  let moved = 0;
  want.forEach((id, i) => {
    const line = byId.get(id);
    if (queueOrderOf(line, lines.indexOf(line)) !== slots[i]) moved++;
    line.queueOrder = slots[i];
  });
  return { ok: true, reason: "", moved };
}

// One move inside a block - the SAME move rule the preview uses
// (lib/queue-order.js moveAsin, which works on any string id).
function moveLiveLine(lines, block, lineId, toIndex) {
  const ids = liveBlockIds(lines, block);
  const asText = ids.map(idKey);
  const next = moveAsin(asText, idKey(lineId), toIndex);
  const back = new Map(ids.map((id) => [idKey(id), id]));
  return next.map((s) => back.get(s));
}

// The run list on screen: what is being bought, what comes next (in the
// order it will be bought), the fallback pool, and everything that is over.
const NOW_STATUSES = new Set(["buying", "confirming"]);
function runListGroups(lines, { currentLineId = null, queueStatus = "" } = {}) {
  const list = Array.isArray(lines) ? lines : [];
  const live = canReorderLive(queueStatus) || queueStatus === "aborting";
  const now = [];
  const done = [];
  for (const l of list) {
    if (!l) continue;
    if (l.status === "pending" || l.status === "pool") continue;
    const isCurrent = live && currentLineId != null && idKey(l.lineId) === idKey(currentLineId);
    if (NOW_STATUSES.has(l.status) || (isCurrent && !["bought", "confirmed_bought", "assumed_met"].includes(l.status))) now.push(l);
    else done.push(l);
  }
  return [
    { key: "now", title: "Buying now", lines: now, reorder: null },
    { key: "upNext", title: "Up next", lines: liveBlockLines(list, "confirmed"), reorder: "confirmed" },
    { key: "pool", title: "Fallback pool - only if short of the target", lines: liveBlockLines(list, "contingency"), reorder: "contingency" },
    { key: "done", title: "Done", lines: done, reorder: null },
  ];
}
__m["queue-order-live.js"] = { LIVE_BLOCK_STATUS, LIVE_REORDER_STATUSES, liveBlockLines, liveBlockIds, canReorderLive, applyLiveOrder, moveLiveLine, runListGroups };
})();
// ---- lib/last-report.js ----
(function () {
"use strict";
// lib/last-report.js - B-776 (v2.0.9): THE LAST RUN'S REPORT OUTLIVES THE QUEUE.
//
// buildBuyQueueReport() put the report inside buyQueueState only, so "Start
// New Buy Queue" (CLEAR) or the stale auto-clear threw it away, and the
// phone - which only saw run.report - lost it with them. At finish the
// background now also writes storage key shopperBuyQueueLastReport =
// buildLastReport(state); the phone gets it as `lastReport` and the
// Dashboards open it.
//
// Pure. background.js (write), lib/remote-protocol.js (projection), the
// phone (shouldPopReport, via remote/run-lib.js).
const { countOutcomes } = __m["line-outcome.js"];

const LAST_REPORT_KEY = "shopperBuyQueueLastReport";
const FINISHED_STATUSES = Object.freeze(["done", "aborted", "error"]);

function isFinishedStatus(status) {
  return FINISHED_STATUSES.includes(String(status || ""));
}

function buildLastReport(state, nowMs = Date.now()) {
  if (!state || !state.report || !isFinishedStatus(state.status)) return null;
  return {
    queueId: state.queueId || null,
    status: state.status,
    finishedEarly: !!(state.status === "done" && /finished early/i.test(String(state.currentStep || ""))),
    startedAt: state.startedAt || null,
    finishedAt: state.finishedAt || nowMs,
    totalSpent: Number(state.totalSpent) || 0,
    spendTarget: Number(state.spendTarget) || 0,
    lineCount: Array.isArray(state.lines) ? state.lines.length : 0,
    outcomes: countOutcomes(state.lines),
    report: state.report,
  };
}

// The phone pops the report up ONCE, only for a run that finished while the
// app was open: `baselineAt` is the lastReport.finishedAt the app saw on its
// FIRST payload (undefined until then), `seenAt` the one it last dismissed.
function shouldPopReport({ baselineAt, lastReportAt, seenAt } = {}) {
  if (baselineAt === undefined) return false;
  const at = Number(lastReportAt) || 0;
  if (!at) return false;
  return at > (Number(baselineAt) || 0) && at > (Number(seenAt) || 0);
}

// One line for the push and the sheet heading.
function describeLastReport(lr) {
  if (!lr) return "";
  const money = (v) => `$${(Number(v) || 0).toFixed(2)}`;
  const o = lr.outcomes || {};
  const how = lr.status === "aborted" ? "stopped (aborted)" : lr.status === "error" ? "stopped with an error" : lr.finishedEarly ? "finished early" : "finished";
  const bits = [`${o.success || 0} bought`];
  if (o.partial) bits.push(`${o.partial} partial`);
  if (o.outOfStock) bits.push(`${o.outOfStock} out of stock`);
  if (o.failed) bits.push(`${o.failed} failed`);
  if (o.needsYou) bits.push(`${o.needsYou} need you`);
  return `Buy Queue ${how} - spent ${money(lr.totalSpent)}${lr.spendTarget ? ` of ${money(lr.spendTarget)}` : ""}. ${bits.join(", ")}.`;
}
__m["last-report.js"] = { LAST_REPORT_KEY, FINISHED_STATUSES, isFinishedStatus, buildLastReport, shouldPopReport, describeLastReport };
})();
root.ShopperRunLib = Object.freeze(Object.assign({}, ...Object.values(__m)));
})(typeof self !== "undefined" ? self : globalThis);
